### ISSUE TITLE
old versions of bundled tools in git repo

### ISSUE THREAD

**Issue by seru71** [tseemann/snippy#102]
Hi,

Just tried installing Snippy from source, and found out that it checks for versions of tools. The ones bundled with the source (I used HEAD in master branch) are older than required:
freebayes (no version), while 1.1 is required
snpEff 4.1l, while 4.3 is required

Possibly other too, I haven't got that far. Checking out release v3.0 got me started snappier:)

**Comment by tseemann** [comment]
@seru71 thanks for the reminder. i don't really want to put people to use the binaries as there are much better ways to install software dependencies (Homebrew and Bioconda) and they are more likely to actually work.  I originally put them there just to help people as a "last resort". It takes a lot of work to source "static" binaries but I'll see what I can do.

I will eventually only support Brew, Conda or Manual installation in 4.0

**Comment by seru71** [comment]
I see your point and totally agree. Just wanted to let you know that there
was a version problem with the binaries, in case you were planning to
release them as they were

**Comment by tseemann** [comment]
@seru71 I have fixed these now.
