### ISSUE TITLE
Linux freebayes and snpEff versions

### ISSUE THREAD

**Issue by jbisanz** [tseemann/snippy#103]
Thanks for the software! I am looking forward to the results. A quick fyi: I obtained snippy 3.2-dev from github and found that I was unable to run due to incorrect versions of dependencies on CentOS 6.9. After a little digging I see the following version info for the problematic packages that came with the github download:

$ ~/sftwr/snippy-master/binaries/linux/freebayes --version
version:  

$ ~/sftwr/snippy-master/binaries/noarch/snpEff -version
4.1l

I was able to bypass this issue by commenting the following lines out and it seems to be running smoothly now:
#parse_version( 'freebayes --version', 1.1, qr/\sv(\d+\.\d+)/        );
#parse_version( 'snpEff -version',     4.3, qr/(\d+\.\d+)/           );

Is it problematic to be using the included freebayes and snpEff dists?

**Comment by tseemann** [comment]
Yes, this was also just reported in https://github.com/tseemann/snippy/issues/102

I'll try and fix it.

 I'd prefer people installed using `brew` or `conda` - this would take care of those problems.

**Comment by tseemann** [comment]
I've updated them @jbisanz
