### ISSUE TITLE
.aligned explanation in readme

### ISSUE THREAD

**Issue by EugeneBragin** [tseemann/snippy#105]
It says: .aligned.fa | A version of the reference but with `-` at position with `depth=0` and `N` for `0 < depth < --minfrac` (**does not have variants**)
But mincov is used in the code. Do you mean mincov, not minfrac? 

Cheers.

**Comment by tseemann** [comment]
@EugeneBragin you are correct! I did mean `mincov`. 
Thanks for letting me know, I've fixed for the next release.
