### ISSUE TITLE
Allele numbering core vcf

### ISSUE THREAD

**Issue by thorellk** [tseemann/snippy#106]
Hi! 

I am writing a script to parse the snippy-core output and wonder if allele 2 or 3 could be the major allele in the snippy core vcf? Or is it always 0 or 1? Are they just numbered after the order in which they occur in the core genome parsing or after any kind of frequency?

Best wishes,

Kaisa

**Comment by thorellk** [comment]
Ping @tseemann, did you have time to look into this?

**Comment by thorellk** [comment]
I actually checked it myself in the latest core alignment I did. Seems like "numbered after the order in which they occur in the core genome parsing" is the most plausible answer since any of 0,1,2,3 can be the major allele.

**Comment by tseemann** [comment]
I believe that is in order of the FOLDERS you pass on the command line, but with `--ref` being placed at the front if you don't have `--noref`.

So usually the 'major' allele `GT=0` will be the reference allele. The `GT={2,3,4}` will be based on the order they appear in the command line.

Here's my code I inferred this behaviour from:
```
for my $dir (@ARGV) {
  my $id = dir_to_id($dir);
...
    my @var = map { $var->{$_} } @id;
    ...
    # multi-sample VCF
    my @allele = uniq(@var);
    my %GT_of = ( map { ($allele[$_] => $_) } (0 .. @allele-1) );
    print VCF tsv($seq, $pos, '.',
                  $allele[0], join(',', @allele[1..$#allele]),
                  '9999.00', '.', "TYPE=snp", "GT",
                  (map { $GT_of{$_} } @var),
               );
```
