### ISSUE TITLE
rRNA SNP nucleotide position

### ISSUE THREAD

**Issue by conmeehan** [tseemann/snippy#111]
This may just be something I am missing but when I run snippy and look at the snps.tab file, I see nucleotide and amino acid positions of SNPs within a gene if it is a CDS but not if it is an rRNA. Of course no AA number should be there but is there anyway to find out the nucleotide number of the SNP in the gene when it is an rRNA related gene? An example is:
NC_000962	979704	snp	G	C	C:91 G:0	CDS	+	343/867	115/288	missense_variant c.343G>C p.Gly115Arg	Rv0881		tRNA/rRNA methyltransferase
NC_000962	1473246	snp	A	G	G:77 A:0	rRNA	+			non_coding_transcript_variant  	Rvnr01	rrs	16S ribosomal RNA

Any help is appreciated!

Con

**Comment by tseemann** [comment]
I am running `snpEff` and giving it all the features. Not sure why it only does CDS. In the `reference` subfolder, there is a `.gff` file that I generate.  Does it have the rRNA features in it?

**Comment by tseemann** [comment]
`"snpEff ann -noStats -no-downstream -no-upstream -no-intergenic -no-utr` is what gets run.

The index includes and features which match this pattern:
` next if $f->primary_tag =~ m/^(source|misc_feature|gene|RBS)$/;`
ie. those ones are skipped
