### ISSUE TITLE
different refs with different .consensus.fa?

### ISSUE THREAD

**Issue by indexofire** [tseemann/snippy#112]
I am doing virus mapping to get genomes. I dont get why I changed the reference of virus genome, snippy returned different snps.consensus.fa with about >30 snps differ. Is that means the method is worng to get virus genome? or Should I remove duplicates first?

anyone can help? thanks alot!

**Comment by tseemann** [comment]
If you change the reference genome, then yes, you will get a different number of SNPs between your reads and the reference?

**Comment by indexofire** [comment]
The method is fine in virus genome mapping assembly I think. I will check if it's the pollution of different samples(highly similar in genomes, so the related reads vary the results) or the sample is a metagenomic ngs(virus mixed infection). 

Thanks you very much.
