### ISSUE TITLE
about the "bwa mem -R " in snippy or wombac

### ISSUE THREAD

**Issue by soybean1015** [tseemann/snippy#115]
i always get a err when i use the wombac or snippy,i think i find a bug in the file snippy. so , i  modify the line 214 to [$bwaopt .= qq{ -v 2 -M -R '\\@RG\\\tID:$rgid\\\tSM:$rgid'};] then i can get the right result using the command [snippy --outdir test --ref example.fna --R1 reads_R1.fastq.gz --R2 reads_R2.fastq.gz]. I want to know if what i did is rigth ? do any other friend find this problem ?

**Comment by nextgenusfs** [comment]
I also got the same error, although this used to not be an error, so perhaps BWA has changed slightly?  The error in the log file looks like this:
```
### (bwa mem  -v 2 -M -R '@RG	ID:snps	SM:snps' -t 18 reference/ref.fa /Volumes/LinuxHD/ophiostoma/genohub_data/JP101/clean.1.fq.gz /Volumes/LinuxHD/ophiostoma/genohub_data/JP101/clean.2.fq.gz | samtools view -@ 18 -F 3844 -q 60 -S -b -u -T reference/ref.fa - | samtools sort -O bam -o snps.bam -@ 18 -)

[E::bwa_set_rg] the read group line contained literal <tab> characters -- replace with escaped tabs: \t
```

As @soybean1015 mentions, escaping the tabs in the snippy perl script correct this behavior:
```
# prepare the command options

$rgid ||= $prefix;
msg("Using BAM RG (Read Group) ID: $rgid");

$bwaopt .= qq{ -v 2 -M -R '\@RG\\tID:$rgid\\tSM:$rgid'};
$bwaopt .= ' -p' if $peil;
```

For reference, I'm on a Mac and running BWA:
```
Program: bwa (alignment via Burrows-Wheeler transformation)
Version: 0.7.16a-r1181
```

**Comment by tseemann** [comment]
Yes BWA was buggy, and Heng Li fixed it, so I had to change Snippy. It's fixed in github.

**Comment by gunns337** [comment]
I implemented using this  ,and work for me: "'\@RG\\tID:sample_1\\tLB:sample_1\\tPL:ILLUMINA\\tPM:HISEQ\\tSM:sample_1\'"
