### ISSUE TITLE
What positions are included in core.nway.tab file?

### ISSUE THREAD

**Issue by thorellk** [tseemann/snippy#116]
Hi!

Maybe trivial question but what loci are included in the nway tab file of the core output?

Thanks,

Kaisa

**Comment by tseemann** [comment]
This is a good question.  The nway file was originally from the Nesoni package we used to use (https://github.com/Victorian-Bioinformatics-Consortium/nesoni) but is no longer maintained.

It contains *all* variant SNP sites, not just "core" ones.

It does not have indels.
