### ISSUE TITLE
vcf-consensus  -- The fasta sequence does not match the REF

### ISSUE THREAD

**Issue by nblouin** [tseemann/snippy#117]
Hi there-
I expect this is a simple question (apologies in advance my Perl is rotten). I am having difficulty figuring out what the issue is with my input files to where I am not passing the sanity check in Snippy. I have pasted in my commands and then  the snps.log.

Any insight would be terrific.
My input consensus assembly does have a small number of gaps (Ns) and ambiguities (e.g., A,R,Y). I have also tried this by replacing the ambiguities with gaps (Ns), but get a similar error at the sanity check.

[nblouin@login001 MolBioLab]$ cat ~/shells/SnippyTestUW1.sh 
#!/bin/bash
#SBATCH -t 24:00:00
#SBATCH --mem=64G
#SBATCH --nodes=1-1
#SBATCH -J SnippyTester
#BATCH -D=/users/nblouin/scratch/MolBioLab

module unload biolite/0.3.3 
module load freebayes/1.1.0
module load snippy/Oct2017 

snippy --cpus 8 \
--reference SL1R_AssemblyMIRA.fasta \
 --outdir SnippyTestUW1 --force \
--pe1 trim_fwd_pair_UW1_S9_R1_001.fq \
--pe2 trim_rev_pair_UW1_S9_R2_001.fq

[nblouin@login001 MolBioLab]$ 
[nblouin@login001 MolBioLab]$ 
[nblouin@login001 MolBioLab]$ cat  SnippyTestUW1/snps.log
### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.04 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 1.24 seconds elapse.
[bwa_index] Update BWT... 0.03 sec
[bwa_index] Pack forward-only FASTA... 0.03 sec
[bwa_index] Construct SA from BWT and Occ... 0.51 sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa index reference/ref.fa
[main] Real time: 5.854 sec; CPU: 1.866 sec

### (bwa mem  -v 2 -M -R '@RG\tID:snps\tSM:snps' -t 8 reference/ref.fa /gpfs/scratch/nblouin/MolBioLab/trim_fwd_pair_UW1_S9_R1_001.fq /gpfs/scratch/nblouin/MolBioLab/trim_rev_pair_UW1_S9_R2_001.fq | samtools view -u -T reference/ref.fa -F 3844 -q 60 | samtools sort --reference reference/ref.fa > snps.bam)

[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (92, 178, 730)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 2006)
[M::mem_pestat] mean and std.dev: (347.00, 420.61)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 2644)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (116, 165, 230)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 458)
[M::mem_pestat] mean and std.dev: (178.36, 83.07)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 572)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (87, 162, 361)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 909)
[M::mem_pestat] mean and std.dev: (222.40, 169.21)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1183)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (105, 165, 544)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1422)
[M::mem_pestat] mean and std.dev: (309.22, 398.59)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1861)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (115, 163, 228)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 454)
[M::mem_pestat] mean and std.dev: (176.99, 82.27)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 567)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (53, 99, 369)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1001)
[M::mem_pestat] mean and std.dev: (161.33, 140.90)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1317)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (106, 180, 375)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 913)
[M::mem_pestat] mean and std.dev: (188.40, 130.41)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1182)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (115, 181, 494)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1252)
[M::mem_pestat] mean and std.dev: (262.00, 216.86)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1631)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (115, 163, 228)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 454)
[M::mem_pestat] mean and std.dev: (176.86, 81.64)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 567)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (136, 218, 409)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 955)
[M::mem_pestat] mean and std.dev: (215.53, 153.07)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1228)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (233, 732, 1757)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 4805)
[M::mem_pestat] mean and std.dev: (854.60, 695.95)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 6329)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (116, 163, 226)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 446)
[M::mem_pestat] mean and std.dev: (176.24, 80.43)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 556)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (104, 111, 258)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 566)
[M::mem_pestat] mean and std.dev: (152.86, 93.67)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 720)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (161, 267, 1405)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 3893)
[M::mem_pestat] mean and std.dev: (583.79, 763.52)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 5137)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (115, 164, 228)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 454)
[M::mem_pestat] mean and std.dev: (177.09, 82.20)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 567)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (92, 145, 213)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 455)
[M::mem_pestat] mean and std.dev: (147.67, 86.55)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 576)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (72, 136, 749)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 2103)
[M::mem_pestat] mean and std.dev: (304.30, 317.90)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 2780)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (114, 162, 225)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 447)
[M::mem_pestat] mean and std.dev: (174.99, 81.02)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 558)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_pestat] skip orientation FF
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (124, 212, 443)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1081)
[M::mem_pestat] mean and std.dev: (228.69, 171.50)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1400)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (115, 162, 225)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 445)
[M::mem_pestat] mean and std.dev: (175.34, 80.12)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 555)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (130, 343, 665)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1735)
[M::mem_pestat] mean and std.dev: (423.70, 320.64)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 2270)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (77, 108, 204)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 458)
[M::mem_pestat] mean and std.dev: (142.72, 87.09)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 585)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (127, 179, 335)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 751)
[M::mem_pestat] mean and std.dev: (198.30, 110.22)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 959)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (115, 161, 224)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 442)
[M::mem_pestat] mean and std.dev: (174.35, 79.46)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 551)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (99, 141, 545)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1437)
[M::mem_pestat] mean and std.dev: (208.20, 178.36)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1883)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (103, 138, 252)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 550)
[M::mem_pestat] mean and std.dev: (168.89, 116.62)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 699)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (111, 157, 217)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 429)
[M::mem_pestat] mean and std.dev: (169.05, 77.13)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 535)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (86, 145, 231)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 521)
[M::mem_pestat] mean and std.dev: (149.28, 102.86)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 666)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (123, 173, 760)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 2034)
[M::mem_pestat] mean and std.dev: (366.62, 436.34)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 2671)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (111, 156, 215)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 423)
[M::mem_pestat] mean and std.dev: (167.95, 75.82)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 527)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (60, 137, 303)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 789)
[M::mem_pestat] mean and std.dev: (155.80, 104.94)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1032)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (97, 108, 193)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 385)
[M::mem_pestat] mean and std.dev: (132.57, 65.28)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 481)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (114, 160, 221)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 435)
[M::mem_pestat] mean and std.dev: (172.70, 77.77)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 542)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (115, 162, 496)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1258)
[M::mem_pestat] mean and std.dev: (227.27, 190.58)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1639)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (169, 230, 522)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1228)
[M::mem_pestat] mean and std.dev: (337.33, 318.48)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1581)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (112, 157, 217)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 427)
[M::mem_pestat] mean and std.dev: (169.21, 77.00)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 532)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (177, 300, 498)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1140)
[M::mem_pestat] mean and std.dev: (225.08, 120.47)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1461)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (113, 181, 1178)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 3308)
[M::mem_pestat] mean and std.dev: (405.57, 708.48)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 4373)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (109, 152, 210)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 412)
[M::mem_pestat] mean and std.dev: (163.95, 73.61)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 513)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (164, 280, 678)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1706)
[M::mem_pestat] mean and std.dev: (388.50, 317.69)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 2220)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (160, 207, 359)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 757)
[M::mem_pestat] mean and std.dev: (233.10, 173.06)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 956)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (113, 158, 218)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 428)
[M::mem_pestat] mean and std.dev: (170.56, 76.04)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 533)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (140, 168, 688)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1784)
[M::mem_pestat] mean and std.dev: (380.82, 424.77)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 2332)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[main] Version: 0.7.12-r1039
[main] CMD: bwa mem -v 2 -M -R @RG\tID:snps\tSM:snps -t 8 reference/ref.fa /gpfs/scratch/nblouin/MolBioLab/trim_fwd_pair_UW1_S9_R1_001.fq /gpfs/scratch/nblouin/MolBioLab/trim_rev_pair_UW1_S9_R2_001.fq
[main] Real time: 511.312 sec; CPU: 445.839 sec
[bam_sort_core] merging from 6 files...

### /gpfs/runtime/opt/snippy/Oct2017/snippy/bin/snippy-vcf_filter --minqual 10 --mincov 10 --minfrac 0.9  snps.raw.vcf > snps.filt.vcf

Parsing: snps.raw.vcf
Types: del=29 complex=490 mnp=22
Passed 541/570 variants (94.91%)

### /gpfs/runtime/opt/snippy/Oct2017/snippy/bin/snippy-vcf_to_tab --gff reference/ref.gff --ref reference/ref.fa --vcf snps.vcf > snps.tab

Loading reference: reference/ref.fa
Loaded 1 sequences.
Loading features: reference/ref.gff
Parsing variants: snps.vcf
Converted 541 SNPs to TAB format.

### vcf-consensus snps.vcf.gz < reference/ref.fa > snps.consensus.fa

The fasta sequence does not match the REF at SL1R_AssemblyMIRA:575315. GYTN(YTNTTAGGG) in .fa, GNTN in .vcf, frz=571510
 at /gpfs/runtime/opt/snippy/Oct2017/snippy/bin/../binaries/noarch/vcf-consensus line 20, <STDIN> line 9590.
	main::error('The fasta sequence does not match the REF at SL1R_AssemblyMIR...') called at /gpfs/runtime/opt/snippy/Oct2017/snippy/bin/../binaries/noarch/vcf-consensus line 262
	main::apply_variant('HASH(0x1bddcb8)', 'ARRAY(0x1f3d4d8)') called at /gpfs/runtime/opt/snippy/Oct2017/snippy/bin/../binaries/noarch/vcf-consensus line 146
	main::do_consensus('HASH(0x1bddcb8)') called at /gpfs/runtime/opt/snippy/Oct2017/snippy/bin/../binaries/noarch/vcf-consensus line 11

**Comment by Cashalow** [comment]
Yes I still get this error too. It's because of the handling of ambiguity codes in the vcf-consensus scripts (comparison between GYTN and GNTN fails because Y != N). I admit that I have removed altogether the sanity check in vcf consensus because somehow the fix did not make it yet. https://github.com/tseemann/snippy/issues/90

**Comment by tseemann** [comment]
Thank you again @Cashalow , your answer is perfect!
