### ISSUE TITLE
trouble  reading reference sequence

### ISSUE THREAD

**Issue by jnricaldi** [tseemann/snippy#120]
Hello,
I get the following message  
"Please supply a reference FASTA/GBK/EMBL file with --reference"
I have tried with various .fasta .gb .gbk sequences but it doesn't seem to work. My files are within other folder, I have also tried the full path. Anything else I can try?
Thanks!

**Comment by tseemann** [comment]
@jnricaldi that error only occurs if you didn't provide the `snippy --reference` parameter.  Being in sub-folder should be fine.  
Are you sure the filename is correct? 
Does it have spaces in it?
Does your command line look like this?
```
snippy --outdir DIR --ref FOLDER/FILE.gbk --R1 R1.fq.gz --R2 read.fq.fz
```

**Comment by jnricaldi** [comment]
Hi!
Our bioinformatician figured it out. It is an error specific to our shared linux environment, due to a old version of freebayes.  We have managed to find a way to fix it.
Thanks!!

**Comment by tseemann** [comment]
Great news! Thanks for replying.
