### ISSUE TITLE
full.aln file

### ISSUE THREAD

**Issue by ryjohnson09** [tseemann/snippy#121]
Hey Torsten,

What tools/programs are used under the hood when creating the full.aln file (tried to figure it out but my perl competency is lackluster). I'm also trying to figure out if it is compatible as input into gubbins.

Thanks,
Ryan

**Comment by tseemann** [comment]
It thoguht it was compatible with Gubbins.

If not, just replace all the gaps `-` with `N` (or the other way around) and you should be fine.
