### ISSUE TITLE
VCF filtering: Pruning / thinnig

### ISSUE THREAD

**Issue by crarlus** [tseemann/snippy#122]
Hi Thorsten,
could you enhance snippy by allowing pruning the combined VCF files?
For genomes with frequent recombinations, it makes sense to consider SNPs only once and remove SNPs that are close. This is called pruning in CGE's [CSIPhylogeny](https://cge.cbs.dtu.dk/services/CSIPhylogeny/), thinning within [vcftools](http://vcftools.sourceforge.net/man_latest.html) and intersnp distance in bionumerics.

> vcftools
Thin sites so that no two sites are within the specified distance from one another.

I would do the pruning after calling the core snps and then compute the alignment fasta

This is what I did:
```
# 1. Call core snps
snippy-core --noref --prefix core_noref */

# 2. thin neigbouting SNPs
vcftools --vcf core_noref.vcf --out thinned --thin 100 --recode

# 3. Convert to tab format
vcf-to-tab < thinned.recode.vcf > thinned.tab

# 4. convert to alignment (from https://code.google.com/archive/p/vcf-tab-to-fasta/)
perl vcf_tab_to_fasta_alignment.pl -i thinned.tab > thinned.aln

# 5. compute distance matrix
snp-dists $analyis_dir/thinned.aln > $analyis_dir/snp_thinned_matrix.tsv
```

Of course it would be charming if snippy could do this with one call.

**Comment by tseemann** [comment]
Pruning is a somewhat crude method for removing potential recombination events.

We tend to use the `core.full.aln` and provide it to `ClonalFrameML` or `gubbins` or `BratNextGen` or `FastGear` to remove recombination in a more model-based manner. But it is much slower.

I agree having your feature would be nifty, but I am going to rewrite snippy soon, as it has many limitations in its current. form, sorry.
