### ISSUE TITLE
Potentially missed SNP

### ISSUE THREAD

**Issue by conmeehan** [tseemann/snippy#125]
Hi Torsten,

I am comparing the output of snippy to a GATK-based pipeline and have come across something weird. There is one SNP that was found by the GATK approach but not found in the snippy pipeline we use here. However, when I view the snippy bam file with IGV, I do see the snp. Am I missing something or is snippy missing that snp for some reason?
The dropbox link below gives you all the output from snippy. The position in question is 2439519. Let me know if I am missing something here please.
https://www.dropbox.com/sh/qy9dityjtrpzf2u/AAD8SQ-zyRP1o7ciOh9I76a0a?dl=0

Thanks,
Conor

**Comment by Cashalow** [comment]
That's because of the thresholds snippy uses for calling snps. Snippy requires per default a coverage of 10 for considering a snp, your position has a coverage of 9 with 7 A's therefore the snp is not called.

**Comment by tseemann** [comment]
Thank you @Cashalow for answering @conmeehan .

7 / 9 is one of those borderline cases where it is probably dodgy, but might not be...  I would make sure there is good normal looking alignments across there.
