### ISSUE TITLE
Snippy on Galaxy

### ISSUE THREAD

**Issue by korinalb** [tseemann/snippy#127]
Hi everyone,

I'm using snippy on galaxy and I'm getting the error below. I'm very new to this program (and bioinfo in general...), but does anyone know what I could do to solve this problem? Because I am using the program through galaxy I don't think I can update BioPerl.

Best,
Korin

Fatal error: Exit code 2 ()
Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/korinalbert/galaxy/database/dependencies/snippy/3.0/simon-gladman/package_snippy_3_0/c8d7d39f0781/bin/snippy line 11.
BEGIN failed--compilation aborted at /Users/korinalbert/galaxy/database/dependencies/snippy/3.0/simon-gladman/package_snippy_3_0/c8d7d39f0781/bin/snippy line 11.

**Comment by tseemann** [comment]
It looks like you haven't installed the `Bio::Perl` perl module into your Galaxy system.
It looks like you are running your own Galaxy on your Apple MacOS computer. 
I am unable to help with Galaxy issues, sorry.
You'll need to contact the author of the Snippy wrapper @slugger70
