### ISSUE TITLE
What are the Ns in the alignment

### ISSUE THREAD

**Issue by suzumar** [tseemann/snippy#128]
Hello Thorsten.  
Could you please explain me what the N represent in the fasta alignments when we align raw fastq reads?
Thanks
Marcelino

**Comment by tseemann** [comment]
See https://github.com/tseemann/snippy#output-files

![image](https://user-images.githubusercontent.com/453972/37014723-abcf80b6-2156-11e8-90a1-9ea0aad1fc1b.png)
