### ISSUE TITLE
start from precomputed .vcf files

### ISSUE THREAD

**Issue by thkuo** [tseemann/snippy#129]
The variant calling in our project was done previously. Is it possible to have snippy start from our vcf files and create the data required by the core SNPs phylogeny?

**Comment by tseemann** [comment]
Unfortunately not easily.  `snippy-core` uses the `snps.tab` and `snps.aligned.fa` files, not the `snps.vcf` files.  My method speeds up generating the core by 100x as I can re-use some precomputet data.

I still can't seem to locate a `vcf2coresnps` style script to recommend to you.

Sorry I can not be more help!

**Comment by thkuo** [comment]
Thanks for the response
