### ISSUE TITLE
version check fails for java based programs under certain conditions

### ISSUE THREAD

**Issue by bgruening** [tseemann/snippy#131]
Hi @tseemann!

Our snpeff version check return the following as we have a env var set to control the JRE:

```
$ snpEff -version 
Picked up _JAVA_OPTIONS: -Xmx4G -Xms1G
4.3
```

`Picked up _JAVA_OPTIONS: -Xmx4G -Xms1G` is a message printed to stderr, so if you filter out stderr from https://github.com/tseemann/snippy/blob/master/bin/snippy#L80 this would solve it.

```
$ snpEff -version 2> /dev/null
4.3
```

**Comment by tseemann** [comment]
@bgruening / Björn

This bug shouldn't be happening, as I join all the lines from the `-version` output and join them, then look for a `(\d+\.\d+)` pattern.

If I change my command inside snippy to `_JAVA_OPTIONS= snpEff -version` I get this:

```
[13:33:57] Checking version: _JAVA_OPTIONS= snpEff -version is >= 4.3 - ok, have 4.3
[13:33:57] Using reference: /home/tseemann/git/snippy/test/example.fna
```

**Comment by bgruening** [comment]
@tseemann ok, thats strange! Thanks for the commit and the new release!
