### ISSUE TITLE
Call SNPs with pre-aligned BAM files:

### ISSUE THREAD

**Issue by EisenRa** [tseemann/snippy#132]
Hi Torsten,

Thank you for making this tool -- works great!

Just a question, is it possible to run the pipeline on BAM files? (_i.e._ I would like to call SNPs with different mincov/minfrac thresholds, but don't want to re-map with BWA).

Cheers,
Raphael

**Comment by tseemann** [comment]
Unfortunately the current design of Snippy doesn't make this easy.    What you really want is to run Snippy once with `--minfrac 0.05` and `--mincov 2` (say) and then filter the `snps.raw.vcf` with one of the many available VCF filtering tools.

ie. you don't need to recall all the SNPs from the BAM, just produce a very liberal VCF and filter that.
