### ISSUE TITLE
output from multiple Snippy runs to find all sites where snp present in >=1 isolate

### ISSUE THREAD

**Issue by lydeejeanne** [tseemann/snippy#135]
Hi there. I'm relatively new to this, but I was wondering if there was an easy way to run snippy on multiple samples compared to a single reference and then pool that output to generate a fasta file for each sample where only those sites that have snps in at least one isolate (of the many put through snippy) are included. I've written R code to do this myself, but I'm worried I'm missing something in the Snippy output--plus there are so many warnings online not to do this. 

I don't want snippy-core to the best of my knowledge because that only includes those snps that are common to all samples I'm investigating. It is similar to what I want to do though, but instead I want to include all sites that are variant in at least one sample of the many I'm evaluating. 

I apologize if this doesn't make sense, I'm not down with the lingo yet. Thanks for any effort that can be given to push me in the right direction.

**Comment by tseemann** [comment]
`snippy-core` outputs `core.aln` (present in all only) and `core.full.aln`  (a column for every base in the reference).  You can just process `core.full.aln` with `disty` to achieve your goal I think.

**Comment by lydeejeanne** [comment]
I'll try that. Thanks for answering so quickly--I really appreciate it.
