### ISSUE TITLE
I got "No variants found" message and empty .bed file

### ISSUE THREAD

**Issue by gokigensz** [tseemann/snippy#138]
Hello,
I'm using snippy 3.2-dev on Macintosh OSX El Captan 10.11.6.
When I tried test data that came with snippy-master, everything was all right. But when I tried my own fastq files, it seemed to finished all right but the resulted .bed file was empty. I checked again and found the following messages displayed during the run.
Creating extra output files: BED GFF CSV TXT HTML
Identified 0 variants. 

In the .log file, there was a warning "All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate", which I cannot understand what this means. My input file is a fasta file of a complete genome about 1.6Mb.

I'd really appreciate it if you give me a suggestion.

.log-----------------------------------------------------------------------------------------------
### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.01 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.42 seconds elapse.
[bwa_index] Update BWT... 0.01 sec
[bwa_index] Pack forward-only FASTA... 0.01 sec
[bwa_index] Construct SA from BWT and Occ... 0.13 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index reference/ref.fa
[main] Real time: 0.610 sec; CPU: 0.592 sec

### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

WARNING: All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate.

### (bwa mem  -v 2 -M -R '@RG\tID:snps\tSM:snps' -t 8 reference/ref.fa /Users/rusuzuki/Desktop/Snippy/Nepal-1_S28_L001_R1_001.fastq.gz /Users/rusuzuki/Desktop/Snippy/Nepal-1_S28_L001_R2_001.fastq.gz | samtools view -u -T reference/ref.fa -F 3844 -q 60 | samtools sort --reference reference/ref.fa > snps.bam)

[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (23, 23, 24)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (21, 26)
[M::mem_pestat] mean and std.dev: (23.24, 0.43)
[M::mem_pestat] low and high boundaries for proper pairs: (20, 27)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] skip orientation FR as there are not enough pairs
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -v 2 -M -R @RG\tID:snps\tSM:snps -t 8 reference/ref.fa /Users/rusuzuki/Desktop/Snippy/Nepal-1_S28_L001_R1_001.fastq.gz /Users/rusuzuki/Desktop/Snippy/Nepal-1_S28_L001_R2_001.fastq.gz
[main] Real time: 16.481 sec; CPU: 105.285 sec

### /Users/rusuzuki/snippy/bin/snippy-vcf_filter --minqual 10 --mincov 10 --minfrac 0.9  snps.raw.vcf > snps.filt.vcf

Parsing: snps.raw.vcf
No variants found.

### /Users/rusuzuki/snippy/bin/snippy-vcf_to_tab --gff reference/ref.gff --ref reference/ref.fa --vcf snps.vcf > snps.tab
Loading reference: reference/ref.fa
Loaded 1 sequences.
Loading features: reference/ref.gff
Parsing variants: snps.vcf
Converted 0 SNPs to TAB format.
### /Users/rusuzuki/snippy/bin/snippy-vcf_filter --subs snps.filt.vcf > snps.filt.subs.vcf
Parsing: snps.filt.vcf
No variants found.

**Comment by tseemann** [comment]
There seems to be something wrong with your Illumina paired-end library.

```
[M::mem_pestat] (25, 50, 75) percentile: (23, 23, 24)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (21, 26)
[M::mem_pestat] mean and std.dev: (23.24, 0.43)
```

BWA is suggesting your read pairs are completely overlapping and only 24bp of actual useable sequence?

I think you need to perform some QC first.

What does `samtools flagstat snps.bam` say?
