### ISSUE TITLE
About snp-core 

### ISSUE THREAD

**Issue by uzmanadeem** [tseemann/snippy#139]
Hi there I am working in 180 GBS isolates of different serotypes (Ia-IX) can i use different reference for each isolates (per closest match to serotype it belongs to) in snippy to find snp variant and then I wish to have aligned core snp file using snippy-core.
Kindly help me with the easiest way to do it.
Thanks

**Comment by tseemann** [comment]
No. 
`snippy-core` requires all isolates use the same reference, otherwise they will not "line up" properly.

You can however, run multiple *separate* analyses for each serotype.
