### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by yzhzu** [tseemann/snippy#141]
hello, everyone,  can you help me to deal with the error, when I perform snippy to investigate SNP between two genome, but the error still occurs. I don't know how to do?
thank you very much.

the snps.log as following:

### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.04 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 2.02 seconds elapse.
[bwa_index] Update BWT... 0.06 sec
[bwa_index] Pack forward-only FASTA... 0.02 sec
[bwa_index] Construct SA from BWT and Occ... 0.63 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index reference/ref.fa
[main] Real time: 3.316 sec; CPU: 2.760 sec

### (bwa mem  -v 2 -M -R '@RG	ID:snps	SM:snps' -t 8 reference/ref.fa fake_reads.fq | samtools view -@ 8 -F 3844 -q 60 -S -b -u -T reference/ref.fa - | samtools sort -O bam -o snps.bam -@ 8 -)

[E::bwa_set_rg] the read group line contained literal <tab> characters -- replace with escaped tabs: \t
sort: invalid option -- 'O'
open: No such file or directory
[bam_sort_core] fail to open file bam
[sam_header_read2] 41 sequences loaded.
[sam_read1] reference '' is recognized as '*'.
[main_samview] truncated file.

### samtools index snps.bam

open: No such file or directory
[bam_index_build2] fail to open the BAM file.

### fasta_generate_regions.py reference/ref.fa.fai 203073 > reference/ref.txt

  File "miniconda3/bin/fasta_generate_regions.py", line 7
    print "usage: ", sys.argv[0], " <fasta file or index file> <region size>"
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "usage: ", sys.argv[0], " <fasta file or index file> <region size>")?

**Comment by tseemann** [comment]
Your version of `samtools` and `bwa` is out of date.

It looks like you are using Miniconda to install things?

**Comment by yzhzu** [comment]
Dear doctor tseemann, thank you very much for your reply. I really use miniconda and will try to upgrade samtools and bwa to run again. if ok, I will immediately share the good news. thank you again.
         yzhzhu

**Comment by yzhzu** [comment]
Dear tseemann, hello, I carefully checked the install requiremnt (bwa mem >= 0.7.12 and  samtools >= 1.3). my bwa and samtools should be satisfy  the criteria. why did the error occur? thank you very much!
                                                                                                                                             yzhzhu

**Comment by yzhzu** [comment]
in current bioconda, the snippy version is 3.1

**Comment by yzhzu** [comment]
I used the original command is snippy --ref --R1 --R2

**Comment by tseemann** [comment]
I can see `bwa mem -v 2 -M -R '@rg	ID:snps	SM:snps' -t 8 reference/ref.fa fake_reads.fq` in the error above.

That means you used `snippy --ref --ctgs` and did not use `--R1 --R2`

@yzhzu i also see now you are using `miniconda`.

Reinstall it with `conda install -c bioconda -c conda-forge snippy`  ?

**Comment by jonahcullen** [comment]
Hello Dr. Seemann, I am also getting the same error. Both samtools and bwa are up-to-date and I reinstalled snippy using anaconda yet the error persists.

snippy \
  --cpus 4 \
  --outdir mysnps \
  --ref ../../reference_genome/NewMap10.fasta \
  --R1 ../trim_clean_data/110B_S7_L001_R1_001.paired.fastq \
  --R2 ../trim_clean_data/110B_S7_L001_R2_001.paired.fastq

### samtools faidx reference/ref.fa


### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.05 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 2.22 seconds elapse.
[bwa_index] Update BWT... 0.04 sec
[bwa_index] Pack forward-only FASTA... 0.03 sec
[bwa_index] Construct SA from BWT and Occ... 0.70 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index reference/ref.fa
[main] Real time: 3.462 sec; CPU: 3.051 sec

### mkdir reference/genomes && cp -f reference/ref.fa reference/genomes/ref.fa


### mkdir reference/ref && bgzip -c reference/ref.gff > reference/ref/genes.gff.gz


### (bwa mem  -v 2 -M -R '@RG	ID:snps	SM:snps' -t 4 reference/ref.fa /Users/jonahcullen/Desktop/UMN_coursework/CMB8571/Final_project/analyses/snippy_variant_calls/../trim_clean_data/110B_S7_L001_R1_001.paired.fastq /Users/jonahcullen/Desktop/UMN_coursework/CMB8571/Final_project/analyses/snippy_variant_calls/../trim_clean_data/110B_S7_L001_R2_001.paired.fastq | samtools view -@ 4 -F 3844 -q 60 -S -b -u -T reference/ref.fa - | samtools sort -O bam -o snps.bam -@ 4 -)

[E::bwa_set_rg] the read group line contained literal <tab> characters -- replace with escaped tabs: \t

### samtools index snps.bam


### samtools depth -q 20 snps.bam | bgzip > snps.depth.gz


### tabix -s 1 -b 2 -e 2 snps.depth.gz


**### fasta_generate_regions.py reference/ref.fa.fai 307071 > reference/ref.txt

  File "/Applications/anaconda3/bin/fasta_generate_regions.py", line 7
    print "usage: ", sys.argv[0], " <fasta file or index file> <region size>"
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "usage: ", sys.argv[0], " <fasta file or index file> <region size>")?**
