### ISSUE TITLE
Is the core SNP codon aligned?

### ISSUE THREAD

**Issue by ojonuba** [tseemann/snippy#143]
I was wondering if the output of the core SNP alignment is aligned by codon? If not, could such a tool be added?

**Comment by tseemann** [comment]
`snp.core.aln` core SNP alignment **only** has SNPs,  so it can't be codon aligned.

`snps.core.full.aln` is just the reference genome with SNPs patched in, so it can't be codon aligned.

It could be possible to generate what you want from all the data in Snippy if you have a reference annotated with CDS.

One way you could do it is create a BED file of the CDS regions in the reference, then use `bedtools getfasta` to extract them from each of the entries in `snps.core.full.aln`, and concatenate the CDS, then combine into a single alignment file again. 

Are you able to do that part?

**Comment by ojonuba** [comment]
Thanks Dr. Tseemann. I had the same thoughts on aligning SNPs but was surprised to see some publications saying they codon-aligned their SNPs.
Thanks for the clarification.
