### ISSUE TITLE
snippy in conda

### ISSUE THREAD

**Issue by thierryjanssens** [tseemann/snippy#150]
Hello,

I am trying to run snippy in conda (version 3.2 it is).

By:

snippy --outdir ./results --ref ./data/ref/ref.gbk --ctgs ./data/contigs/contigs.fasta --prefix first_test --report --force --unmapped

In the verbous stdout I already get the following warnings:
use of uninitialized value in uc at /data/anaconda3/envs/env/bin/snippy line 159, <GEN0> line 16934272.

The analysis ends by returning the following error in the log file:

##############
### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

java.lang.RuntimeException: Error reading file '/data/results/reference/./ref/genes.gff'
java.lang.RuntimeException: FATAL ERROR: Offending line (lineNum: 6998): 'NC_016038     snippy  5'UTR   1       31      .       +       0
       '. File '/data/results/reference/./ref/genes.gff' line 6998
        'NC_016038      snippy  5'UTR   1       31      .       +       0       '

        at org.snpeff.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:353)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.createSnpEffPredictor(SnpEffCmdBuild.java:116)
        at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:345)
        at org.snpeff.SnpEff.run(SnpEff.java:1009)
        at org.snpeff.SnpEff.main(SnpEff.java:155)

###########
Therefore, I am not sure if the warning and the error are related. It looks like the path to the gff reference is malformed.
I could not find a solution to install the latest version under conda.

Regards,

Thierry

**Comment by druvus** [comment]
@thierryjanssens the latest release of snippy is now available in bioconda.

**Comment by thierryjanssens** [comment]
@druvus 

Thank yoou for your swift reply.
It seems a dependency is not included.

[22:58:10] Can not find required 'vcffirstheader' in PATH

Regards,

**Comment by tseemann** [comment]
Version 3.2 is the latest.
4.0-dev is a pre release, and has bugs.

You have found a genuine bug I think. I'm not handling the relative path properly I think. I'm on vacation but will endeavour to fix soon. It affects all versions of snippy.

I'll talk to @slugger70 about the vcflib missing dependencies.

**Comment by thierryjanssens** [comment]
@tseemann 
I have included the conda-forge channel.
$ conda install -c conda-forge snippy

this is the installed version.
snippy                    4.0_dev              pl5.22.0_0    bioconda

When running the following command

$ snippy --outdir ./results \
        --ref ./data/ref.gbk \
        --ctgs ./data/contigs.fasta  \
        --prefix first_test --report --force --unmapped

the last line of the verbous output points to a missing dependency:

[09:59:53] Can not find required 'vcffirstheader' in PATH

kind regards,

**Comment by Slugger70** [comment]
Hi Thierry,

To install snippy with conda you need to specify both bioconda and conda-forge.

The command line you need is: `conda install -c bioconda -c conda-forge snippy`

If you intend to install other packages from bioconda I would suggest that you add both of these channels to your conda config. This can be done as follows:

```
conda config --add channels r
conda config --add channels conda-forge
conda config --add channels bioconda
```
Then you may add packages from bioconda with a simple install command such as `conda install snippy`

Cheers,

Simon.

**Comment by tseemann** [comment]
@thierryjanssens snippy 4.0-dev was a pre-release, it was not meant to be deployed in production.  it has bugs.  @druvus was just very keen :-)   Try using `conda install -c ....... snippy==3.2` to get the stable version.

This is a conda bug, not a snippy bug, so i'm closing it. Please add an issue to bioconda github if you have more problems.

**Comment by druvus** [comment]
@thierryjanssens @tseemann the dev release of snippy is now removed from Bioconda so version 3,2 will be installed by default.
