### ISSUE TITLE
Failed run - ?syntax issue

### ISSUE THREAD

**Issue by lflisboa** [tseemann/snippy#153]
New user here, having recurrent issues right after:

[11:46:13] Running: fasta_generate_regions.py reference/ref.fa.fai 147471 > reference/ref.txt 2>> snps.log
[11:46:13] Error running command, check /path/to/snps.log

Getting following .log:

[snps.log](https://github.com/tseemann/snippy/files/1948727/snps.log)

Tried .gbff, .fasta as reference,  both ultimately failing.   

Appreciate your help!

**Comment by tseemann** [comment]
It says it can't run `fasta_generate_regions.py` 
This is part of most `freebayes` packages (but not all).
Do you have it?

**Comment by lflisboa** [comment]
Thanks for your quick reply - I do have freebayes v1.0.2-dirty

**Comment by tseemann** [comment]
Do you have `snps.log` file for the failed run?

if you type `fasta_generate_regions.py` what happens?

**Comment by lflisboa** [comment]
Problem solved it seems - @mcroxen figured it out - phyton3 was probably being called instead of phyton2.7, so creating an environment for snippy did the trick, but just for --ref .fasta, otherwise having same issue as #154 with snpeff
