### ISSUE TITLE
BWA index issue 

### ISSUE THREAD

**Issue by s18692001** [tseemann/snippy#155]
Hi there,

When I use bwa index -a bwtsw  abc.fa, it shows:
`[bwa_index] Pack FASTA... [bns_fasta2bntseq] Failed to allocate 0 bytes at bntseq.c line 303: Success`
Any suggestion?

My abc.fa is a combined .fa file from both human hg19 and mouse mm10 genome. 

Simon

**Comment by tseemann** [comment]
Have you filed this issue to the correct project?

Snippy is software for finding SNPs in bacterial genomes.
It runs `bwa index` for you.
