### ISSUE TITLE
Freebayes call by snippy

### ISSUE THREAD

**Issue by cizydorczyk** [tseemann/snippy#158]
Hello,

I had a couple of questions regarding the call to freebayes snippy makes.

When looking at the call to freebayes in a recent run of snippy, freebayes was called as follows:

`### freebayes-parallel reference/ref.txt 8 -p 2 -P 0.5 -q 13 -m 60 --min-repeat-entropy 1.0 -f reference/ref.fa snps.bam > snps.raw.vcf`

From my understanding, the -p parameter of freebayes sets the ploidy; why would ploidy be set to 2, if snippy is working with a haploid genome (Pseudomonas aeruginosa in my case)?

Further, does use of the --min-cov or --minfrac change prevent the use of --min-repeat-entropy parameter? And how does the use of these parameters affect the -P 0.05 option of freebayes (required probability of a polymorphism)?

Any response is greatly appreciated.

Thank you,
Conrad Izydorczyk

**Comment by tseemann** [comment]
SNippy 3.x used to use ploidy 1 , but this has a bad effect of turning MISMAPPED reads into false SNPs becuase we are *forcing* a haploid mode. I now use diploid mode, and ignore all  heterozygous SNPs.
