### ISSUE TITLE
Linuxbrew link is broken in readme

### ISSUE THREAD

**Issue by davised** [tseemann/snippy#159]
Hi,

I noticed a small bug here in the README.md file.

https://github.com/tseemann/snippy/blob/82baf13f8739e7102c4a9359f018a616837a0162/README.md#L57

the correct link for linuxbrew would be 

`[LinuxBrew](http://linuxbrew.sh/)`

I'm interested to try this software, and I've already used prokka a ton. Thanks for your hard work generating these pieces of software to make my life easier.

**Comment by tseemann** [comment]
Thanks @davised for the bug fix and the feedback on my tools!
