### ISSUE TITLE
stringency of calling and filteration

### ISSUE THREAD

**Issue by a1204350** [tseemann/snippy#160]
Hi Torsten,

First thanks for this great tool and then I've got a few questions need your help.

I used to call snp through the bowtie2+freebayes pipeline, and recently changed to snippy, so I'm kind of comparing the results generated from both to see if they are consistent.

I noticed that snippy sets the minimum mapping quality to 60 when running freebayes and wondering if there is a reason for this. Would it be too stringent? 

If I use the latest bowtie2 for the mapping, which value should I use then, let's say if I want to obtain the nearly same result? I used 30 (minimum mapping quality) in the bowtie2+freebayes before, which I thought was stringent enough, so it turns out maybe not actually true?

Regarding downstream variants filteration, how the default values used in snippy compare with the traditional strategies, such as filtering by quality, alternative fraction, reads count, etc..If you could explain a little bit on how and why you choose those as defaults. 

Thanks

Yu

**Comment by tseemann** [comment]
Yu,

BWA MEM specifically uses MAPQ=60 for *uniquely* mapped. 
I think bowtie2 might use MAPQ=42 for that instead!

You may want to try Snippy 4.0-dev2  which we are using here in production. It allows you to provide a `--bam` so you can use bowtie2 instead. You can also use `--mapqual` and `--basequal` to change it to whatever you want.

Snippy4 has less false positives, and more true positives.

**Comment by a1204350** [comment]
Got it. thanks

**Comment by drish91** [comment]
On the same lines, maybe I'm missing this in the documentation, but is there a way to use previously mapped-sam files from another pipeline (like samtools/bbmap) as input and then use snippy for variant filtering, consensus and downstream alignment?

The reason I ask is because I used bbmap for calling variants and bcftools for downstream filtering, but the results are much more comprehensive than when I re-did the analysis using snippy for the same purpose. There are a lot of vcfs in the bbmap results that don't show up in the snippy results, and I was wondering if that was because of the stringency of parameters. So, I thought it would be great if I could use the SNPs previously detected and do the downstream parsing and core phylogenetic analysis with snippy?

Thanks,
Drishti

**Comment by tseemann** [comment]
@drish91 does the `--bam` option do what you want?  it probably works with SAM too i think.

**Comment by drish91** [comment]
Hi @tseemann 
I re-ran the pipeline on a subset of the data with `--bam` option for the SAM files, and while it got through most of the steps, it failed at running snp-sites.
Below is a snippet of the error:

> Running: snp-sites -c -o core.aln core.full.aln
> Warning: No SNPs were detected so there is nothing to output.
> ERROR: Could not run: snp-sites -c -o core.aln core.full.aln

All the core* output files created seem empty, except for core.ref.fa which is just the reference fasta.

Any suggestions?

**Comment by tseemann** [comment]
Sounds like you have no core SNPs then.
This usually means your inputs are too diverse.
And that usually means one or more of your samples is bad.
What does `wc -l */snps.tab` say?

**Comment by drish91** [comment]
Huh. 
that's strange bc the samples are supposed to be randomly picked clones. When I try running the same analysis from scratch, with raw reads as suggested in the readme, it works fine, resulting in ~2500 SNPs across all three genomes.

analysis using SAM files:
```
$ wc -l */snps.tab
  1 A3_CANDIDA-PE-P25-1_S11/snps.tab
  1 A4_CANDIDA-PE-P37-1_S12/snps.tab
  1 A5_CANDIDA-PE-P49-1_S13/snps.tab
  3 total
```

analysis using raw reads:
```
$ wc -l */snps.tab
  3116 A3_CANDIDA-PE-P25-1_S11/snps.tab
  2414 A4_CANDIDA-PE-P37-1_S12/snps.tab
  2774 A5_CANDIDA-PE-P49-1_S13/snps.tab
  8304 total
```

**Comment by tseemann** [comment]
Candida fungi.yeast --- it produces lots of heterozygous SNPs in my experience. i think its hard to get clonal DNA from it. or it was in a diploid growth phase. this would make assembly bad. and cause problems with using it for --ctgs
