### ISSUE TITLE
empty results

### ISSUE THREAD

**Issue by mdtorohernando** [tseemann/snippy#164]
Hi, I'm trying to run snippy v4.0-dev and v4.0-dev2 and I find output files (also test files from snippy directory) are empty. I attach the logfile. Perhaps is due that I'm using a virtual machine with Ubuntu 14?
Thanks, 
María
[snps.log](https://github.com/tseemann/snippy/files/2020273/snps.log)

**Comment by tseemann** [comment]
```
### bwa mem  -Y -M -R '@RG\tID:snps\tSM:snps' -t 8 reference/ref.fa /home/osboxes/sw/snippy/test/reads_R1.fastq.gz /home/osboxes/sw/snippy/test/reads_R2.fastq.gz | samclip --ref reference/ref.fa.fai | samtools sort -n -l 0 -T /tmp/snippy.14169. --threads 8 -m 1000M | samtools fixmate -m - - | samtools sort -l 0 -T /tmp/snippy.14169. --threads 8 -m 1000M | samtools markdup -T /tmp/snippy.14169. -r -s - - > snps.bam

READ 0 WRITTEN 0 
EXCLUDED 0 EXAMINED 0
PAIRED 0 SINGLE 0
DULPICATE PAIR 0 DUPLICATE SINGLE 0
DUPLICATE TOTAL 0
```

It seems no reads are aligning, or making it to the end?

Your bwa looks old: `Version: 0.7.5a-r405`
How old is your samtools?

**Comment by mdtorohernando** [comment]
Hi Torsten, thanks for your quick response. I have uninstalled bwa and samtools, that were installed from synaptic by default (sorry, I didn't realized) and were old and now Snippy works with bwa and samtools that are in its bin folder. 

When I run snippy --check all is OK (file attached)
[snippy_check.txt](https://github.com/tseemann/snippy/files/2022270/snippy_check.txt)

But, when I run snippy over raw reads or contigs (in this case contigs) I obtain a message "samtools sort: couldn't allocate memory for bam_mem"and all the files are empty. I suspect this is due to the low memory of the virtual machine. I attached to you the log file. 
[prueba_error.txt](https://github.com/tseemann/snippy/files/2022281/prueba_error.txt)

On the other hand, by checking the snps.log file I obtain a error in Freebayes execution (Failed to set region:...). 
[snps.log](https://github.com/tseemann/snippy/files/2022286/snps.log)

Thanks in advance for your help!

María

**Comment by tseemann** [comment]
How much RAM do you have?

Snippy is trying to use 8 GB of RAM,  (1 GB per thread). Try using less --threads

**Comment by mdtorohernando** [comment]
Thanks! First I tried to increase the VBx RAM, but it has no good result. Then, I followed your suggestion and use --cpus 1 and it works properly! thanks. It is a VBox for students to practice in their own computers... 
Thank you very much!

**Comment by tseemann** [comment]
Glad it helped.
