### ISSUE TITLE
ERROR(freebayes)

### ISSUE THREAD

**Issue by SGarciaCobos** [tseemann/snippy#176]
Hi, I get the following error (see below) regarding freebayes when using a gb file as reference.
In addition, when I try a .fasta file as reference I also get an error: " invalid reference"
Any insights what could be the problem? thanks!

### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.18 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=58769916, availableWord=16134824
[BWTIncConstructFromPacked] 10 iterations done. 26614380 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 49166028 characters processed.
[bwa_index] 10.72 seconds elapse.
[bwa_index] Update BWT... 0.13 sec
[bwa_index] Pack forward-only FASTA... 0.11 sec
[bwa_index] Construct SA from BWT and Occ... 6.07 sec
[main] Version: 0.7.5a-r405
[main] CMD: bwa index reference/ref.fa
[main] Real time: 17.429 sec; CPU: 17.224 sec

### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

WARNING: All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate.

### bwa mem  -Y -M -R '@RG\tID:mysnps_Af293vsP1MR\tSM:mysnps_Af293vsP1MR' -t 16 reference/ref.fa /home/cobos/PROJECTS/A_fumigatus/Clinical_samples_trimmed_fastQ/P1MR_trimmed_R1.fastq /home/cobos/PROJECTS/A_fumigatus/Clinical_samples_trimmed_fastQ/P1MR_trimmed_R2.fastq | samclip --max 10 --ref reference/ref.fa.fai | samtools sort -n -l 0 -T /tmp/snippy.21174. --threads 8 -m 1000M | samtools fixmate -m - - | samtools sort -l 0 -T /tmp/snippy.21174. --threads 8 -m 1000M | samtools markdup -T /tmp/snippy.21174. -r -s - - > snps.bam

READ 0 WRITTEN 0 
EXCLUDED 0 EXAMINED 0
PAIRED 0 SINGLE 0
DULPICATE PAIR 0 DUPLICATE SINGLE 0
DUPLICATE TOTAL 0

### freebayes-parallel reference/ref.txt 16 -p 2 -P 0.5 -q 13 -m 60 --no-partial-observations --haplotype-length 0 --min-repeat-entropy 1.0 -f reference/ref.fa snps.bam > snps.raw.vcf

Error: Failed to set region: -1:0-963,722(*)
ERROR(freebayes): Could not SetRegion to NC_007194:0..963722
Error: Failed to set region: -1:963,722-1,927,444(*)
ERROR(freebayes): Could not SetRegion to NC_007194:963722..1927444
Error: Failed to set region: -1:1,927,444-2,891,166(*)
ERROR(freebayes): Could not SetRegion to NC_007194:1927444..2891166
Error: Failed to set region: -1:2,891,166-3,854,888(*)
ERROR(freebayes): Could not SetRegion to NC_007194:2891166..3854888
Error: Failed to set region: -1:3,854,888-4,818,610(*)
ERROR(freebayes): Could not SetRegion to NC_007194:3854888..4818610
Error: Failed to set region: -1:4,818,610-4,918,979(*)
ERROR(freebayes): Could not SetRegion to NC_007194:4818610..4918979
Error: Failed to set region: -1:0-963,722(*)
ERROR(freebayes): Could not SetRegion to NC_007195:0..963722
Error: Failed to set region: -1:963,722-1,927,444(*)
ERROR(freebayes): Could not SetRegion to NC_007195:963722..1927444
Error: Failed to set region: -1:1,927,444-2,891,166(*)
ERROR(freebayes): Could not SetRegion to NC_007195:1927444..2891166
Error: Failed to set region: -1:2,891,166-3,854,888(*)
ERROR(freebayes): Could not SetRegion to NC_007195:2891166..3854888
Error: Failed to set region: -1:3,854,888-4,818,610(*)
ERROR(freebayes): Could not SetRegion to NC_007195:3854888..4818610
Error: Failed to set region: -1:4,818,610-4,844,472(*)
ERROR(freebayes): Could not SetRegion to NC_007195:4818610..4844472
Error: Failed to set region: -1:0-963,722(*)
ERROR(freebayes): Could not SetRegion to NC_007196:0..963722
Error: Failed to set region: -1:963,722-1,927,444(*)
ERROR(freebayes): Could not SetRegion to NC_007196:963722..1927444
Error: Failed to set region: -1:1,927,444-2,891,166(*)
ERROR(freebayes): Could not SetRegion to NC_007196:1927444..2891166
Error: Failed to set region: -1:2,891,166-3,854,888(*)
ERROR(freebayes): Could not SetRegion to NC_007196:2891166..3854888
Error: Failed to set region: -1:3,854,888-4,079,167(*)
ERROR(freebayes): Could not SetRegion to NC_007196:3854888..4079167
Error: Failed to set region: -1:0-963,722(*)
ERROR(freebayes): Could not SetRegion to NC_007197:0..963722
Error: Failed to set region: -1:963,722-1,927,444(*)
ERROR(freebayes): Could not SetRegion to NC_007197:963722..1927444
Error: Failed to set region: -1:1,927,444-2,891,166(*)
ERROR(freebayes): Could not SetRegion to NC_007197:1927444..2891166
Error: Failed to set region: -1:2,891,166-3,854,888(*)
ERROR(freebayes): Could not SetRegion to NC_007197:2891166..3854888
Error: Failed to set region: -1:3,854,888-3,923,705(*)
ERROR(freebayes): Could not SetRegion to NC_007197:3854888..3923705
Error: Failed to set region: -1:0-963,722(*)
ERROR(freebayes): Could not SetRegion to NC_007198:0..963722
Error: Failed to set region: -1:963,722-1,927,444(*)
ERROR(freebayes): Could not SetRegion to NC_007198:963722..1927444
Error: Failed to set region: -1:1,927,444-2,891,166(*)
ERROR(freebayes): Could not SetRegion to NC_007198:1927444..2891166
Error: Failed to set region: -1:2,891,166-3,854,888(*)
ERROR(freebayes): Could not SetRegion to NC_007198:2891166..3854888
Error: Failed to set region: -1:3,854,888-3,948,441(*)
ERROR(freebayes): Could not SetRegion to NC_007198:3854888..3948441
Error: Failed to set region: -1:0-963,722(*)
ERROR(freebayes): Could not SetRegion to NC_007199:0..963722
Error: Failed to set region: -1:963,722-1,927,444(*)
ERROR(freebayes): Could not SetRegion to NC_007199:963722..1927444
Error: Failed to set region: -1:1,927,444-2,891,166(*)
ERROR(freebayes): Could not SetRegion to NC_007199:1927444..2891166
Error: Failed to set region: -1:2,891,166-3,778,736(*)
ERROR(freebayes): Could not SetRegion to NC_007199:2891166..3778736
Error: Failed to set region: -1:0-963,722(*)
ERROR(freebayes): Could not SetRegion to NC_007200:0..963722
Error: Failed to set region: -1:963,722-1,927,444(*)
ERROR(freebayes): Could not SetRegion to NC_007200:963722..1927444
Error: Failed to set region: -1:1,927,444-2,058,334(*)
ERROR(freebayes): Could not SetRegion to NC_007200:1927444..2058334
Error: Failed to set region: -1:0-963,722(*)
ERROR(freebayes): Could not SetRegion to NC_007201:0..963722
Error: Failed to set region: -1:963,722-1,833,124(*)
ERROR(freebayes): Could not SetRegion to NC_007201:963722..1833124

### bcftools view --include 'GT="1/1" && DP>=0 && AF>=0' -Ov -o snps.filt.vcf snps.raw.vcf

Both INFO/DP and FORMAT/DP exist, which one do you want?

**Comment by tseemann** [comment]
You are using the pre-release version of snippy 4.0_dev

It looks like the BAM file was empty?

What does samtools flagstat snps.bam say?

**Comment by SGarciaCobos** [comment]
Indeed, it seems the BAM file is empty..?:
0 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 mapped (N/A : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

I updated everything trying to solve the problem, isn't the pre-release version of snippy 4.0_dev ready to use?

**Comment by SGarciaCobos** [comment]
I updated samtools to 1.8 as well, and I updated to the last snippy version because initially I was getting the following error:
The fasta sequence does not match the REF at...
That's because I upgraded snippy and all dependencies but now it is giving me constantly the error mentioned above (seems the bam file is empty...) 
I run it using different sequences to check if it was related to the reference genome used and again I get another error when start running freebayes...

**Comment by tseemann** [comment]
Can you even use freebayes manually?
eg `freebayes -f ref.fa snps.bam` etc?

**Comment by tseemann** [comment]
I'm closing this now, but please re-open the issue if you are still having trouble.

**Comment by mdtorohernando** [comment]
Hi! I'm returning the same error. It is a bit strange, as two weeks ago I was using snippy without any problem. The bam file seems to be OK but the problem is bcftools, with the error message: Both INFO/DP and FORMAT/DP exist, which one do you want?. 
[snps.log](https://github.com/tseemann/snippy/files/2937129/snps.log)
Thanks in advanced.
