### ISSUE TITLE
The fasta sequence does not match the REF 

### ISSUE THREAD

**Issue by kelvin-wcl** [tseemann/snippy#183]
Hi Torsten,

I have exported a consensus sequence from a sample to use as a reference in snippy, but I received this error message:

### vcf-consensus snps.vcf.gz < reference/ref.fa > snps.consensus.fa

The fasta sequence does not match the REF at C16SRHH060:217410. Y(AAAATA) in .fa, N in .vcf, frz=216930
 at /home/ubuntu/snippy/bin/../binaries/noarch/vcf-consensus line 20, <STDIN> line 3625.

Can you please advise what is wrong?

Thank you.

Kind Regards,
Kelvin

**Comment by tseemann** [comment]
I am not sure what is going on.
I am no longer supporting Snippy 3.x anymore.
Snippy 4.x is close to release, and you can use the github HEAD version of it now.
Snippy 4 doe not need `vcf-consensus` anymore as it caused problems for some people.

**Comment by kelvin-wcl** [comment]
Hi Torsten,
I have installed Snippy 4. When I run the command, I receive this message:
ubuntu@kwcl-xl3:~/500GB/snippy$ snippy --outdir test1 --ref C16SRHH060.fasta --ctgs 16S_RHH017_12537.fasta 
[04:58:56] This is snippy 4.0-dev2
[04:58:56] Written by Torsten Seemann
[04:58:56] Obtained from https://github.com/tseemann/snippy
[04:58:56] Detected operating system: linux
[04:58:56] Enabling bundled linux tools.
[04:58:56] Found bwa - /home/ubuntu/snippy/binaries/linux/bwa
[04:58:56] Found bcftools - /home/ubuntu/snippy/binaries/linux/bcftools
[04:58:56] Found samtools - /home/ubuntu/snippy/binaries/linux/samtools
[04:58:56] Found snpEff - /home/ubuntu/snippy/binaries/noarch/snpEff
[04:58:56] Found java - /usr/bin/java
[04:58:56] Found gzip - /bin/gzip
[04:58:56] Found samclip - /home/ubuntu/snippy/binaries/noarch/samclip
[04:58:56] Can not find required 'seqtk' in PATH
ubuntu@kwcl-xl3:~/500GB/snippy$ 

Running snippy returned the help menu as expected:
ubuntu@kwcl-xl3:~/500GB/snippy$ snippy
SYNOPSIS
  snippy 4.0-dev2 - fast bacterial variant calling from NGS reads
USAGE
  snippy [options] --outdir <dir> --ref <ref> --R1 <R1.fq.gz> --R1 <R2.fq.gz>
  snippy [options] --outdir <dir> --ref <ref> --ctgs <contigs.fa>
  snippy [options] --outdir <dir> --ref <ref> --bam <reads.bam>
GENERAL
  --help           This help
  --version        Print version and exit
  --citation       Print citation for referencing snippy
  --check          Check dependences are installed then exit (default OFF)
  --force          Force overwrite of existing output folder (default OFF)
  --quiet          No screen output (default OFF)

Kind Regards,
Kelvin

**Comment by tseemann** [comment]
That is not Snippy 4.0.5 - it is a broken conda version that someone prematurely added.

Try `conda update --all` and then `conda install snippy=4.0.5`
