### ISSUE TITLE
mapping several libraries of same genome to one ref

### ISSUE THREAD

**Issue by sbridel** [tseemann/snippy#184]
I wonder how you can do it.

Let's say I have these reads for one genome:
library (i) sample_A_i_R1.fastq.gz sample_A_i_R2.fastq.gz
library (ii) sample_A_ii_R1.fastq.gz sample_A_ii_R2.fastq.gz

So 2 sets of reads (2 libraries) from the same genome.

Can we use all of them when using snippy?
I know for one assembly you can use several libraries.
Does snippy already have this function or not?

**Comment by tseemann** [comment]
So these are two libraries of the same isolate DNA ?

You have 2 options:

1. This will definitely work, but wastes disk space (temporarily).
```
cat  sample_A_i_R1.fastq.gz sample_A_i_R2.fastq.gz > A_R1.fq.gz
cat  sample_A_i_R1.fastq.gz sample_A_i_R2.fastq.gz > A_R2.fq.gz

snippy --R1 A_R1.fq.gz --R2 A_R2.fq.gz
```

2. This probably will not work, but works with other applications that only use the reads once, assuming you use `bash` shell:

```
snippy --R1 <(cat  sample_A_i_R1.fastq.gz sample_A_i_R2.fastq.gz) --R2 <(cat sample_A_i_R1.fastq.gz sample_A_i_R2.fastq.gz)
```
