### ISSUE TITLE
snippy-core bedfile mask only retains last entry

### ISSUE THREAD

**Issue by jrober84** [tseemann/snippy#186]
When you supply a mask file for snippy-core, only the last bedfile entry is used in the masking process. It correctly identifies the number of bed entries but only keeps the last one.

snippy-core --mask mask.bed --verbose SRR1264998_snippy/

NZ_CP012921.1 | 1 | 4751447
NZ_CP012921.1 | 21097 | 21097
NZ_CP012921.1 | 33581 | 33581
NZ_CP012921.1 | 157792 | 157792
NZ_CP012921.1 | 293728 | 293728
NZ_CP012921.1 | 300920 | 300920
NZ_CP012921.1 | 378270 | 378270

[19:23:14] Read 7 regions from BED file to mask SNPs from
$VAR1 = {
          'NZ_CP012921.1' => {
                               'END' => 378271,
                               'START' => '378270'
                             }
        };

**Comment by jrober84** [comment]
It is snippy: 4.0_dev-1 from bioconda. I uninstalled and reinstalled but the issue is still there.

**Comment by tseemann** [comment]
@jrober84 you misunderstand. reinstalling will not help. that conda package should not exist. and there is *no* conda package for the current working version. You need to install manually using the `git clone` method.  A proper version will be in conda in ~ 2 months. Sorry for the hassle.
