### ISSUE TITLE
snpEff

### ISSUE THREAD

**Issue by Jeroen-K** [tseemann/snippy#195]
Dear Torsten Seemann, 

Using snippy 4.0-pre_20180707 on Ubuntu 18.04 LTS, I get an error when snippy tries to use SnpEff: 

Running: snpEff ann -noStats -no-downstream -no-upstream -no-intergenic -no-utr -t -c reference/snpeff.config -dataDir . ref snps.filt.vcf > snps.vcf 2>> snps.log
[14:02:51] Error running command, check mysnps/snps.log

From snps.log: 

**### bcftools view --include '(GT="1/1" || GT="1|1") && DP>=0 && AF>=0' snps.raw.vcf  | vt normalize -r reference/ref.fa - | bcftools annotate --remove '^INFO/TYPE,^INFO/DP,^INFO/RO,^INFO/AO,^INFO/AF,^FORMAT/GT,^FORMAT/DP,^FORMAT/RO,^FORMAT/AO,^FORMAT/QR,^FORMAT/QA,^FORMAT/GL' > **snps.filt.vcf**

**### snpEff ann -noStats -no-downstream -no-upstream -no-intergenic -no-utr -t -c reference/snpeff.config -dataDir . ref snps.filt.vcf > snps.vcf**

Runs using plain FASTA as ref work normally
Could you suggest a solution that I could try?

With kind regards,

Jeroen

**Comment by tseemann** [comment]
What does `snpEff -version` say?

Mine says `SnpEff  4.3t    2017-11-24`

**Comment by tseemann** [comment]
I have updated the bundled snpEff in snippy HEAD, in case you were relying on that.

**Comment by Jeroen-K** [comment]
Thank you for your response, 

`snpEff -version` gives

`SnpEff	4.3p	2017-06-06
`

I will re-clone Snippy, and see if it works
