### ISSUE TITLE
Conda dependency issue in 4.0.0-dev

### ISSUE THREAD

**Issue by rekm** [tseemann/snippy#196]
Hi Torsten, 
the following [lines](https://github.com/tseemann/snippy/blob/b23af3ffd3a7648e8c84e70b0b98e5b397c9d5a0/bin/snippy-core#L8) in snippy-core make conda very unhappy.   
```
8 use Bio::SeqIO;
9 use List::Util qw(sum max any uniq min);
```

It's not really a big issue, but BioPerl is only available for Perl 5.22.0  (in conda space) and 
List::Util uniq seems to be a more recent addition to Perl, which necessitates the upgrade to at least 5.26.
Maybe i am missing something stupid, but it seems to be impossible to package the newest version of 
your tool with conda.
I am 4 hours into trying to package an updated bioperl and the fact, that running bcftools consensus myself is way easier, can no longer be ignored.

**Comment by andersgs** [comment]
@rekm that seems like a Conda issue. No?

**Comment by tseemann** [comment]
Snippy 4.0.0-dev was never meant to be created in Conda. I did not package it. That release is full of bugs and should never be used. The proper version will be out soon. Until then, use `conda install snippy==3.2`
