### ISSUE TITLE
re-code lower case `n` as IUPAC ambiguous base instead

### ISSUE THREAD

**Issue by schultzm** [tseemann/snippy#204]

**Comment by tseemann** [comment]
This is an interesting idea.

Do you know of any software that will use these IUPAC codes correctly?
ie. not just treat like N, or ignore the column

**Comment by schultzm** [comment]
At least `BEAST`, `IQ-Tree`, `RAxML`, `MrBayes` and `PAML` support the use of IUPAC-coded sites.

`BEAST 1.8`: this is achieved by changing all lines of `<treeLikelihood id="treeLikelihood" useAmbiguities="false">` to `<treeLikelihood id="treeLikelihood" useAmbiguities=“true">`
`BEAST2`: use `<distribution id="treeLikelihood.ant" spec="TreeLikelihood" tree="@Tree.t:tree" useAmbiguities="true">` [see here](https://groups.google.com/forum/#!topic/beast-users/rWqz6FcTdKU)

`IQ-Tree`: [see How does IQ-TREE treat gap/missing/ambiguous characters?](http://www.iqtree.org/doc/Frequently-Asked-Questions)

`RAxML`: [see here](https://groups.google.com/forum/#!topic/raxml/GrKRkN-3XAo)

`MrBayes`: [p86](http://mrbayes.sourceforge.net/mb3.2_manual.pdf)

`PAML`: [p12](http://abacus.gene.ucl.ac.uk/software/pamlDOC.pdf)

**Comment by tseemann** [comment]
I've had a think about this. These are not ambiguous sites. These are false mappings from mixed populations. These are definitely sites we don't want in any phylogenomic inference. I will leave them as N.
