### ISSUE TITLE
Exclusion of reference from aln in snippy-core 4

### ISSUE THREAD

**Issue by sbaines** [tseemann/snippy#208]
Hi Torsten, 

Could you possibly add in the option to exclude the reference sequence from the alignments generated by snippy-core in v4? It was option --noref in the previous version.

Thanks, Sarah B.

**Comment by andersgs** [comment]
@sbaines you can use `seqkit grep -v Reference` to remove the reference from the alignment.

**Comment by sbaines** [comment]
Thanks @andersgs . I have been doing something similar. The --noref option in the old version was just handy because it would also remove the snp sites that were only between one strain and the reference. I can accomplish this easy enough with with a second run through snp-sites, its just an extra step is all!

**Comment by tseemann** [comment]
I won't be supporting --noref in Snippy 4.   

I think it's important to have it do understand if it was a good "middle-man" or not.
