### ISSUE TITLE
Snippy install "Can't locate Bio/SeqIO.pm in @INC

### ISSUE THREAD

**Issue by sharbie88** [tseemann/snippy#215]
Hello, I installed via miniconda bioconda instructions but installation check came up with this error message.  Can you please tell me how to fix this? (PS. I'm very new to this.)

Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /home/sharb/miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/sharb/miniconda3/lib/site_perl/5.26.2 /home/sharb/miniconda3/lib/5.26.2/x86_64-linux-thread-multi /home/sharb/miniconda3/lib/5.26.2 .) at /home/sharb/miniconda3/bin/snippy line 11.
BEGIN failed--compilation aborted at /home/sharb/miniconda3/bin/snippy line 11.

Thanks,

**Comment by tseemann** [comment]
I am told  bioperl is currently broken on bioconda, and that it will be fixed within a week.

Snippy 4 will not appear until that is fixed first.

**Comment by sharbie88** [comment]
Wow! so fast - thank you.  So do I need to undo the install for now and re-install when the fix is done? (if so, how?)
And will you post a note to say when it's fixed?

thanks again.

**Comment by tseemann** [comment]
@sharbie88 i think 4.0.0 now works on bioconda. i am not sure how to upgrade it. maybe `conda update --all` ?

**Comment by sharbie88** [comment]
Thanks for that.  I used conda update --all and it all went through without a hitch, but still v3.1.

**Comment by tseemann** [comment]
Try
```
conda install snippy==4.05
```
or
```
conda install -c bioconda -c conda-forge snippy>=4.0
```

**Comment by sharbie88** [comment]
Sweet.  2nd one didn't work - just hung the window, but first one did for 4.0.5.  Thanks!

**Comment by nenadmacesic** [comment]
Hi, I just installed 4.2 using Conda and have run into the same issue.

**Comment by tseemann** [comment]
@nenadmacesic snippy 4.2.3 is now in conda and brew. i am told the channel order has changed in brew now.  you might have to do `conda install -c conda-forge -c bioconda snippy` instead. Make sure you `conda update conda` and `conda update --all` too!

**Comment by nenadmacesic** [comment]
Great - a Brew reinstall did the trick but the Conda is still not quite working. Thank you for your help and for making these tools available Torsten, much appreciated.

**Comment by tseemann** [comment]
Conda is in so much flux at the moment it is hard to debug, but we will get there. I think it's a python problem now, the freebayes helper scripts. I will replace them with my own perl ones.

**Comment by nickloman** [comment]
I'm still having problems installing Snippy on MacOS. Any ideas?
snippy --version
Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /Users/nick/miniconda3/envs/metaphylo/bin/../perl5 /Users/nick/miniconda3/envs/metaphylo/lib/perl5/site_perl/5.22.0/darwin-thread-multi-2level /Users/nick/miniconda3/envs/metaphylo/lib/perl5/site_perl/5.22.0 /Users/nick/miniconda3/envs/metaphylo/lib/perl5/5.22.0/darwin-thread-multi-2level /Users/nick/miniconda3/envs/metaphylo/lib/perl5/5.22.0 .) at /Users/nick/miniconda3/envs/metaphylo/bin/snippy line 15.
BEGIN failed--compilation aborted at /Users/nick/miniconda3/envs/metaphylo/bin/snippy line 15.

**Comment by jtfield** [comment]
Howdy. This issue popped up for me with a conda install as well. I used ```conda update --all``` and still nothing.

**Comment by Lamm-a** [comment]
I have also just come across this same problem

**Comment by Ankita-1211** [comment]
nothing worked for me while installing via conda, i tried all above suggestions too.
every time i get this when i type snippy --check

Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /root/miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /root/miniconda3/lib/site_perl/5.26.2 /root/miniconda3/lib/5.26.2/x86_64-linux-thread-multi /root/miniconda3/lib/5.26.2 .) at /root/miniconda3/bin/snippy line 11.
BEGIN failed--compilation aborted at /root/miniconda3/bin/snippy line 11.

Pls HELP !!!!

**Comment by tseemann** [comment]
I did not write the conda package for snippy.
Please make a whole new conda env for it and see what happens:
```
conda activate base
conda update --all --yes
conda create -n snippy_env snippy>=4.6
conda activaye snippy_env
snippy --check
```

**Comment by daviesdrew** [comment]
@tseemann 

I tried the solution you posted 15 days ago after running into the same issue and it did not fix the error. 

The command hung on conda create -n snippy_env snippy>=4.6

**Comment by nenadmacesic** [comment]
@daviesdrew - I had the same issue which resolved when I used this slight fix:
conda create -n snippy_env snippy=4.6.0
Snippy has worked fine subsequently.

**Comment by webermarcolivier** [comment]
Same problem here, and new environment, followed by `conda install -c conda-forge -c bioconda -c defaults snippy` did not solve the problem.

**Comment by LuoDaTou123** [comment]
conda install snippy >snippy 3.1 run error
github clone snippy>snippy 4.6 run ok
here:
git clone https://github.com/tseemann/snippy.git

You'll need to add Snippy's bin directory to your $PATH

maybe conda snippy is old version not upgrade
