### ISSUE TITLE
snippy-core v4.0.0 sample naming

### ISSUE THREAD

**Issue by amilesj** [tseemann/snippy#217]
I ran the new snippy-core on snippy output in a couple of different directories, and it names samples with the whole path to the directory I point to (as entered on the command line) rather than just the snippy directory name for each sample. 

For example: if i run `snippy-core ../*` to get all snippy files one directory up, the samples end up named `../sample1` rather than just `sample1` in the multifasta output. 

I think this is a new behavior in snippy 4. Let me know if it is intentional, or if I am doing something wrong!

Thanks,
Arianna

**Comment by tseemann** [comment]
@amilesj thank you so much for reporting this! I've fixed in 4.0.2
