### ISSUE TITLE
filtered variant calls difference

### ISSUE THREAD

**Issue by alantsangmb** [tseemann/snippy#218]
Hi, Torsten. I am aligning the reads of two highly similar isolates (isolate A and B) to a reference genome using snippy.

For a particular position, both isolates show a 'T' in the snps.raw.vcf and also the bam file.
However, this 'T' only present in isolate A in the snps.vcf and snps.filt.vcf

The particular snp shown in the snps.raw.vcf for the two isolates are as follows;

A:
CP014960.1	710089	.	G	T	116.417	.	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=4;CIGAR=1X;DP=4;DPB=4;DPRA=0;EPP=5.18177;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=10.1503;PAIRED=0;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=152;QR=0;RO=0;RPL=4;RPP=11.6962;RPPR=0;RPR=0;RUN=1;SAF=1;SAP=5.18177;SAR=3;SRF=0;SRP=0;SRR=0;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	1/1:4:0,4:0:0:4:152:-14.0499,-1.20412,0

B:
CP014960.1	710089	.	G	T	247.11	.	AB=0.909091;ABP=19.0002;AC=1;AF=0.5;AN=2;AO=10;CIGAR=1X;DP=11;DPB=11;DPRA=0;EPP=3.0103;EPPR=5.18177;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=10.7924;PAIRED=0.7;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=350;QR=38;RO=1;RPL=10;RPP=24.725;RPPR=5.18177;RPR=0;RUN=1;SAF=5;SAP=3.0103;SAR=5;SRF=1;SRP=5.18177;SRR=0;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	0/1:11:1,10:1:38:10:350:-28.5219,0,-0.485939

I can't figure out why the snp in isolate B was filtered. It leads to one more SNP difference between A and B. Any manual/reference I can read further to understand how the filter work? Thank you so much.

The head of the vcf file for your reference:
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=20180810
##source=freeBayes v1.2.0
##reference=reference/ref.fa
##contig=<ID=CP014960.1,length=4799801>
##phasing=none
##commandline="freebayes -p 2 -P 0.5 -q 13 -m 60 --min-repeat-entropy 1.0 -f reference/ref.fa snps.bam --region CP014960.1:0-157415"

**Comment by alantsangmb** [comment]
Thank you so much Torsten.

I was using snippy-4.0-dev for this case.
I have upgraded to snippy-4.0.5, samtools 1.9 , bcftools 1.9 and freebayes 1.1 now.

And I have re-run the script and the results for that snp are as follow:
SampleA:
No snp called at pos 710089
SampleB:
CP014960.1	710089	.	G	T	365.774	.	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=14;CIGAR=1X;DP=15;DPB=15;DPRA=0;EPP=5.49198;EPPR=5.18177;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=60;NS=1;NUMALT=1;ODDS=16.0274;PAIRED=0.785714;PAIREDR=1;PAO=0;PQA=0;PQR=0;PRO=0;QA=502;QR=38;RO=1;RPL=14;RPP=33.4109;RPPR=5.18177;RPR=0;RUN=1;SAF=5;SAP=5.49198;SAR=9;SRF=1;SRP=5.18177;SRR=0;TYPE=snp	GT:DP:AD:RO:QR:AO:QA:GL	1/1:15:1,14:1:38:14:502:-41.7147,-0.718181,0

And I tried to execute under the directory : samtools mpileup --min-MQ 60 --min-BQ 13 -f ref.fa snps.bam CP014960.1:710089-710089
But following error returned:
[E::hts_open_format] Failed to open file CP014960.1:710089-710089
[mpileup] failed to open CP014960.1:710089-710089: Protocol not supported

**Comment by tseemann** [comment]
Sorry i used the wrong syntax:

```
samtools mpileup -r 'CP014960.1:710089-710089' --min-MQ 60 --min-BQ 13 -f ref.fa snps.bam
```

**Comment by alantsangmb** [comment]
Thanks! Much appreciated.
