### ISSUE TITLE
Fix instructions for installation from source package

### ISSUE THREAD

**Issue by ikirker** [tseemann/snippy#223]
Current:

```bash
cd $HOME
git clone https://github.com/tseemann/snippy.git
$HOME/bin/snippy --help
```

This will result in `~/snippy` being created, but there's no provided mechanism for getting to a state where `$HOME/bin` would contain a valid snippy file or link.

Maybe this should be:

```bash
cd $HOME
git clone https://github.com/tseemann/snippy.git
$HOME/snippy/bin/snippy --help
```

**Comment by tseemann** [comment]
Whoops, I missed a "snippy" in the middle. I'll update the docs in the morning. Thank you!
