### ISSUE TITLE
vcffirstheader python 2 dependency in Snippy 4.x

### ISSUE THREAD

**Issue by amilesj** [tseemann/snippy#224]
vcffirstheader seems to use python 2. When I ran Snippy 4.0.5 in my normal environment with python 3.6.2, I got the following error in the log after the `freebayes-parallel` line: 

`File "/home/amiles/miniconda3/bin/vcffirstheader", line 9
    print line.strip()
             ^
SyntaxError: invalid syntax`

I changed my script to activate my environment with python 2.7 before running Snippy, and it worked fine. 

Best,
Arianna

**Comment by luckystar008** [comment]
I had the same problem，When I run  Snippy 4.0.5, vcffirstheader reports an error：
`### freebayes-parallel reference/ref.txt 8 -p 2 -P 0 -C 10 --min-repeat-entropy 1.5 --strict-vcf -q 13 -m 60
 --min-coverage 10 -F 0.05 -f reference/ref.fa snps.bam > snps.raw.vcf

  File "/disk1/cau/cvmjxx/miniconda3/bin/vcffirstheader", line 9
    print line.strip()
             ^
SyntaxError: invalid syntax
`
And the version of python：
`Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.`

**Comment by tseemann** [comment]
@luckystar008 @amilesj 
Can you tell me what these command say?
```
head -n 1 $(which vcffirstheader)
head -n 1 $(which fasta_generate_regions.py)
```

**Comment by amilesj** [comment]
`#!/usr/bin/env python`
`#!/home/amiles/miniconda3/bin/python`
`#!/bin/bash`

**Comment by tseemann** [comment]
And what does `/home/amiles/miniconda3/bin/python --version` say?

Under python PEP rules it should be 2.x  .... but my guess is 3.x due to Conda madness.

**Comment by amilesj** [comment]
Yes its 3.6.2

**Comment by luckystar008** [comment]
1.#!/usr/bin/env python
2.#!/disk1/cau/cvmjxx/miniconda3/bin/python
3.#!/bin/bash
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Hope to solve this problem.All the best！

**Comment by tseemann** [comment]
I think I will need to write my own wrappers for these python tools, as the conda 2 vs 3 problem will keep cropping up.

Until then, you can change `/usr/bin/env python` to `/usr/bin/python` or whereever your system has python 2.x installed.  they use no modules so should just work.

**Comment by luckystar008** [comment]
@tseemann Do I just change the version of pyhon used by vcffirstheader or change the pyhon version of entire snippy and dependency package?

**Comment by tseemann** [comment]
Snippy is written in Perl. not python.

Snippy uses other packages (freebayes, vcflib) which include some python 2.x scripts in them. They are the issue, not snippy itself. You just need to edit the first line of all the failing scripts to point to a  python 2 executable.

**Comment by rtfcoimbra** [comment]
I'm a bit late here but one can also change all instances of `print line.strip()` to `print(line.strip())` in the `vcffirstheader` script. That fixes the syntax compatibility with python 3 and it worked for me.

**Comment by jdeligt** [comment]
Please also see #309 for another python 2 dependecy fix

**Comment by tseemann** [comment]
I have joined the `vcflib` project and made a 1.0.0-rc3 release which is py3 now.
Will be in Conda  soon: https://github.com/bioconda/bioconda-recipes/pull/17050

**Comment by tseemann** [comment]
Fixed now
