### ISSUE TITLE
when masking in snippy-core, (-) strand annotation crashes program

### ISSUE THREAD

**Issue by phiweger** [tseemann/snippy#227]
When the bed file used to `snippy-core --mask ...` has annotations on the minus strand (i.e. start > end) snippy-core errs out w/

```bash
Opening: core.tab
Opening: core.vcf
Processing contig: reference
Masking alignment at 27 regions
Negative repeat count does nothing at /usr/local/bin/snippy-core line 252, <VCF> line 5125.
Negative repeat count does nothing at /usr/local/bin/snippy-core line 252, <VCF> line 5125.
Negative repeat count does nothing at /usr/local/bin/snippy-core line 252, <VCF> line 5125.
Negative repeat count does nothing at /usr/local/bin/snippy-core line 252, <VCF> line 5125.
substr outside of string at /usr/local/bin/snippy-core line 253, <VCF> line 5125.
```

thx.

**Comment by tseemann** [comment]
@phiweger can you please paste the BED file here please?

I only use the first 3 columns of the BED file
```
CHR \t BEGIN \t END
```
The BED format requires that BEGIN is less than END. 
Are yours back to front?

Complement features are to use the strand in column 6.
Strand is not relevant for masking SNPS, so I just use the `CHR:BEGIN-END` ranges.
