### ISSUE TITLE
error using gbk

### ISSUE THREAD

**Issue by memoriasresiduais** [tseemann/snippy#229]
Hi Torsten,

I'm trying to run snippy/4.1.0 with snpEff/4.3 and I get an error about the codonTable:

### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

java.lang.RuntimeException: Error parsing property 'ref.MYREF.codonTable'. No such codon table 'Bacterial_and_Plant_Plastid'
	at org.snpeff.snpEffect.Config.createCodonTables(Config.java:169)
	at org.snpeff.snpEffect.Config.readConfig(Config.java:650)
	at org.snpeff.snpEffect.Config.init(Config.java:480)
	at org.snpeff.snpEffect.Config.<init>(Config.java:117)
	at org.snpeff.SnpEff.loadConfig(SnpEff.java:451)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:364)
	at org.snpeff.SnpEff.run(SnpEff.java:1183)
	at org.snpeff.SnpEff.main(SnpEff.java:162)

It seems the same error that some people noted in some previous issues, but it is not clear to me how we can fix it.  
https://github.com/tseemann/snippy/issues/86
https://github.com/tseemann/snippy/issues/154

Any feedback will be much appreciated!
Thanks,
Alexandra

**Comment by memoriasresiduais** [comment]
It doesn't seem to work make any gbk file, either directly downloaded from NCBI, generated by PROKKA or the example.gbk.
It works well with the reference files in fasta, though, so problem overcomed.
Cheers,
Alexandra

**Comment by tseemann** [comment]
I've never had this error reported before. I suspect the bioconda package for snpeff is broken in some way - it can't find its own config files.

What do these say?

```
which snpEff
snpEff -version
which java
java -version
```

**Comment by EricDeveaud** [comment]
Hello, 

the installation was not performed using bioconda. 
it was done from sources, and it uses external binaries for the dependencies.
required external tools binaries are provided thru module environment system 

snpEff/4.3 works correctly when used as standalone 
java/1.8.0

**Comment by tseemann** [comment]
That is not the full version of `snpEff`  - it has a letter after it. 
Please run the commands I asked for please?

```
snpEff -version
SnpEff  4.3t    2017-11-24
```

**Comment by memoriasresiduais** [comment]
Sorry guys, I missed your replies in the spam box...

The version we're using:
SnpEff version SnpEff 4.3t (build 2017-11-24 10:18), by Pablo Cingolani

**Comment by memoriasresiduais** [comment]
And the java:
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

**Comment by tseemann** [comment]
I can;t explain why it is not working. I am assuming the conda package is not installing the snpeff config file in the correct place, and so it doesn't know about the different codon tables.

The brew package ensures it is found:
`        s.gsub! "${jardir}/snpEff.config", "#{pkgshare}/snpEff.config"`

Not sure if the conda package is:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/snpeff/build.sh

I don't think this is a snippy problem.

If yiou can find the official snpeff.config file, you can edit the snippy script and add `-c path_to_config_file` and maybe that will work.
