### ISSUE TITLE
Unable to create symbolic link snippy 4.05

### ISSUE THREAD

**Issue by PyroEndy** [tseemann/snippy#230]
Hi Torsten,

I have just upgraded from snippy 3.1 to snippy 4.05 but I have encountered an issue.

When running snippy I now get this error:

ln: failed to create symbolic link ‘./ref.fa’: Operation not supported

I understand this is because I am using CIFS/SMB shares and ln does not like this.

Is there anyway to fix this so it'll work?

Thanks in advance,

Nick

**Comment by tseemann** [comment]
You will need to edit the main `snippy` script and change the link to a copy:

```
  "ln -sf $refdir/ref.fa .",
  "ln -sf $refdir/ref.fa.fai .",
```

to

```
  "cp -f $refdir/ref.fa .",
  "cp -f $refdir/ref.fa.fai .",
```

Also, make sure you upgrade to version 4.1.0 as there was a bug in 4.0.5.
