### ISSUE TITLE
ALIGNED	& UNALIGNED calculation

### ISSUE THREAD

**Issue by fengyuchengdu** [tseemann/snippy#231]
An Unicycler hybrid-assembled plasmid (~34k) was mapped using its Illumina reads (same reads used in assembly, about 200x depth on average) previously gave us ZERO unaligned region (probably done by snippy 3.x or 4.0.dev). 

However, we did the same thing this week using snippy 4.1 and it told us there were two regions (~500bp x 2) with '-', hence ~1000bp had coverage=0  

We are not sure if this is normal, and wondering which is correct, thanks.

All snippy settings remained as default.

**Comment by fengyuchengdu** [comment]
also in the snp.txt (generated after running snippy with defaults), the number shown in "ReferenceSize" is not equal to the actual nt size of reference.

**Comment by tseemann** [comment]
Snippy 3.x and 4.0-dev were totally different so it is important which one you meant.
Snippy 4.0-dev had `--mincov = 0` so you would always get UNALIGNED=0.
Snippy 4.1.0 uses `--mincov 10` now, and alsi `--basequal 13` - these affect that number.

What file is `ReferenceSize` in?

**Comment by fengyuchengdu** [comment]
a file named "snps.txt" containing 

DateTime	2018-08-30T09:03:17
ReadFiles	/home/zong/Desktop/020135/020135bb_1.fq.gz /home/zong/Desktop/020135/020135bb_2.fq.gz
Reference	/home/zong/Desktop/020135/p_020135.gbk
ReferenceSize	134042
Software	snippy 4.1.0
Variant-COMPLEX	2
Variant-DEL	1
Variant-INS	1
Variant-SNP	4
VariantTotal	8

**Comment by tseemann** [comment]
@fengyuchengdu  Can you let me know what this command says?
```
grep LOCUS /home/zong/Desktop/020135/p_020135.gbk
```
I want to check what `ReferenceSize` should be.
