### ISSUE TITLE
brew install on MacOS throws error

### ISSUE THREAD

**Issue by mblaxter** [tseemann/snippy#239]
Installing using homebrew on MacOSX 10:13

brew install brewsci/bio/snippy
==> Installing snippy from brewsci/bio
snippy: Linux is required.
Error: An unsatisfied requirement failed this build.

So the brew installer is looking for "Linux"; is this inside the snippy bundle or is this some dependency?

**Comment by tseemann** [comment]
Brewed snippy only works on Linux, not Mac, at the moment.
I could not get it to pass the tests on Mac for some reason.
I am going to try again with the latest version.

**Comment by mblaxter** [comment]
Thanks Torsten
Im sorry to have bothered you with this… ill access a linux box instead for now, but hope that the Mac.nix version appears soon
Best
Mark


> On 19 Sep 2018, at 13:45, Torsten Seemann <notifications@github.com> wrote:
> 
> Brewed snippy only works on Linux, not Mac, at the moment.
> I could not get it to pass the tests on Mac for some reason.
> I am going to try again with the latest version.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by tseemann** [comment]
Trying here: https://github.com/brewsci/homebrew-bio/pull/437

**Comment by mblaxter** [comment]
Thanks! Works fine.
/usr/local/Cellar/snippy/4.2.1/bin/snippy --version
snippy 4.2.1

/usr/local/Cellar/snippy/4.2.1/bin/snippy --check
[09:43:41] This is snippy 4.2.1
[09:43:41] Written by Torsten Seemann
[09:43:41] Obtained from https://github.com/tseemann/snippy
[09:43:41] Detected operating system: darwin
[09:43:41] Enabling bundled darwin tools.
…
[09:43:42] Dependences look good!

I also tried an install of v3.2 yesterday via conda and that functions perfectly also

> On 19 Sep 2018, at 17:21, Torsten Seemann <notifications@github.com> wrote:
> 
> @mblaxter try this for now:
> 
> brew install -s -v https://raw.githubusercontent.com/brewsci/homebrew-bio/dd347f0883c3a61130242061a787a62cde143118/Formula/snippy.rb
> ```
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by tseemann** [comment]
@mblaxter Please don't use v3.2 -- it has many serious bugs.
