### ISSUE TITLE
Use of uninitialized value

### ISSUE THREAD

**Issue by samlipworth** [tseemann/snippy#240]
Hi Torsten,

I have used snippy without issue for ages but have started getting an error message:

### /gpfs0/users/bag/lipworth/miniconda2/bin/snippy-vcf_to_tab --gff reference/ref.gff --ref reference/ref.fa --vcf snps.vcf > snps.tab

Loading reference: reference/ref.fa
Loaded 1 sequences.
Loading features: reference/ref.gff
Parsing variants: snps.vcf
Converted 4175 SNPs to TAB format.

### /gpfs0/users/bag/lipworth/miniconda2/bin/snippy-vcf_extract_subs snps.filt.vcf > snps.subs.vcf

Use of uninitialized value in concatenation (.) or string at /gpfs0/users/bag/lipworth/miniconda2/bin/snippy-vcf_extract_subs line 137, <> line 28.
Use of uninitialized value in concatenation (.) or string at /gpfs0/users/bag/lipworth/miniconda2/bin/snippy-vcf_extract_subs line 137, <> line 29.
Use of uninitialized value in concatenation (.) or string at /gpfs0/users/bag/lipworth/miniconda2/bin/snippy-vcf_extract_subs line 137, <> line 30.
Use of uninitialized value in concatenation (.) or string at /gpfs0/users/bag/lipworth/miniconda2/bin/snippy-vcf_extract_subs line 137, <> line 31.
Use of uninitialized value in concatenation (.) or string at /gpfs0/users/bag/lipworth/miniconda2/bin/snippy-vcf_extract_subs line 137, <> line 32.
Use of uninitialized value in concatenation (.) or string at /gpfs0/users/bag/lipworth/miniconda2/bin/snippy-vcf_extract_subs line 137, <> line 33.
Use of uninitialized value in concatenation (.) or string at /gpfs0/users/bag/lipworth/miniconda2/bin/snippy-vcf_extract_subs line 137, <> line 34.
Use of uninitialized value in concatenation (.) or string at /gpfs0/users/bag/lipworth/miniconda2/bin/snippy-vcf_extract_subs line 137, <> line 35.
Use of uninitialized value in concatenation (.) or string at /gpfs0/users/bag/lipworth/miniconda2/bin/snippy-vcf_extract_subs line 137, <> line 36.
Use of uninitialized value in concatenation (.) or string at /gpfs0/users/bag/lipworth/miniconda2/bin/snippy-vcf_extract_subs line 137, <> line 37.
Use of uninitialized value in concatenation (.) or string at /gpfs0/users/bag/lipworth/miniconda2/bin/snippy-vcf_extract_subs line 137, <> line 38.

Having said this, the output from snippy still looks OK.  Any idea what the issue is?

**Comment by CJREID** [comment]
Hi Torsten,

I am getting a similar error when using snippy-core 


(snippy) [cjreid@titan12 snippy_out]$ snippy-core --ref ~/JJ1897_ST131.fasta *.out
Saving reference FASTA: core.ref.fa
Loaded 1 sequences totalling 5174541 bp.
Will mask 0 positions ~ 0.00%
Use of uninitialized value in transliteration (tr///) at /home/cjreid/miniconda3/envs/snippy/bin/snippy-core line 141.
Use of uninitialized value in transliteration (tr///) at /home/cjreid/miniconda3/envs/snippy/bin/snippy-core line 142.
Use of uninitialized value in transliteration (tr///) at /home/cjreid/miniconda3/envs/snippy/bin/snippy-core line 171, <VCF> line 4559.


These three lines come up for every output file I'm giving to snippy-core. The 'snps' files in the output directories look normal though.

Cheers

Cam

**Comment by samlipworth** [comment]
one other thing --mask gives me 'Unknown option: mask' - doesn't seem to be an option looking at the code either.

**Comment by tseemann** [comment]
Did you use a FASTA file with sequence IDs that have a pipe character in them ?

**Comment by tseemann** [comment]
The latest Snippy will warn about this. Try and use a Genbank if you can - so you get consequences too.

**Comment by CJREID** [comment]
Same story here.

Thanks

**Comment by tseemann** [comment]
@CJREID @samlipworth COnda and Brew should both have snippy 4.2.3 now.
