### ISSUE TITLE
seqret parsing of fasta headers with pipes causes snippy-core to not parse reference information correctly 

### ISSUE THREAD

**Issue by jrober84** [tseemann/snippy#242]
seqret is changing fasta headers that is causing issues with snippy-core
input headers:
>NC_003197|1
>NC_003277

output headers:
>1 NC_003197
>NC_003277

These headers then get parsed as chromsome ids: "1","NC_003277" which no longer match the fasta information in the snippy folder.
Use of uninitialized value in transliteration (tr///) at line 174,175

This causes the unaligned portion to always be reported at 0bp.

If I run snippy with reference fastas without pipes then everything works great.

**Comment by tseemann** [comment]
Yes, the problem is `|` characters in the FASTA ID get "processed" in EMBOSS (ie. mangled) and there is no way to disable it AFAIK.  I will write code and remove the dependency on `seqret`.

**Comment by tseemann** [comment]
I am now using `readseq` instead and this will appear in Snippy 4.3.0

Thanks for the report!
