### ISSUE TITLE
Question: snippy-core

### ISSUE THREAD

**Issue by MichWeb75** [tseemann/snippy#243]
I am running **snippy-core** with all output folders but it demands the **reference fasta**, although the reference is contained in all folders as ref.fa and reference/

`snippy-core folder1 folder2 folder3`

ERROR: Please provide --ref FASTA/GENBANK

**Comment by tseemann** [comment]
I would suggest giving it what it is asking for.

```
snippy-core --ref ONE_OF_THE_FOLDERS/reference/ref.fa  ....
```

Snippy 3.x attempted to auto-detect but I remove that feature, because many pipelines delete all the `reference/` folders to prevent space wastage.
