### ISSUE TITLE
Snippy-core error: "Alignment core.full.aln contains sequences of unequal length"

### ISSUE THREAD

**Issue by BaMagalhaes** [tseemann/snippy#246]
I performed snippy for 74 isolates of P. aeruginosa in batch, using the same reference genome for all. The reference I used is a PacBio assembled genome, corrected using pilon. However, when I used the snippy-core script with the same reference:

$ /home/localadmin/snippy/bin/snippy-core' --ref st17_pilon.fasta <output folders from snippy>

I get the following error:

"Running: snp-sites -c -o core.aln core.full.aln
snp-sites: invalid option -- 'c'
Alignment core.full.aln contains sequences of unequal length. Expected length is 0 but got 6706800 in sequence Reference

ERROR: Could not run: snp-sites -c -o core.aln core.full.aln"

I can't understand why this happens. It seems to be happening after I updated snippy to the new version, as before there was no error but I'm not sure this is the reason.

[README_snippy_core.docx](https://github.com/tseemann/snippy/files/2473872/README_snippy_core.docx)

**Comment by tseemann** [comment]
It looks like your `snp-sites` is a very old version that doesn't support the `-c` option. 

```
% snp-sites -V
snp-sites 2.4.0
```

From your log it looks like it's installed from Debian maybe? 
Yours is `/usr/bin/snp-sites`
What does `snp-sites -V say for you` ?

**Comment by BaMagalhaes** [comment]
It was indeed an older version, so I updated snp-sites and now I have:

$ snp-sites -V
snp-sites 2.4.1

However, when I try the snippy-core script again I still get an error related to snp-sites, but a different one:

"Running: snp-sites -c -o core.aln core.full.aln
snp-sites: symbol lookup error: snp-sites: undefined symbol: generate_snp_sites_with_ref_pure_mono
ERROR: Could not run: snp-sites -c -o core.aln core.full.aln"

[README_snippy_core_2.docx](https://github.com/tseemann/snippy/files/2487449/README_snippy_core_2.docx)
