### ISSUE TITLE
Is core.full.aln a "core" genome alignment or "reference" genome alignment?

### ISSUE THREAD

**Issue by cizydorczyk** [tseemann/snippy#251]
Hi,

Searched around a bit but couldn't find anything on the topic.

I found that the "core.full.aln" file is a whole genome alignment the same length as the reference sequence. I assume this means that the set of core SNPs for each isolate was simply imprinted on the reference sequence? (and so positions would be included in the alignment regardless of whether an isolate actually has data for those positions or not; the isolate would just have a reference base at any "missing" sites)

If the above statement is true, then is it possible to obtain a "core genome alignment" from Snippy, where it is a genome alignment containing variant and invariant sites but only from positions that are present among ALL isolate genomes?

I ask because I am interested in running a BEAST analysis afterward, and am not sure how clock rate estimation/etc. would be affected by including positions absent from an isolate in an alignment.

Thanks!
Conrad

**Comment by tseemann** [comment]
It is a reference based alignment.

No, I do not default to reference - i mark zero coverage etc in the alignment correctly.
See https://github.com/tseemann/snippy#why-is-corefullaln-an-alphabet-soup

You probably want to run this as described at end of this section:

```
snippy-clean_full_aln core.full.aln > clean.full.aln
snp-sites -b -c core.full.aln > beast.aln
```

**Comment by cizydorczyk** [comment]
Great, thank you for the clarification - much appreciated!!
