### ISSUE TITLE
Snippy bcftools error

### ISSUE THREAD

**Issue by JordanVV** [tseemann/snippy#260]
Hello,

After checking the "python" problem, I am faced with another error :
[samclip] Processed 1000000 records...
[samclip] Processed 1100000 records...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (375, 119604, 8, 295)
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (244, 342, 530)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1102)
[M::mem_pestat] mean and std.dev: (382.64, 213.66)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1388)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (335, 442, 565)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1025)
[M::mem_pestat] mean and std.dev: (455.22, 179.76)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1255)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (233, 399, 624)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 1406)
[M::mem_pestat] mean and std.dev: (432.64, 280.90)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 1797)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RR
[M::mem_process_seqs] Processed 246550 reads in 60.030 CPU sec, 20.808 real sec
[samclip] Processed 1200000 records...
[samclip] Processed 1300000 records...
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -Y -M -R @rg\tID:mysnps\tSM:mysnps -t 8 reference/ref.fa /Users/jordanv/Pseudomonas-CHAR_R1_001.fastq /Users/jordanv/Pseudomonas-CHAR_R2_001.fastq
[main] Real time: 136.626 sec; CPU: 352.724 sec
[samclip] Total SAM records 1381406, removed 547162, allowed 87919, passed 834244
[samclip] Header contained 3 lines
[samclip] Done.
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
[14:55:33] Running: samtools index snps.bam 2>> snps.log
[14:55:35] Running: fasta_generate_regions.py reference/ref.fa.fai 465500 > reference/ref.txt 2>> snps.log
[14:55:35] Running: freebayes-parallel reference/ref.txt 8 -p 2 -P 0 -C 10 --min-repeat-entropy 1.5 --strict-vcf -q 13 -m 60 --min-coverage 10 -F 0.05 -f reference/ref.fa snps.bam > snps.raw.vcf 2>> snps.log
[14:56:20] Running: bcftools view --include 'FMT/GT="1/1" && QUAL>=100 && FMT/DP>=10 && (FMT/AO)/(FMT/DP)>=0' snps.raw.vcf | vt normalize -r reference/ref.fa - | bcftools annotate --remove '^INFO/TYPE,^INFO/DP,^INFO/RO,^INFO/AO,^INFO/AB,^FORMAT/GT,^FORMAT/DP,^FORMAT/RO,^FORMAT/AO,^FORMAT/QR,^FORMAT/QA,^FORMAT/GL' > snps.filt.vcf 2>> snps.log
dyld: Symbol not found: __ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
Referenced from: /usr/local/bin/vt
Expected in: /usr/lib/libstdc++.6.0.9.dylib
in /usr/local/bin/vt
[14:56:20] Error running command, check mysnps/snps.log

When I open the snps.log, I got this at the end:

bcftools view --include 'FMT/GT="1/1" && QUAL>=100 && FMT/DP>=10 && (FMT/AO)/(FMT/DP)>=0' snps.raw.vcf | vt normalize -r reference/ref.fa - | bcftools annotate --remove '^INFO/TYPE,^INFO/DP,^INFO/RO,^INFO/AO,^INFO/AB,^FORMAT/GT,^FORMAT/DP,^FORMAT/RO,^FORMAT/AO,^FORMAT/QR,^FORMAT/QA,^FORMAT/GL' > snps.filt.vcf

Failed to open -: unknown file type

I try to use genbank or fasta file as ref, and I had the same error...

Thank's for your help.

**Comment by tseemann** [comment]
`Expected in: /usr/lib/libstdc++.6.0.9.dylib`

Your software isn't setup correctly. Perhaps you are mixing conda and brew and manually installed tools?

**Comment by proychou** [comment]
@tseemann Torsten, I'm getting something similar but snippy --check ran fine.

```
[11:41:19] Running: bcftools view --include 'FMT/GT="1/1" && QUAL>=100 && FMT/DP>=10 && (FMT/AO)/(FMT/DP)>=0' snps.raw.vcf  | vt normalize -r reference/ref.fa - | bcftools annotate --remove '^INFO/TYPE,^INFO/DP,^INFO/RO,^INFO/AO,^INFO/AB,^FORMAT/GT,^FORMAT/DP,^FORMAT/RO,^FORMAT/AO,^FORMAT/QR,^FORMAT/QA,^FORMAT/GL' > snps.filt.vcf 2>> snps.log
vt: /app/easybuild/software/cURL/7.49.1-foss-2016b/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by vt)
```


and in snps.log: 
```
### bcftools view --include 'FMT/GT="1/1" && QUAL>=100 && FMT/DP>=10 && (FMT/AO)/(FMT/DP)>=0' snps.raw.vcf  | vt normalize -r reference/ref.fa - | bcftools annotate --remove '^INFO/TYPE,^INFO/DP,^INFO/RO,^INFO/AO,^INFO/AB,^FORMAT/GT,^FORMAT/DP,^FORMAT/RO,^FORMAT/AO,^FORMAT/QR,^FORMAT/QA,^FORMAT/GL' > snps.filt.vcf

Failed to open -: unknown file type
```

**Comment by tseemann** [comment]
Your bcftools is too old.  Ideally want 1.10.2
