### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by idolawoye** [tseemann/snippy#261]
I am trying to install snippy on the Anaconda environment using `conda install -c conda-forge -c bioconda snippy` and after installation I am having the version 3.1 and not the recent version. Is there any reason why this is happening?
I am running a Linux Mint 19 Cinnamon.
Thanks

**Comment by rpetit3** [comment]
Hi @idolawoye! You may have fixed this by now! But, I wonder if you were to get the same error if you created a new environment for snippy. There may be a program already installed, forcing snippy v3.1 during the solving environment step.

`conda create -n snippy -c conda-forge -c bioconda snippy`

**Comment by idolawoye** [comment]
Thanks a lot Robert, I'll keep that in mind next time.

**Comment by IdoBar** [comment]
I'm having similar issues, even after installing in a fresh environment.
This is the error message:
```
Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /export/home/s2978925/.pyenv/versions/miniconda-latest/envs/snippy/bin/../perl5 /export/home/s2978925/etc/tools/Trinity/HpcGridRunner-1.0.2/PerlLib /export/home/s2978925/etc/tools/SNP/vcftools/src/perl /export/home/s2978925/.pyenv/versions/miniconda-latest/lib/site_perl/5.26.2/x86_64-linux-thread-multi /export/home/s2978925/.pyenv/versions/miniconda-latest/lib/site_perl/5.26.2 /export/home/s2978925/.pyenv/versions/miniconda-latest/lib/5.26.2/x86_64-linux-thread-multi /export/home/s2978925/.pyenv/versions/miniconda-latest/lib/5.26.2 .) at /export/home/s2978925/.pyenv/versions/miniconda-latest/envs/snippy/bin/snippy line 16.
BEGIN failed--compilation aborted at /export/home/s2978925/.pyenv/versions/miniconda-latest/envs/snippy/bin/snippy line 16.
```
I looked at the log files and it seems that the issue is with the encoding on line 10 of `t/test_non_ascii.t` in `XML::DOM::XPath`, which uses `encoding.pm` that is no longer supported after Perl 5.25.3 (see this [SO thread](https://stackoverflow.com/a/51696052/5346827))

Couldn't find a solution yet

**Comment by tseemann** [comment]
I have changed the conda channel order in the instructions.
