### ISSUE TITLE
Snippy-core insists on a reference. 

### ISSUE THREAD

**Issue by happykhan** [tseemann/snippy#262]
Running snippy 4.3.6 installed via conda

snippy-core insists on a --ref  (reference) although I don't see why. 

```
(base) (.venv) [galaxy@head-galaxy __snippy@4.3.6]$ bin/snippy-core  folder1    folder2  folder3 
This is snippy-core 4.3.6
Obtained from http://github.com/tseemann/snippy
Enabling bundled tools.
Found any2fasta - /export/tool_deps/_conda/envs/__snippy@4.3.6/binaries/noarch/any2fasta
Found samtools - /export/tool_deps/_conda/bin/samtools
Found minimap2 - /export/tool_deps/_conda/bin/minimap2
Found bedtools - /export/tool_deps/_conda/bin/bedtools
Found snp-sites - /export/tool_deps/_conda/bin/snp-sites
ERROR: Please provide --ref FASTA/GENBANK

```

**Comment by dfornika** [comment]
see: https://github.com/tseemann/snippy/issues/243

**Comment by tseemann** [comment]
@happykhan The VCF files are insufficient to reconstruct the reference and determine core sites, as I use varant-only VCF plus `snps.aligned.fa` for coverage information. This is much faster than generating VCF files with 5M rows. I need to learn how to use gVCF properly.
