### ISSUE TITLE
snippy-multi .sh has wrong snippy-core --ref

### ISSUE THREAD

**Issue by eam12** [tseemann/snippy#263]
I've been using `snippy-multi` to generate the output script, `runme.sh`. Looking at `runme.sh`, I noticed that the `snippy-core` script at the end has the wrong `--ref` defined. Instead of using the reference fasta I defined with the `snippy-multi --ref` flag, `snippy-core` lists the first sample in the tab separated input file as the reference. Interestingly, it looks like the _correct_ reference file is being used when `snippy-multi`/`snippy-core` runs, but the `runme.sh` file is confusingly wrong. Perhaps I'm missing something? Below is a small example:

`cat input_samples.tab`
sample1	sample1_trim_R1_paired.fastq.gz	sample1_trim_R2_paired.fastq.gz
sample2	sample2_trim_R1_paired.fastq.gz	sample2_trim_R2_paired.fastq.gz
sample3	sample3_trim_R1_paired.fastq.gz	sample3_trim_R2_paired.fastq.gz

`snippy-multi input_samples.tab --ref reference.fasta > snippy_multi.sh`

`cat snippy_multi.sh`
snippy --outdir 'sample1' --R1 'sample1_trim_R1_paired.fastq.gz' --R2 'sample1_trim_R2_paired.fastq.gz' --ref reference.fasta
snippy --outdir 'sample2' --R1 'sample2_trim_R1_paired.fastq.gz' --R2 'sample2_trim_R2_paired.fastq.gz' --ref reference.fasta
snippy --outdir 'sample3' --R1 'sample3_trim_R1_paired.fastq.gz' --R2 'sample3_trim_R2_paired.fastq.gz' --ref reference.fasta
snippy-core --ref 'sample1/ref.fa' sample1 sample2 sample3

`sh ./snippy_multi.sh`

`cat core.txt`
ID	LENGTH	ALIGNED	UNALIGNED	VARIANT	HET	MASKED	LOWCOV
sample1	4616416	4550945	26943	656	311	0	38217
sample2	4616416	4559071	33021	652	313	0	24011
sample3	4616416	4561979	26924	629	268	0	27245
Reference	4616416	4616416	0	0	0	0	0

**Comment by sbridel** [comment]
It's a little bit tricky.
When you run _snippy_ on a genome A against the REF genome, 
it creates A folder containing (copy/pasta) the REF genome in it.
This is to ensure (if you forgot) to retrieve which reference was used for generating A folder

**Comment by eam12** [comment]
That makes perfect sense. Thank you!
