### ISSUE TITLE
BEGIN failed--compilation aborted at ./snippy-core line 7.

### ISSUE THREAD

**Issue by BioinformaticaUSFQ** [tseemann/snippy#264]
Please I need help. 
I need to run snippy-core, but this was the error:
BEGIN failed--compilation aborted at ./snippy-core line 7.

My command was: ./snippy-core --ref /home/bioinformatica/C_Bioinformatica/Lazaro_Lactobacillus/Glr1_annotated/PROKKA_01172019.gbk /home/bioinformatica/C_Bioinformatica/Lazaro_Lactobacillus/snippyGlr1_3_24012019 /home/bioinformatica/C_Bioinformatica/Lazaro_Lactobacillus/Snippy_Fas23_18012019 

Version of snippy: snippy 4.3.6
Thanks for your help!

Regards

Belén

**Comment by BioinformaticaUSFQ** [comment]
And also I has this error 
Creating TSV file: core.txt
Running: snp-sites -c -o core.aln core.full.aln
Warning: No SNPs were detected so there is nothing to output.
ERROR: Could not run: snp-sites -c -o core.aln core.full.aln

**Comment by tseemann** [comment]
Can you post the *full* error after/before `BEGIN failed--compilation aborted at ./snippy-core line 7.` ?

**Comment by ankeetkumar** [comment]
I downloaded snippy using this command 

cd $HOME
git clone https://github.com/tseemann/snippy.git

snippy/bin/snippy --version
Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /home/i/snippy/bin/../perl5 /home/i/perl5/lib/perl5/5.30.0/x86_64-linux-gnu-thread-multi /home/i/perl5/lib/perl5/5.30.0 /home/i/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/ianke/perl5/lib/perl5 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at snippy/bin/snippy line 17.
BEGIN failed--compilation aborted at snippy/bin/snippy line 17.


Could you help me?
