### ISSUE TITLE
Errors when SNPs hidden in 'complex' variants

### ISSUE THREAD

**Issue by tseemann** [tseemann/snippy#27]
Because we are not joint-calling, we can get variant sites from different isolates which have different SNP types. eg. position 344421 could be 'snp' in isolate1, 'mnp' in 2, and 'complex' in 3 !

We are ignoring 'complex' types.  Need to take them into consideration so we don't get false matches to reference!

**Comment by flashton2003** [comment]
Hey Torst,

Is this issue fixed in the version of snippy on climb? Pretty sure it isn't, I'm getting reference calls for 'complex' variants. I can't find the git commit that is installed on climb.

Ta,

Phil

**Comment by tseemann** [comment]
@flashton2003 I don't know what is installed on CLIMB. Might be an old GVL image. Can you log in as `ubuntu` and type `brew reinstall snippy --HEAD` ?
