### ISSUE TITLE
samtools sort could not allocate memory for bam_mem

### ISSUE THREAD

**Issue by bearnomore** [tseemann/snippy#271]
First time trying snippy for variant calling of my bacterial genome. I passed the following command:

`snippy --outdir mysnps --ref myref.fasta --pe1 R1.fq.gz --pe2 R2.fq.gz`

It seems I have all the required packages/tools but the mission stopped at mapping using the bwa mem, and said the samtools sort could not allocate memory for bam_mem. The command that has executed by the snippy is:

`bwa mem  -v 2 -M -R '@RG   ID:snps SM:snps'  -t 8 reference/ref.fa  /media/sf_Ubuntu/Snippy/Test/R1.fq.gz  /media/sf_Ubuntu/Snippy/Test/R2.fq.gz | samtools view -@ 8 -F 3844 -q 60 -S -b -u -T reference/ref.fa - | samtools sort -O bam -o snps.bam -@ 8 -
`
The above followed by the following error message:

> [E::bwa_set_rg] the read group line contained literal <tab> characters -- replace with escaped tabs: \t
samtools sort: couldn't allocate memory for bam_mem 

It seems the reads didn't even get mapped to the ref genome. 

Please help.

Thanks!

Ye

**Comment by tseemann** [comment]
You seem to be using an old 3.x version of Snippy. This version has many serious bugs. You should move to version 4.x immediately.

The`set_rg` error was also fixed a long time ago.

**Comment by bearnomore** [comment]
Thanks for your reply. Yes, I'm using 3x version (downloaded from
bioconda). I'll move to the 4x version.

Ye

Torsten Seemann <notifications@github.com> 于2019年2月19日周二 下午5:10写道：
