### ISSUE TITLE
Set a tmp for snippy-core

### ISSUE THREAD

**Issue by Nilad** [tseemann/snippy#273]
Hi,

Can it possible to set a tmp directory for snippy-core
 like in snippy `--tmpdir F       Fast temporary storage eg. local SSD (default '/tmp')` ?

I run a snippy-core with 301 snippy folder and it's took more than my 8Go of /tmp space...

Thanks in advance.

**Comment by tseemann** [comment]
@Nilad `snippy-core` does not use any temporary disk space as far as I can tell.

However, you can set the `TMPDIR` variable and it will be honoured by most Unix software.

eg. `export TMPDIR=/mnt/ssd` or `TMPDIR=/mnt/ssd snippy-core ....`
