### ISSUE TITLE
snippy-multi

### ISSUE THREAD

**Issue by Mpaljacar** [tseemann/snippy#275]
Hi, this is my first time trying to run snippy and I get the following error when I run snippy-multi: 
Bad ID: 
Nay help would be great
Cheers
Maria

**Comment by andersgs** [comment]
Hi Maria. Could you elaborate more? Could you provide a sample input file, the command you are trying to run, the version of Snippy you are running? Best. A.

**Comment by Mpaljacar** [comment]
This is the command line 
snippy-multi input.tab --ref NZ_CP011597.gb -cpus 16 > runme.sh
Snippy version: snippy 4.3.6
And attached you can find the input file
Thank you 
Cheers
María

[input.txt](https://github.com/tseemann/snippy/files/2995550/input.txt)

**Comment by andersgs** [comment]
My first guess is that the header (first) line of the input file is causing the issue. Either remove it or comment it out by putting a # at the very start of the line.

**Comment by tseemann** [comment]
Yes, please remove the first line, or put a `#` as the first character eg. `# ID`

**Comment by chaikhi-soumaya** [comment]
Sometimes, besides the line of the '#', there may be some empty lines that the program considers. When you finish writing on "input.tab", don't move to the next line. If you do, it will be considered as a line with an ID and paths, but it's empty, so you will get an error "Bad ID:".
