### ISSUE TITLE
samtools improperly gets an extra cpu

### ISSUE THREAD

**Issue by lskatz** [tseemann/snippy#276]
I noticed that with `--cpus 2`, I have a samtools command in my log, e.g.,

```samtools sort -O bam -o snps.bam -@ 2 -```

Which might be improper.  I believe that `-@` indicates how many _extra_ cpus are granted.

**Comment by andersgs** [comment]
That seems like it would be at odds with the documentation: http://www.htslib.org/doc/samtools.html

I would also argue that would be a very unconventional behaviour of a threads/cpus option that would likely cause a lot of confusion. 

If it is indeed behaving that way, it surely is a bug, no??

When I am back on my feet, I’ll have to try it out.

**Comment by tseemann** [comment]
```
  -@, --threads INT
               Number of additional threads to use [0]
```

Looks like you are correct. That is strange, i thought 1 thread was for reading so didn't use much CPU.

**Comment by tseemann** [comment]
```
+# -@ = _additional_ CPUs: https://github.com/tseemann/snippy/issues/276
+my $sort_cpus = max(1, min($cpus, 16)-1);
```
might work

**Comment by lskatz** [comment]
That might set it to a maximum of 15 though??

**Comment by tseemann** [comment]
Case 1: 
```
--cpus 8
min(8,16) = 8 
8-1 = 7
max(1,7) = 7
-@ = 7
```
Case 2:
```
--cpus 32
min(32,16) = 16 
16-1 = 15
max(1,15) = 15
```
I've found that using > 16 threads offers no advantage.

**Comment by tseemann** [comment]
@lskatz i think i messed up, but i will make up for my sin
