### ISSUE TITLE
snippy-multi can't read files 

### ISSUE THREAD

**Issue by sgl07007** [tseemann/snippy#279]
I am new to snippy and am trying to run snippy-multi with the following command: 

snippy-multi input_tab_test.txt --ref JKS2530_q7_canu_1.7.1_test.contigs.fasta --cpus 16 > runme.sh

I get the following error: 

Reading: input_tab_test.txt
'RROR: [JKS2554] unreadable file 'assemblies/JKS2554_unicycler_v4.8.assembly.fasta

I am not sure where I am going wrong. See attached tab file. I checked the fasta for each of my assemblies and they all start with the appropriate ">" and have no whitespace. 
[input_tab_test.txt](https://github.com/tseemann/snippy/files/3023364/input_tab_test.txt)

**Comment by tseemann** [comment]
You need the full path to the .fasta file. eg. `/home/sgl/assemblies/contigs.fasta`

**Comment by sgl07007** [comment]
I fixed the path but am still getting the same error. 

'RROR: [JKS2554] unreadable file '/home/sgoldstein/Documents/Paper_2/Assembly_fasta_files/assemblies/JKS2554_unicycler_v4.8.assembly.fasta
[input_tab_test.txt](https://github.com/tseemann/snippy/files/3044149/input_tab_test.txt)

**Comment by liaochenlanruo** [comment]
The same problem happens to me, full path does not make sense, please tell me how to fix that.
Thanks!

**Comment by om9055** [comment]
I've started getting this error with snippy-multi as well. It worked fine when I first used it a couple of weeks ago but now I'm getting this error. I'm using the full pathways to my files in my tab file and I've tried removing the file in question, as well, but it still returns the same error with the next file in the list.

My files are assembled contigs and begin:
>NODE_1_length_372054_cov_47.9586
GTTTAA... etc.

That shouldn't be an issue, I wouldn't have thought, but figured I'd mention it anyway. Any help would be hugely appreciated. Thanks.

**Comment by om9055** [comment]
Having done some fairly extensive testing, I've traced the problem (or my problem at least) to Excel. Fortunately, I used Snippy-multi in the past and it worked fine. I went back and used it with the same tab file before and again it worked fine. I then did some tinkering with the original file and the one that doesn't work and eventually traced the problem to Excel tab files. Opening my original tab file (the one that worked) in Excel and saving it as a tab delimited text file seems to change the nature of the tab or something. It also changes the file type to .txt but that's easily changed.

Changing it back to a .tab file yields a file which is, on the face of things, identical to the original, but one other them works in snippy-multi and the other one doesn't, for some reason (see files attached – I had to change them to .txt, as GitHub won't let you upload .tab files)

[snippy_multi_Phy_grp_A_test5.tab.txt](https://github.com/tseemann/snippy/files/3072966/snippy_multi_Phy_grp_A_test5.tab.txt)

[snippy_multi_Phy_grp_A_test6.tab.txt](https://github.com/tseemann/snippy/files/3072967/snippy_multi_Phy_grp_A_test6.tab.txt)

Code from the terminal showing that one works, and one does not:

(home) ubuntu@collab-1:~/projects/Oliver/All_cow_dog_UTI/Phy_grp_A_snippy_out$ snippy-multi snippy_multi_Phy_grp_A_test5.tab --ref /home/ubuntu/projects/Oliver/EC590_ST744_closed_sequence.fasta --mapqual 60 --mincov 10 --minfrac 0.8 --cpus 8 > Cow_dog_UTI_snippy_multi.sh
Reading: snippy_multi_Phy_grp_A_test5.tab
Generating output commands for 284 isolates
Done.
(home) ubuntu@collab-1:~/projects/Oliver/All_cow_dog_UTI/Phy_grp_A_snippy_out$ snippy-multi snippy_multi_Phy_grp_A_test6.tab --ref /home/ubuntu/projects/Oliver/EC590_ST744_closed_sequence.fasta --mapqual 60 --mincov 10 --minfrac 0.8 --cpus 8 > Cow_dog_UTI_snippy_multi.sh
Reading: snippy_multi_Phy_grp_A_test6.tab

I'm looking at a possible fix, now. Will reply again soon.

**Comment by om9055** [comment]
So, it seems, even if I just download the tab file, open it in Notepad and copy contents to another file and upload the new file, snippy-multi, for some reason, then gives the 'RROR: unreadable file' error when trying to read the new file. I had hoped that this might be fixable by changing the tabs in spaces then back into tabs but unfortunately, that doesn't appear to be the case.

**Comment by om9055** [comment]
I've come up with a fix that worked for me. I copied the text from my .tab file that was previously returning an error into MS Word and replaced the tabs with commas, using the find/replace function. I then copied that directly into a file in the Terminal, using Nano, and used sed to replace the commas with tabs:

`sed -e 's/,/\t/g' filewithcommas > file.tab`

This then, finally, produced a script file, without any errors. Halle-bloody-lujah!

This can probably be avoided if you just do everything in the terminal. Unfortunately, I had trouble generating the file paths and combining them with the file names (I'm fairly new to Bash).

**Comment by AlnMetTyr** [comment]
Was wondering if there was a fix for this yet? Correct full path to each file and no luck

(/home/vaughana/conda-envs/roary) iramohio-01$ snippy-multi pathsfasta.txt --ref"/home/vaughana/chromosomes_entomophila/626.fasta"
Reading: pathsfasta.txt
'RROR: [477] unreadable file '/home/vaughana/chromosomes_entomophila/477.fasta

**Comment by tseemann** [comment]
There was a bug fix in May, and is in Prokka 1.14 - does that work?

commit ffefb2bf8a5c83fc59a30b8a82a8ff36d6d10042
Author: Sara Monzón <sara.monzon.fdz@gmail.com>
Date:   Fri May 31 14:05:04 2019 +0200

    Minimum fix. unreadable error points to r1 file for both r1 and r2

**Comment by tseemann** [comment]
I would also run `dos2unix` and `mac2unix` on the files to ensure the line endings are good.

**Comment by emrosenthal17** [comment]
Hello, I'm encountering this problem today and the above solutions are not working for me. I've tried several strategies of creating the tab file, including om9055's suggestion to make the csv file in MS Word and convert to tab using sed, as well as manually writing the input file using nano in terminal. I was thinking the issue could be with recognizing the full path, but working both on my local cpu and in a supercomputer, the path seems to be found properly but the file is still unreadable. I've also run the --check on snippy and see the dependencies are installed. Any further suggestions for this issue? Thanks!

running the command: 
$ snippy-multi input-test7.tab 
Reading: input-test7.tab
ERROR: [BS0336] unreadable file '/storage/home/err5/scratch/0336_S1_L001_R1_001_paired.fastq'

**Comment by Batstaph** [comment]
Hi,  I had this problem yesterday. I usually make my input list file using a bash one-liner, but made the file yesterday in libre-office calc instead. I opened the file in a text editor and traced the problem to an extra (invisible) tab at the end of some of the lines. I removed the tabs and it worked fine.

**Comment by tseemann** [comment]
@Batstaph if you have extra columns they will be ignored. that shouldn't be the problem. i split each line on tab chars and only pull the first 3 columns.  

you can use `cat -vet input.tab` to show TABs at `^I` etc.

also `od -a input.tab | less` will show `ht` and `nl` chars. if you see `cr` or `sp` that's bad.

**Comment by qingbo11** [comment]
Hello Dr. Seemann

Thank you for your effort. I am using snippy-multi line as suggested, and had the problem of file reading as shown below. Please see if there is a way of generating the correct format of input.tab when using paired fastq files.
 
Reading: input.tab
ERROR: [SRR069978,C:/Qingbo/snippy/fastq/SRR069978_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR069978_R2.fastq.gz_] missing read/contig data: SRR069978,C:/Qingbo/snippy/fastq/SRR069978_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR069978_R2.fastq.gz
sh-5.0# cat -vet input.tab
SRR069978,C:/Qingbo/snippy/fastq/SRR069978_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR069978_R2.fastq.gz^M$
SRR067479,C:/Qingbo/snippy/fastq/SRR067479_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067479_R2.fastq.gz^M$
SRR069918,C:/Qingbo/snippy/fastq/SRR069918_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR069918_R2.fastq.gz^M$
SRR069940,C:/Qingbo/snippy/fastq/SRR069940_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR069940_R2.fastq.gz^M$
SRR067500,C:/Qingbo/snippy/fastq/SRR067500_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067500_R2.fastq.gz^M$
SRR067534,C:/Qingbo/snippy/fastq/SRR067534_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067534_R2.fastq.gz^M$
SRR069929,C:/Qingbo/snippy/fastq/SRR069929_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR069929_R2.fastq.gz^M$
SRR067482,C:/Qingbo/snippy/fastq/SRR067482_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067482_R2.fastq.gz^M$
SRR069931,C:/Qingbo/snippy/fastq/SRR069931_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR069931_R2.fastq.gz^M$
SRR069927,C:/Qingbo/snippy/fastq/SRR069927_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR069927_R2.fastq.gz^M$
SRR067499,C:/Qingbo/snippy/fastq/SRR067499_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067499_R2.fastq.gz^M$
SRR067507,C:/Qingbo/snippy/fastq/SRR067507_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067507_R2.fastq.gz^M$
SRR067551,C:/Qingbo/snippy/fastq/SRR067551_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067551_R2.fastq.gz^M$
SRR069939,C:/Qingbo/snippy/fastq/SRR069939_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR069939_R2.fastq.gz^M$
SRR067527,C:/Qingbo/snippy/fastq/SRR067527_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067527_R2.fastq.gz^M$
SRR067480,C:/Qingbo/snippy/fastq/SRR067480_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067480_R2.fastq.gz^M$
SRR067557,C:/Qingbo/snippy/fastq/SRR067557_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067557_R2.fastq.gz^M$
SRR067529,C:/Qingbo/snippy/fastq/SRR067529_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067529_R2.fastq.gz^M$
SRR069959,C:/Qingbo/snippy/fastq/SRR069959_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR069959_R2.fastq.gz^M$
SRR067537,C:/Qingbo/snippy/fastq/SRR067537_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067537_R2.fastq.gz^M$
SRR067543,C:/Qingbo/snippy/fastq/SRR067543_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067543_R2.fastq.gz^M$
SRR069968,C:/Qingbo/snippy/fastq/SRR069968_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR069968_R2.fastq.gz^M$
SRR067494,C:/Qingbo/snippy/fastq/SRR067494_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067494_R2.fastq.gz^M$
SRR067541,C:/Qingbo/snippy/fastq/SRR067541_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067541_R2.fastq.gz^M$
SRR067484,C:/Qingbo/snippy/fastq/SRR067484_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067484_R2.fastq.gz^M$
SRR067512,C:/Qingbo/snippy/fastq/SRR067512_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067512_R2.fastq.gz^M$
SRR067505,C:/Qingbo/snippy/fastq/SRR067505_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067505_R2.fastq.gz^M$
SRR067518,C:/Qingbo/snippy/fastq/SRR067518_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067518_R2.fastq.gz^M$
SRR067467,C:/Qingbo/snippy/fastq/SRR067467_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067467_R2.fastq.gz^M$
SRR069914,C:/Qingbo/snippy/fastq/SRR069914_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR069914_R2.fastq.gz^M$
SRR067474,C:/Qingbo/snippy/fastq/SRR067474_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067474_R2.fastq.gz^M$
SRR067496,C:/Qingbo/snippy/fastq/SRR067496_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067496_R2.fastq.gz^M$
SRR067472,C:/Qingbo/snippy/fastq/SRR067472_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067472_R2.fastq.gz^M$
SRR067513,C:/Qingbo/snippy/fastq/SRR067513_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067513_R2.fastq.gz^M$
SRR067517,C:/Qingbo/snippy/fastq/SRR067517_R1.fastq.gz,C:/Qingbo/snippy/fastq/SRR067517_R2.fastq.gz^M$
0000000   S   R   R   0   6   9   9   7   8   ,   C   :   /   Q   i   n
0000020   g   b   o   /   s   n   i   p   p   y   /   f   a   s   t   q
0000040   /   S   R   R   0   6   9   9   7   8   _   R   1   .   f   a
0000060   s   t   q   .   g   z   ,   C   :   /   Q   i   n   g   b   o
0000100   /   s   n   i   p   p   y   /   f   a   s   t   q   /   S   R
0000120   R   0   6   9   9   7   8   _   R   2   .   f   a   s   t   q
0000140   .   g   z  cr  nl   S   R   R   0   6   7   4   7   9   ,   C
0000160   :   /   Q   i   n   g   b   o   /   s   n   i   p   p   y   /
0000200   f   a   s   t   q   /   S   R   R   0   6   7   4   7   9   _
0000220   R   1   .   f   a   s   t   q   .   g   z   ,   C   :   /   Q
0000240   i   n   g   b   o   /   s   n   i   p   p   y   /   f   a   s
0000260   t   q   /   S   R   R   0   6   7   4   7   9   _   R   2   .
0000300   f   a   s   t   q   .   g   z  cr  nl   S   R   R   0   6   9
0000320   9   1   8   ,   C   :   /   Q   i   n   g   b   o   /   s   n
0000340   i   p   p   y   /   f   a   s   t   q   /   S   R   R   0   6
0000360   9   9   1   8   _   R   1   .   f   a   s   t   q   .   g   z
0000400   ,   C   :   /   Q   i   n   g   b   o   /   s   n   i   p   p
0000420   y   /   f   a   s   t   q   /   S   R   R   0   6   9   9   1
0000440   8   _   R   2   .   f   a   s   t   q   .   g   z  cr  nl   S
0000460   R   R   0   6   9   9   4   0   ,   C   :   /   Q   i   n   g
0000500   b   o   /   s   n   i   p   p   y   /   f   a   s   t   q   /
0000520   S   R   R   0   6   9   9   4   0   _   R   1   .   f   a   s
0000540   t   q   .   g   z   ,   C   :   /   Q   i   n   g   b   o   /
0000560   s   n   i   p   p   y   /   f   a   s   t   q   /   S   R   R
0000600   0   6   9   9   4   0   _   R   2   .   f   a   s   t   q   .
0000620   g   z  cr  nl   S   R   R   0   6   7   5   0   0   ,   C   :
0000640   /   Q   i   n   g   b   o   /   s   n   i   p   p   y   /   f
0000660   a   s   t   q   /   S   R   R   0   6   7   5   0   0   _   R
0000700   1   .   f   a   s   t   q   .   g   z   ,   C   :   /   Q   i
0000720   n   g   b   o   /   s   n   i   p   p   y   /   f   a   s   t
standard input  

Best regards,

Qingbo

**Comment by sshirsat2020** [comment]
For Mac: I copied my tab file into Word and backspaced the tabs (which didn't turn out to be tabs) and replaced with tabs (by clicking the tab key). I copied all the text in the word file and pasted it into a Text/Edit file which I saved as .tab and this ended up working for me.

**Comment by Marius101** [comment]
This is still a persistent error and all above mentioned fixes have not worked, it worked one after using dos2unix, but running the exact same command using the exact same input file later on the same terminal produced the same error.

**Comment by Arthurdyu** [comment]
我遇到了同样的问题，我用键盘的tab键敲出来的似乎不是制表符，所以我先用了逗号，然后用Linux命令将逗号替换成制表符，问题终于解决了，哭死！
