### ISSUE TITLE
snippy-core "No SNPs were detected"

### ISSUE THREAD

**Issue by eam12** [tseemann/snippy#280]
I have been running `snippy-core` for months with no problems. However, with the new data set I started using today, I'm getting the following warning and error:

> Warning: No SNPs were detected so there is nothing to output.
> ERROR: Could not run: snp-sites -c -o core.aln core.full.aln

All 45 of my _snps.tab_ files have variants listed (between 200 and 20,000). I do get all of the `snippy-core` output files minus the output file _core.aln_ from `snp-sites`. Additionally, the _core.tab_ is empty and in _core.txt_ only about the first 1/4 of samples listed have counts >0 in the VARIANT column. I am totally at a loss as to what is going on here.

Snippy was installed using Bioconda: Snippy version 4.3.6 and snp-sites version 2.4.1. Below is my code and the entire output. Any help would be very much appreciated.

`snippy-core --ref GCF_003344465.1_ASM334446v1_genomic.fna --prefix core RS*_snippy`

> This is snippy-core 4.3.6
> Obtained from http://github.com/tseemann/snippy
> Enabling bundled tools.
> Found any2fasta - /panfs/roc/groups/1/johnsont/millere/.conda/envs/snippy/binaries/noarch/any2fasta
> Found samtools - /home/johnsont/millere/.conda/envs/snippy/bin/samtools
> Found minimap2 - /home/johnsont/millere/.conda/envs/snippy/bin/minimap2
> Found bedtools - /home/johnsont/millere/.conda/envs/snippy/bin/bedtools
> Found snp-sites - /home/johnsont/millere/.conda/envs/snippy/bin/snp-sites
> Saving reference FASTA: core.ref.fa
> This is any2fasta 0.4.2
> Opening 'GCF_003344465.1_ASM334446v1_genomic.fna'
> Detected FASTA format
> Read 63041 lines from 'GCF_003344465.1_ASM334446v1_genomic.fna'
> Wrote 6 sequences from FASTA file.
> Processed 1 files.
> Done.
> Loaded 6 sequences totalling 5042521 bp.
> Will mask 0 regions totalling 0 bp ~ 0.00%
> 0	RS775_S1_snippy	snp=514	del=30	ins=15	het=47	unaligned=103286
> 1	RS776_S2_snippy	snp=7709	del=61	ins=32	het=25	unaligned=4160628
> 2	RS777_S3_snippy	snp=490	del=29	ins=14	het=22	unaligned=109762
> 3	RS778_S4_snippy	snp=506	del=43	ins=5	het=16	unaligned=114017
> 4	RS779_S5_snippy	snp=542	del=45	ins=15	het=57	unaligned=92868
> 5	RS780_S6_snippy	snp=481	del=24	ins=5	het=18	unaligned=127453
> 6	RS781_S7_snippy	snp=463	del=18	ins=15	het=37	unaligned=122072
> 7	RS782_S8_snippy	snp=5110	del=30	ins=23	het=15	unaligned=4199463
> 8	RS783_S9_snippy	snp=9624	del=52	ins=38	het=77	unaligned=1142005
> 9	RS784_S10_snippy	snp=11605	del=100	ins=45	het=88	unaligned=1160033
> 10	RS785_S11_snippy	snp=13734	del=54	ins=67	het=91	unaligned=4112515
> 11	RS786_S12_snippy	snp=8188	del=40	ins=55	het=11	unaligned=4158363
> 12	RS787_S13_snippy	snp=489	del=42	ins=5	het=74	unaligned=110907
> 13	RS788_S14_snippy	snp=487	del=27	ins=14	het=37	unaligned=106314
> 14	RS789_S15_snippy	snp=484	del=25	ins=15	het=13	unaligned=122179
> 15	RS790_S16_snippy	snp=503	del=49	ins=5	het=60	unaligned=104724
> 16	RS791_S17_snippy	snp=517	del=25	ins=5	het=26	unaligned=109372
> 17	RS792_S18_snippy	snp=498	del=40	ins=5	het=23	unaligned=107839
> 18	RS793_S19_snippy	snp=526	del=25	ins=15	het=88	unaligned=107489
> 19	RS794_S20_snippy	snp=511	del=39	ins=5	het=28	unaligned=112726
> 20	RS795_S21_snippy	snp=486	del=25	ins=4	het=56	unaligned=107964
> 21	RS796_S22_snippy	snp=7203	del=33	ins=44	het=5511	unaligned=2398124
> 22	RS797_S23_snippy	snp=6437	del=17	ins=20	het=115	unaligned=4141658
> 23	RS798_S24_snippy	snp=494	del=25	ins=5	het=14	unaligned=114275
> 24	RS799_S25_snippy	snp=489	del=43	ins=5	het=5	unaligned=114279
> 25	RS800_S26_snippy	snp=550	del=45	ins=15	het=73	unaligned=99047
> 26	RS801_S27_snippy	snp=540	del=45	ins=15	het=22	unaligned=104577
> 27	RS802_S28_snippy	snp=526	del=30	ins=17	het=34	unaligned=139526
> 28	RS803_S29_snippy	snp=488	del=46	ins=15	het=33	unaligned=107619
> 29	RS804_S30_snippy	snp=543	del=41	ins=8	het=117	unaligned=127738
> 30	RS805_S31_snippy	snp=566	del=46	ins=16	het=157	unaligned=89592
> 31	RS806_S32_snippy	snp=505	del=24	ins=15	het=85	unaligned=96192
> 32	RS807_S33_snippy	snp=8505	del=44	ins=62	het=95	unaligned=4133264
> 33	RS808_S34_snippy	snp=14284	del=68	ins=59	het=71	unaligned=4089801
> 34	RS809_S35_snippy	snp=504	del=44	ins=4	het=48	unaligned=102777
> 35	RS810_S36_snippy	snp=465	del=39	ins=5	het=27	unaligned=121538
> 36	RS811_S37_snippy	snp=532	del=46	ins=6	het=25	unaligned=95703
> 37	RS812_S38_snippy	snp=483	del=25	ins=5	het=0	unaligned=140587
> 38	RS813_S39_snippy	snp=531	del=40	ins=7	het=22	unaligned=140048
> 39	RS814_S40_snippy	snp=434	del=23	ins=4	het=33	unaligned=170791
> 40	RS815_S41_snippy	snp=492	del=17	ins=6	het=23	unaligned=146678
> 41	RS816_S42_snippy	snp=30563	del=197	ins=161	het=67	unaligned=4006634
> 42	RS817_S43_snippy	snp=6751	del=23	ins=20	het=25	unaligned=4159698
> 43	RS818_S44_snippy	snp=8497	del=40	ins=48	het=26	unaligned=4153394
> 44	RS819_S45_snippy	snp=7078	del=39	ins=54	het=24	unaligned=4158072
> Opening: core.tab
> Opening: core.vcf
> Processing contig: NZ_CP030111.1
> Processing contig: NZ_CP030112.1
> Processing contig: NZ_CP030113.1
> Processing contig: NZ_CP030114.1
> Processing contig: NZ_CP030115.1
> Processing contig: NZ_CP030116.1
> Generating core.full.aln
> Creating TSV file: core.txt
> Running: snp-sites -c -o core.aln core.full.aln
> Warning: No SNPs were detected so there is nothing to output.
> ERROR: Could not run: snp-sites -c -o core.aln core.full.aln

**Comment by tseemann** [comment]
You have lots of samples where `unaligned` is > 4,000,000 bp, and your reference is an E.coli with 5,042,521 bp.
These samples must not be similar to the reference, and hence have mostly zero coverage (or you have < 10x depth of sequencing)
This means your core genome will be zero, and snippy only uses *core* sites.
Try removing all the outlier sequences with unaligned > 200.000 bp.

**Comment by eam12** [comment]
I see that now. My apologies!
