### ISSUE TITLE
snippy fails at freebayes-parallel 

### ISSUE THREAD

**Issue by fmobegi** [tseemann/snippy#281]
Hi Torsten,
Am trying to run snippy to target sites on th E.coli K12 reference. However, the pipeline keeps failing at the freebayes step with this error:
""### freebayes-parallel reference/ref.txt 4 -p 2 -P 0.5 -q 13 -m 60 --min-repeat-entropy 1.0-t 'ecoli_amr.bed' -f reference/ref.fa snps.bam > snps.raw.vcf
could not parse --min-repeat-entropy""
From first glance, I think it's because of a missing space at << --min-repeat-entropy 1.0-t>> but am not sure. Perhaps it is something you could help me with?
My command is: ""snippy --cpu 4 --targets ecoli_amr.bed --outdir snippy_AMR/28D10/ --ref Escherichia_coli_k12_MG1655.gbff --R1 fastq_files/28D10_R1.fastq.gz --R2 fastq_files/28D10_R2.fastq.gz"" also tried "snippy --cpu 4 --targets ecoli_amr.bed --outdir snippy_AMR/28D10/ --ref Escherichia_coli_k12_MG1655.gbff --ctgs 28D10_contigs.fna"
the reference is "wget -O  Escherichia_coli_k12_MG1655.gbff.gz ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/005/845/GCA_000005845.2_ASM584v2/GCA_000005845.2_ASM584v2_genomic.gbff.gz"

Thanks,
Fredrick 
[ecoli_amr.bed.txt](https://github.com/tseemann/snippy/files/3046369/ecoli_amr.bed.txt)
[28D10_contigs.fna.txt](https://github.com/tseemann/snippy/files/3046370/28D10_contigs.fna.txt)

**Comment by tseemann** [comment]
Yes, you have found a bug. There is a missing space in the code. Clearly no one has ever used this feature until now. I have fixed in 4.3.8, but you might just want to patch it yourself.

**Comment by fmobegi** [comment]
Thanks mate.
