### ISSUE TITLE
maximum number of contigs for snippy-multi

### ISSUE THREAD

**Issue by pneumowidow** [tseemann/snippy#282]
Hello,

I was wondering if perhaps there's a limit on the number of isolates for snippy-multi to generate core snps. The maximum I've been able to analyze at one is 6 contigs. Anything more than that and it says it can't generate core snps. Is 6 the limit?

Thank you

**Comment by tseemann** [comment]
There is no limit to how many isolates you can use.

However, if one of your isolates is too distant from the reference, so most of its reads will not align to the reference, and hence the core will become zero or empty.

Please provide the whole output of `snippy-core` if you need more help.

**Comment by pneumowidow** [comment]
Sorry I actually forgot to reply to this. One of the draft assemblies was incorrect and once I removed it, the rest assembled well. Thanks for the reply.
