### ISSUE TITLE
SNP filtering in snippy-core

### ISSUE THREAD

**Issue by ElainW** [tseemann/snippy#284]
![AC dist default snippy](https://user-images.githubusercontent.com/50131630/56944163-57d84f80-6af0-11e9-9448-3bd9f4a668ec.png)
![AC dist no snippy](https://user-images.githubusercontent.com/50131630/56944164-59097c80-6af0-11e9-9e8f-d0652a8fb0df.png)
I wonder if there's any filtering of the SNPs (besides getting rid of all the indels and complex variants) when snippy-core generates core.vcf and core.full.aln? Shown above are the distributions of allele counts of SNPs after snippy-core and of allele counts of SNPs by unique positions (which is likely a lower estimate of unique # snps called in all the samples merged in snippy-core, due to the presence of multiallelic snps).
Thank you in advance!

**Comment by tseemann** [comment]
Snippy-core only includes SNPs that are in ALL the samples ie. the "core" SNPs.   It also breaks up compound SNPs into single SNP entries in the VCF.    So core SNPs is always <= all SNPs.   

I think I need more explanation of what you mean.
