### ISSUE TITLE
“n” character in *.tab generated by snippy-core

### ISSUE THREAD

**Issue by zhaoxvwahaha** [tseemann/snippy#285]
Hi, 
I have some questions when using snippy, could you please help me?
(1) Why there are "n" character in .tab generated by snippy-core?
A "core site" is a genomic position that is present in all the samples, what means "present"? It  include [ATCGn], or others, such as "N"," -"? 
(2) About the filter process
I could got the following 4 *.vcf files, I'm not sure about the filter process for each of vcf:
 snps.raw.vcf snps.filt.vcf  snps.subs.vcf  snps.vcf
a) the raw.vcf is under the parameters (--mapqual --basequal...) ?
b) the filt.vcf was filtered by Freebayes with parameters : --mincov and --minfrac ?
c) .vcf should add the annotation for filt.vcf ?
d) what about the subs.vcf?
Thanks in advance!

**Comment by tseemann** [comment]
(1) Read https://github.com/tseemann/snippy/blob/master/README.md#why-is-corefullaln-an-alphabet-soup

**Comment by tseemann** [comment]
(2) Please look at `snps.log` first to see all the commands that were run
