### ISSUE TITLE
Not getting the complete files

### ISSUE THREAD

**Issue by jotes35** [tseemann/snippy#286]
When I run snippy , instead of the 16 files specified i get 9 files. I am using snippy version  4.3.6

**Comment by jotes35** [comment]
Below is the detail
Files: ref.fa ,snps.bam.bai ,snps.log ,snps.vcf , ref.fa.fai, snps.bam ,snps. filt.vcf ,sps.raw.vcf
Folder: reference

**Comment by tseemann** [comment]
Please paste the contents of `snps.log` here please.

**Comment by kusonahikari** [comment]
Hi Torsten, I also encounter the same issue. 
When I ran the snippy with .gbk ref I got this issue. Below is the log file. However, when ran snippy with .fna ref file, snippy worked fine.

`### cd /home/ubuntu/data

### /home/ubuntu/miniconda3/bin/snippy --cpus 4 --prefix snippy_02 --ref Pseudomonas_aeruginosa_PA01.gbk --R1 pseudomonas/02_S1_L001_R1_001.fastq.gz --R2 pseudomonas/02_S1_L001_R2_001.fastq.gz --outdir 02_snippy

### samtools faidx reference/ref.fa


### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.06 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 3.31 seconds elapse.
[bwa_index] Update BWT... 0.04 sec
[bwa_index] Pack forward-only FASTA... 0.04 sec
[bwa_index] Construct SA from BWT and Occ... 0.95 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index reference/ref.fa
[main] Real time: 4.577 sec; CPU: 4.396 sec

### mkdir -p reference/genomes && cp -f reference/ref.fa reference/genomes/ref.fa


### ln -sf reference/ref.fa .


### ln -sf reference/ref.fa.fai .


### mkdir -p reference/ref && gzip -c reference/ref.gff > reference/ref/genes.gff.gz


### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

WARNING: All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate.

### bwa mem  -Y -M -R '@RG\tID:02_snippy\tSM:02_snippy' -t 4 reference/ref.fa /home/ubuntu/data/pseudomonas/02_S1_L001_R1_001.fastq.gz /home/ubuntu/data/pseudomonas/02_S1_L001_R2_001.fastq.gz | samclip --max 10 --ref reference/ref.fa.fai | samtools sort -n -l 0 -T /tmp/snippy.4573. --threads 4 -m 2000M | samtools fixmate -m - - | samtools sort -l 0 -T /tmp/snippy.4573. --threads 4 -m 2000M | samtools markdup -T /tmp/snippy.4573. -r -s - - > snippy_02.bam

READ 1214377 WRITTEN 1187149
EXCLUDED 213036 EXAMINED 1001341
PAIRED 926082 SINGLE 75259
DULPICATE PAIR 4812 DUPLICATE SINGLE 22416
DUPLICATE TOTAL 27228

### samtools index snippy_02.bam


### fasta_generate_regions.py reference/ref.fa.fai 909839 > reference/ref.txt


### freebayes-parallel reference/ref.txt 4 -p 2 -P 0 -C 10 --min-repeat-entropy 1.5 --strict-vcf -q 13 -m 60 --min-coverage 10 -F 0.05  -f reference/ref.fa snippy_02.bam > snippy_02.raw.vcf


### bcftools view --include 'FMT/GT="1/1" && QUAL>=100 && FMT/DP>=10 && (FMT/AO)/(FMT/DP)>=0' snippy_02.raw.vcf  | vt normalize -r reference/ref.fa - | bcftools annotate --remove '^INFO/TYPE,^INFO/DP,^INFO/RO,^INFO/AO,^INFO/AB,^FORMAT/GT,^FORMAT/DP,^FORMAT/RO,^FORMAT/AO,^FORMAT/QR,^FORMAT/QA,^FORMAT/GL' > snippy_02.filt.vcf


### snpEff ann -noLog -noStats -no-downstream -no-upstream -no-utr -t -c reference/snpeff.config -dataDir . ref snippy_02.filt.vcf > snippy_02.vcf`

**Comment by jotes35** [comment]
> Please paste the contents of `snps.log` here please.

Hi Torsten. The issue is resolved now. I had to change the reference file. Thanks

**Comment by tseemann** [comment]
Great news @jotes35
