### ISSUE TITLE
what the "." character in core.snp.nway.tab means

### ISSUE THREAD

**Issue by zhaoxvwahaha** [tseemann/snippy#288]
Hi,

I have 2 questions about the tab file generated by snippy-core, anyone could help me, thanks in advance
(1) what's the "." character in core.snp.nway.tab?
(2) How many kinds of characters will be included in the *.tab file generated by snippy-core at most? Are the following 9 charaters right:    [ATCGNn.X-] ?

Best Wishes

**Comment by tseemann** [comment]
(1) the `.` in `snps.nway.wab` is the same meaning as `.` in a VCF file. It means there is no allele at that position, that region of the reference genome is not in that sample.

(2) Lowercase `agct` is also included for variant sites.

**Comment by zhaoxvwahaha** [comment]
Hi tseemann,

Thank you for helpful reply, I checked the  documentation of vcf file, "." is a site that is called monomorphic reference (i.e. with no alternate alleles), that is to say, the "." means the sample has same base with the reference in this position, right?

**Comment by zhaoxvwahaha** [comment]
or, the "." means gap, i.e. no base can be aligned to reference in this position?

**Comment by tseemann** [comment]
It means "no base can be aligned to reference in this position?".

In the VCF sample column, I meant to say the `GT` (genotype) is `.` when there is no allele.

**Comment by zhaoxvwahaha** [comment]
Thank you so much tseemann, 
(1) I was confused because I used samtools rather than freebayes to call variants before, the "." character in column "ALT" means same base with reference, now I know that  the "." character by snippy (actually freebayes) means gap (no reads can be aligned to this position in my sample.)
(2) I noticed that there are also "-" character in "core.full.aln", which means zero coverage or a deletion relative to the reference, so the "-" character in core.full.aln is the "." character in core.snp.nway.tab ? And, if yes, there will be these chareacters [A T C G a t c g X n N -] rather than [A T C G a t c g X n N . - ] in core.snp.nway.tab ?

**Comment by zhaoxvwahaha** [comment]
Thank you so much tseemann,
(1) I was confused because the "." character in column "ALT" in vcf file means same base with reference. Now I know that the "." is from GT rather than "ALT" column, right?
(2) If "." means gap (no reads can aligned to the position in this sample) in core.snp.nway.tab, so this "." should be the "-" character which means zero coverage or a deletion relative to the reference in core.full.aln file ? if yes, so the core.snp.nway.tab will include these characters [A T C G a t c g X n . N] rather than [A T C G a t c g X n - N], right?
