### ISSUE TITLE
The position outside of snps.raw.vcf

### ISSUE THREAD

**Issue by zhaoxvwahaha** [tseemann/snippy#289]
Hi,

The snps.raw.vcf only include some reference position, but I need to know the situation of positions which don't be included in the vcf file. So I'm not sure, these positions don't be reported in vcf file are high-quality but same with reference base or  don't pass the freebayes cutoff, or both of them? How can I get a complete vcf file which include all reference position?

Thanks in advance.

**Comment by tseemann** [comment]
Instead of having a huge VCF file for every genome site, I use the `snps.vcf` and `snps.aligned.fa`. The information you want is in the `snps.aligned.fa` file.

See https://github.com/tseemann/snippy#output-files

```

.aligned.fa | A version of the reference but with - at position with depth=0 and N for 0 < depth < --mincov (does not have variants)
```
