### ISSUE TITLE
Snippy help for analyzing output

### ISSUE THREAD

**Issue by ramyag03** [tseemann/snippy#29]
Hi Seemann,

Greetings for the day!!!

I have just started using the snippy tool for finding snp's from a bacterial genome and i found it really awesome and very fast detection and annotation tool.

I have a few questions:

1) I have used a draft genome as a reference. How confident can i be of the snp's called and annotated?

2) Also this genome has been sequenced on Iontorrent platform. So they are single end reads. Is the tool suitable for this platform.?

3) There is a file called .depth.gz. is it the file that indicated the depth of coverage of snp's called? IS there any other file from which i can take the depth parameters to take into consideration the real snp's?

Thanks in advance,
Ramya.

**Comment by tseemann** [comment]
@ramyag03 

1. Snippy will find the SNPs between your read and the reference. If the reference is wrong, there is nothing we can do!

2. Ion Torrent should work ok. If it is very old PGM data then it might have trouble with false indels in the homopolymer erorrs it has. Just use the `--se reads.fastq` option.

3. Yes that file is the read depth at each position in the reference genome. The depth information is in the `snps.tab` report too in the EVIDENCE column.
