### ISSUE TITLE
why many site are - in my aligned fa file while it's coverage > mincov

### ISSUE THREAD

**Issue by wanyingsun** [tseemann/snippy#292]
Hi, Dr. tseemann, 
I set the mincov of 10 (others setting are default ) and the file depth.gz shows many sites are more than 60 , could you tell me why these many sites still - in my aligned file ? 
thank you .

**Comment by tseemann** [comment]
snps.depth.gz  is from Snippy 3.x which is deprecated and very buggy.
Please upgrade to Snippy 4.x using conda or brew.
