### ISSUE TITLE
Is it possible to provide more than one forward and one reverse read files for each sample?

### ISSUE THREAD

**Issue by IdoBar** [tseemann/snippy#298]
Hi @tseemann,

In the documentation for `snippy-multi` you provide an example of multiple read files for the same sample (Isolate1, Isolate1b, Isolate1c in this case):
```
# input.tab = ID R1 [R2]
Isolate1	/path/to/R1.fq.gz	/path/to/R2.fq.gz
Isolate1b	/path/to/R1.fastq.gz	/path/to/R2.fastq.gz
Isolate1c	/path/to/R1.fa		/path/to/R2.fa
```
However, running it this way, they will appear in the VCF as separate "samples". 
Is there a way to consolidate all the reads (without concatenating the files)?
Like the following:
```
# input.tab = ID R1 [R2]
Isolate1	/path/to/R1.fq.gz,/path/to/R1.fastq.gz,/path/to/R1.fa	/path/to/R2.fq.gz,/path/to/R2.fastq.gz,/path/to/R2.fa
```

If it's not possible or recommended, how would you suggest to make a "consensus" VCF column from the 3 replicates?

Thanks, Ido

**Comment by tseemann** [comment]
RE: https://github.com/tseemann/snippy#using-snippy-multi

That example is not meant to suggest they are the same isolate. It was to show that files could be in different formats. They are separate isolates.

There is no way to provide multiple read sets for a single isolate, and I will not be adding that fearure, sorry.

You could run snippy manually perhaps using the subshell feature of bash shell:
```
snippy --R1 <(cat A_R1.fq B_R1.fq) --R2 <(cat A_R2.fq B_R2.fq) ....
```
