### ISSUE TITLE
WARNING: All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate.

### ISSUE THREAD

**Issue by nadiaandreani** [tseemann/snippy#299]
Hi, I am using snippy 4.4 and a newly downloaded reference genome in gbk and/or fasta (cds from genomic). I have installed snippy using conda. 
my command looks like this:
snippy --cpus 8 --outdir ./snippy2/contigs/GB1_11 --ref ./c.jejuni_NCTC11168.gbk--ctgs . /sorted2/GB1_11_contigs_sorted.fa --mincov 1

the only warning I get from the run is the following 
 ### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

WARNING: All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate.
and this results in an empty .csv file

I am using Python 2.7.8. 

can you help me in understanding what I am doing wrong? I attach the snps.log and the csv. 
can i use the other files to run "snippy-core"?

Thanks 
[snps.log](https://github.com/tseemann/snippy/files/3377545/snps.log)

**Comment by nadiaandreani** [comment]
i also attach the log file that I get using the fasta file as it is different. 

[snps.log](https://github.com/tseemann/snippy/files/3377885/snps.log)

**Comment by tseemann** [comment]
That warning can be ignored. Are you getting the output files you expected?

What do you mean by cds fasta?

**Comment by evezeyl** [comment]
I have the same problem using .gbk (full genebank download with gi). Installed snippy downloaded from Conda 2-3 days ago (saw you posted a fix in conda 7 days ago). Tried all the fixes proposed here (except docker) https://github.com/tseemann/snippy/issues/259
created a new environment with installing java first, changing java load in snpEff ... did not work. 
Getting all files out of snippy
Will troubleshoot more today. Keeping posted if I can narrow problem. 
SnpEff	4.3t	2017-11-24
snippy 4.4.0
java-jdk                  8.0.112

**Comment by nadiaandreani** [comment]
Hi everybody and thanks for you replies.
yes all the files are there but some of them are empty (GFF is, csv too).

i did all the troubleshooting too as suggested on the previous issues. No
idea what's wrong.Today I will try on the computer of a colleague who
managed to have it working and see if it is a matter of my files or of
snippy.
Can you see anything funny from my log file?
N

**Comment by tseemann** [comment]
Unfortunately the `snps.log` file does not have the information I need.
Can you run it again but save all output using `snippy ...... 2>&1 > snippy.log` and send that?

**Comment by nadiaandreani** [comment]
here is the log you requested. i attach the one with a fasta file as
reference and one with gbk. I have to be honest they dont look different
from the one I submitted earlier this week.

thanks again for your help,
Nadia
*Nadia Andrea Andreani, PhD *
Research Fellow
School of Life Sciences
Joseph Banks Laboratories
University of Lincoln
Lincoln, LN6 7DL
UK


Il giorno ven 12 lug 2019 alle ore 10:00 Torsten Seemann <
notifications@github.com> ha scritto:

**Comment by nadiaandreani** [comment]
a quick update: my colleague got to work creating a new one environment with py 2.7 and then installing snippy. I did the same with no success. 

is there a way

**Comment by tseemann** [comment]
@nadiaandreani there was no log file attached to your previous message?  
If you have tried different conda and brew over time, your ~/.bashrc file may be full of old legacy cruft and in need of a full clean up. This is a common problem.
