### ISSUE TITLE
Update instruction reverts to older version of Snippy

### ISSUE THREAD

**Issue by sharbie88** [tseemann/snippy#300]
I had Snippy v 4.6.11 installed and used conda update -n base -c defaults conda to attempt update to 4.7.5.

Although the screen advice was "The following packages will be UPDATED: conda 4.6.11-py37_0 --> 4.7.5-py37_0", after completion of the update, the Snippy version is 4.3.5.

As per "Conda installation" issue #261, i tried using
conda create -n snippy -c conda-forge -c bioconda snippy

But the Snippy version is still 4.3.5 and 

"conda update snippy" returns

PackageNotInstalledError: Package is not installed in prefix.
  prefix: /home/sharb/anaconda3
  package name: snippy

If I try conda install Snippy=4.7.5, will this create 'environment' or duplication issues?

**Comment by tseemann** [comment]
There is no snippy 4.7.5 - this is the latest:
```
snippy --version
snippy 4.4.0
```
Your conda channel order should look like thos:
```
cat ~/.condarc
channels:
  - conda-forge
  - bioconda
  - defaults
```

**Comment by sharbie88** [comment]
OK - I see - that was the conda version.  AND, when I activated snippy, the version is correct as 4.4.0. Thanks.

My channel order is 
- bioconda
- conda-forge
- defaults
Can I fix the order?

**Comment by tseemann** [comment]
Yes, you can edit `~/.condarc directly` or use
```
conda install -c conda-forge -c bioconda -c defaults snippy
```

**Comment by sharbie88** [comment]
After processing the last instruction, the Package Plan "added/updated specs: - snippy". Various packages were downloaded and installed. However the following is still the case:
 cat ~/.condarc
channels:
  - bioconda
  - conda-forge
  - defaults
Also, when I enquired checked on the version of snippy, the mesage is now:
$ snippy -V
Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /home/sharb/anaconda3/bin/../perl5 /home/sharb/anaconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/sharb/anaconda3/lib/site_perl/5.26.2 /home/sharb/anaconda3/lib/5.26.2/x86_64-linux-thread-multi /home/sharb/anaconda3/lib/5.26.2 .) at /home/sharb/anaconda3/bin/snippy line 15.
BEGIN failed--compilation aborted at /home/sharb/anaconda3/bin/snippy line 15.

**Comment by tseemann** [comment]
Yes, you can fix the order using the `conda config` command somehow, but you can also just edit your ~/.condarc file directly.

Alternatively install like this:
```
conda install -c conda-forge -c bioconda -c defaults snippy

**Comment by sharbie88** [comment]
Yes, that's the instruction I used last time to install.  It is installed (V 4.4.0). Channels are still listing in the bioconda, conda-forge, defaults order.  But all seems ok anyway.
Thanks.
