### ISSUE TITLE
problem of bwa version(Version: 0.7.8-r455)

### ISSUE THREAD

**Issue by flyant2** [tseemann/snippy#302]
My bwa was installed by conda, Version: 0.7.8-r455, and there do not have the  options "**-Y**" in bwa's usage. However, "**-Y**" was used in snippy 4.3.8 :
$bwaopt .= qq{  **-Y** -M -R '\@RG\\tID:$rgid\\tSM:$rgid'};

so, bwa's version maybe required in: snippy --check.

Usage: bwa mem [options] <idxbase> <in1.fq> [in2.fq]
Algorithm options:
       -t INT        number of threads [1]
       -k INT        minimum seed length [19]
       -w INT        band width for banded alignment [100]
       -d INT        off-diagonal X-dropoff [100]
       -r FLOAT      look for internal seeds inside a seed longer than {-k} * FLOAT [1.5]
       -c INT        skip seeds with more than INT occurrences [10000]
       -D FLOAT      drop chains shorter than FLOAT fraction of the longest overlapping chain [0.50]
       -m INT        perform at most INT rounds of mate rescues for each read [100]
       -S            skip mate rescue
       -P            skip pairing; mate rescue performed unless -S also in use
       -e            discard full-length exact matches
       -A INT        score for a sequence match, which scales [-TdBOELU] unless overridden [1]
       -B INT        penalty for a mismatch [4]
       -O INT[,INT]  gap open penalties for deletions and insertions [6,6]
       -E INT[,INT]  gap extension penalty; a gap of size k cost '{-O} + {-E}*k' [1,1]
       -L INT[,INT]  penalty for 5'- and 3'-end clipping [5,5]
       -U INT        penalty for an unpaired read pair [17]
Input/output options:
       -p            first query file consists of interleaved paired-end sequences
       -R STR        read group header line such as '@RG\tID:foo\tSM:bar' [null]
       -v INT        verbose level: 1=error, 2=warning, 3=message, 4+=debugging [3]
       -T INT        minimum score to output [30]
       -a            output all alignments for SE or unpaired PE
       -C            append FASTA/FASTQ comment to SAM output
       -M            mark shorter split hits as secondary
       -I FLOAT[,FLOAT[,INT[,INT]]]
                     specify the mean, standard deviation (10% of the mean if absent), max
                     (4 sigma from the mean if absent) and min of the insert size distribution.
                     FR orientation only. [inferred]

**Comment by flyant2** [comment]
Note: path2git/snippy/binaries/linux/bwa
Version: 0.7.12-r1039

**Comment by tseemann** [comment]
The documentations state you need BWA > 0.7.12:
https://github.com/tseemann/snippy#requirements

The `bwa` binary that comes bundled is `Version: 0.7.12-r1039`

Are you sure you are using the 4.3.8 version of snippy?
Type
```
which -a snippy
```

**Comment by flyant2** [comment]
(biopython) [biox@localhost bin]$ ~/stu10/bio-app/git/snippy/bin/snippy
SYNOPSIS
  snippy 4.3.8 - fast bacterial variant calling from NGS reads

**Comment by flyant2** [comment]
ok..thanks!

**Comment by flyant2** [comment]
Sometimes, I like install biotools by git clone. It is easy to find software's database, and make my own, such as prokka of your. 
---Thanks

**Comment by flyant2** [comment]
~/stu10/bio-app/git/snippy/bin/snippy check 
...
[10:28:46] Checking version: samtools --version is >= 1.7 - ok, have 1.7
[10:28:46] Checking version: bcftools --version is >= 1.7 - ok, have 1.8
[10:28:46] Checking version: freebayes --version is >= 1.1 - ok, have 1.2
[10:28:47] Checking version: snpEff -version is >= 4.3 - ok, have 4.3
[10:28:47] Dependences look good!

So, Snippy4.4.x may add the Version Checking of other dependences, such as bwa.
//conda is somewhat slow here.

**Comment by tseemann** [comment]
Conda is very slow in Australia too - when I visited USA I noticed how much quicker it was!

You are right, I do not check BWA version even in 4.4.0, I will fix that now.
