### ISSUE TITLE
problem with snippy-core 

### ISSUE THREAD

**Issue by flyant2** [tseemann/snippy#303]
**Q1: about help document.**
snippy-core (4.4.0) must provide  '--ref', and it is not consistent with the help:
--ref=s         Reference in FASTA or GENBANK (default '').

The help document should be update.
**Q2:  No annotation of in snippy-core(4.4.0) output, but snippy-core(4.0-dev2) .** 
**$ head coreSNP.ab.run4.tab (snippy-core(4.4.0))**
CHR     POS     REF     snps.AB_CP018664.vs.49239       snps.AB_CP018664.vs.49242       snps.AB_CP018664.vs.49307
NZ_CP018664     179     T       A       A       A
NZ_CP018664     264     T       C       C       C
NZ_CP018664     276     C       T       T       T
NZ_CP018664     279     A       C       C       C

**$ head coreSNP.ab.run4.tab (snippy-core(4.0-dev2))**
### CHR     POS     Reference       snps.AB_CP018664.vs.49239       snps.AB_CP018664.vs.49242       snps.AB_CP018664.vs.49307       LOCUS_TAG       GENE    PRODUCT EFFECT
NZ_CP018664     179     T       A       A       A       AUO97_RS00005           alpha/beta fold hydrolase       missense_variant c.209T>A p.Ile70Asn
NZ_CP018664     264     T       C       C       C       AUO97_RS00005           alpha/beta fold hydrolase       synonymous_variant c.294T>C p.Phe98Phe
NZ_CP018664     276     C       T       T       T       AUO97_RS00005           alpha/beta fold hydrolase       synonymous_variant c.306_309delCCTAinsTCTC p.104
NZ_CP018664     279     A       C       C       C       AUO97_RS00005           alpha/beta fold hydrolase       synonymous_variant c.306_309delCCTAinsTCTC p.104
NZ_CP018664     285     C       T       T       T       AUO97_RS00005           alpha/beta fold hydrolase       synonymous_variant c.315C>T p.Arg105Arg
NZ_CP018664     303     T       C       C       C       AUO97_RS00005           alpha/beta fold hydrolase       synonymous_variant c.333T>C p.Gly111Gly
NZ_CP018664     309     G       A       A       A       AUO97_RS00005           alpha/beta fold hydrolase       synonymous_variant c.339G>A p.Glu113Glu

**Comment by tseemann** [comment]
(1) I do not understand
The help shows that `--ref` is mandatory.
```
USAGE
  snippy-core [options] --ref ref.fa snippy1 snippy2 snippy3 ...
```

**Comment by tseemann** [comment]
(2) yes annotations are not in `core.tab` 
this is an open issue: https://github.com/tseemann/snippy/issues/254
