### ISSUE TITLE
Incorrect numbering/reference nucleotide

### ISSUE THREAD

**Issue by conmeehan** [tseemann/snippy#31]
The nucleotide listed as the reference in snps.tab file is not always (or perhaps ever) the correct one for the nucleotide position and codon position listed.

**Comment by tseemann** [comment]
@otogishu I have now integrated `snpEff` into the pipeline and I now take the coordinates from that. I hope this solves the bug!

**Comment by otogishu** [comment]
Hi Torsten,

The new version seems to have helped a lot, thanks. I still see a small
problem in an example that I am looking at. A snps.tab output file has a
line that is output like so:

NC_000962 2288944 snp T G G:50 T:0 CDS - 298/561 99/185 synonymous_variant
c.297A>C p.Thr99Thr Rv2043c pncA pyrazinamidase/nicotinamidase PncA

From this I can see the Thr amino acid is listed as position 99 but is
actually 100 in the protein. I guess this is just a starting at 0 instead
of 1 error. However, a larger problem is that it calls a synonymous
mutation at position 297 whereas this is position 1 of the codon (ACC)
changed to a C (CCC) which is a non-synonymous change to a proline. Any
idea why this error is occurring?


Kind regards,

Conor

**Comment by tseemann** [comment]
I figured out this bug!

It seems it is a bug in Bioperl! The `/codon_start=1` is being converted to `frame=1` in the GFF but it should be `frame=0`. This was causing offset translations. It's fixed in current release of snippy now. It usually only happens if you use a NCBI .gbk file and not a Prokka .gbk file.

**Comment by GuilhemRoyer** [comment]
Hi Torsten,

It seems that I have the same problem as Conor... I use Snippy v4.0.2 with gbk files from Prokka and for every snp there is an offset of 1 in the nucleotide position resulting in an error in amino acid position and translation. I installed Snippy through Bioconda.

Is there a way to resolve this problem? Does it come from Bioperl version installed by Bioconda?

Bests,

Guilhem

**Comment by tseemann** [comment]
The solution is to use Snippy 4.2.x
Trying to package them
