### ISSUE TITLE
snippy-core

### ISSUE THREAD

**Issue by maingoclanmaingoclan** [tseemann/snippy#310]
Hello Torsten,
I have used snippy-multi or snippy-core to find out the differences between isolates. However, when I check the core.tab and core.vcf file, there is only snp TYPE in INFO column, there is no other type of substitutions (insertion, deletions).
Can snippy-core do this? If yes, what can I add in the command line to get it?
Thank you.
Anh

**Comment by tseemann** [comment]
`snippy-core` is for core SNPs (substitutions) only.

You will need to combine the individual `SAMPLE/snps.vcf` files  yourself, maybe using `bcftools merge` or something similar.

It is a challenging problem to reconcile these.   The better solution is to run `freebayes` or `bcftools call` with ALL YOUR SAMPLES AT ONCE.  This is slower, but will give you what you want, _joint variant calling_.
