### ISSUE TITLE
Freebayes --pooled-continuous option?

### ISSUE THREAD

**Issue by Buuntu** [tseemann/snippy#311]
Is there an option to run freebayes with the `--pooled-continuous` option, and if not, would it be doable/easy to add in a newer version?

**Comment by tseemann** [comment]
@Buuntu i thought the `--pooled-*` options were for when you perform multi-sample joint variant calling? 

 `snippy` calls one sample at a time and merges them independently. this was a desigh decision to make incremental tree building faster.

**Comment by Buuntu** [comment]
Thanks @tseemann! I'll try the `--fbopt` option.  My understanding is that `--pooled-continuous` is for when you do population level sequencing (ie not a single isolate).  So you may not know how many biological samples you're really sequencing in one go.  It allows you to call SNPs based on allele frequencies rather than considering it as a single biological sample.

**Comment by Buuntu** [comment]
While it does seem to be passing that option on to freebayes, I think the other hardcoded settings may interfere, such as `-p 2`.  I don't know which is taking precedence in this case since the two are not meant to be used together, my guess is the ploidy setting is.

Why is ploidy set to 2 and not 1 by the way?  Looking at the vcf file it generates the command looks like this:
```
freebayes -p 2 -P 0 -C 10 --min-repeat-entropy 1.5 --strict-vcf -q 13 -m 60 --min-coverage 10 -F 0.05 --pooled-continuous -f reference/ref.fa snps.bam --region contig_1_pilon:0-123479
```

**Comment by tseemann** [comment]
Why would `--pooled-continuous` not work with `-p 2`? 

I use `-p 2` for a good reason.  If you use `-p 1` then mismapping reads will cause false +ve SNP calls.  I learnt this lesson the hard way in Snippy 3.x

**Comment by Buuntu** [comment]
Thanks for the clarification @tseemann!  

You are right that I can just make my own pipeline, but I like how easy to use your tools are (and cover most of my use cases).  Will go ahead and create my own pipeline for these edge cases.

**Comment by rspreafico-vir** [comment]
Hi Torsten, a follow-up question on this that likely does not deserve its own issue: what parameters would you recommend to pass to freebayes if I were to use Snippy for calling variants from multiple samples, each being a mixture of viral sequences (1% frequency threshold, often 5000x average coverage)?

I think I am certain about `--pooled-continuous` but have doubts around `--pooled-discrete`, `--ploidy`, whether to keep priors, and maybe some other minor parameters (whether to limit search to best n alleles without losing sensitivity given 1% frequency threshold, whether to zero out haplotype length).

Thanks for any recommendation!

**Comment by tseemann** [comment]
@rspreafico-vir you should not use Snippy for calling variants in mixtures. it's for halpoid "pure, single colony" isolates only.

**Comment by rspreafico-vir** [comment]
Gotcha, thanks! I was hoping because of the ability to pass the `--pooled-continuous` parameter. Will not use Snippy, but if you have ever looked into calling variants from mixtures with freebayes and have any suggestion, I would only be happy to learn :-) Thank you for your prompt response!

**Comment by Buuntu** [comment]
@rspreafico-vir I would recommend you take a look at Breseq.  Here's a tutorial on how to do it for mixed samples: https://barricklab.org/twiki/pub/Lab/ToolsBacterialGenomeResequencing/documentation/tutorial_populations.html.  

It has a conda recipe, is easy to run, and generates really nice HTML output.  It will tell you all of the mutations and the % of the population they are in, and even look for larger indels.

**Comment by rspreafico-vir** [comment]
That's awesome, thanks so much for your recommendation!

**Comment by tseemann** [comment]
@rspreafico-vir it's also in `brew`. i wrote the formula for it. just be aware it only supports single end reads.
