### ISSUE TITLE
Unknown option mask

### ISSUE THREAD

**Issue by maingoclanmaingoclan** [tseemann/snippy#314]
Hello Torsten,
I have created a bed file named "gene" to exclude specific regions in Mycobacterium tuberculosis.
The content of bed file is:

NC_000962       105324  106715  Rv0096  PPE1
NC_000962       131382  132872  Rv0109  PE-PGRS1

When I run the command line:
snippy --outdir 218T0 -R1 WTCHG_689876_72885264_1.fastq -R2 WTCHG_689876_72885264_2.fastq --mask auto gene

The error is: Unknown option mask
Do you know what is the problem?
I look forward to hear from you.
Thank you.
Anh

**Comment by tseemann** [comment]
@maingoclanmaingoclan i think you mean `--mask gene` ?
