### ISSUE TITLE
All frames are zero!

### ISSUE THREAD

**Issue by yob1997** [tseemann/snippy#316]
Hello,

I try to run snippy (installed with LinuxBrew). the reference is one i created myself with RAST.
`### /home/linuxbrew/.linuxbrew/bin/snippy --cpus 16 --outdir test --ref genome_data/T_0-references/DTK_01.gbk --R1 genome_data/trimReads/DTK_03_48485-A03_R1.fastq.gz --R2 genome_data/trimReads/DTK_03_48485-A03_R2.fastq.gz`

All dependencies are installed and checken with snippy --check.
The following warning is displayed twice in the snps.log
```
### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref
WARNING: All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate.
```
Do you have any idea how I can fix this warning, I only found one other issue where conda was used. the packages seem up-to-date.

Kind regards,
Yob

**Comment by tseemann** [comment]
That warning can be ignored. It's some issue with `snpeff` that changed between minor versions.  if you have snippy 4.4.x and are using conda and `conda update --all` is happy then you are fine.
