### ISSUE TITLE
Snippy-multi input format

### ISSUE THREAD

**Issue by shrdlu9** [tseemann/snippy#319]
I'm trying to test out the core SNP genome step described on the Snippy front page from a directory containing multiple snippy output folders, all fasta contigs run against the same reference genome. 

The input.tab tsv file was created with below layout 

AssemblyName1     /snippyoutput1/AssemblyName1.aligned.fa
AssemblyName2     /snippyoutput2/AssemblyName2.aligned.fa
.
.
.

When the snippy-multi script is run from the parent directory it gives an error message

ERROR: [AssemblyName1] unreadable file '/snippyoutput1/AssemblyName1.aligned.fa'

I tried running the same process with just the initial assembly fasta files (rather than the snippy outputs) as well, and encountered the same error message. 

I'm pretty sure I'm making a silly mistake somewhere- would you mind telling me what could be wrong? 

Thank you!

**Comment by tseemann** [comment]
You appear to be creating an input file for `snippy-multi` not `snippy-core`.

If you have already run `snippy` on each genome, just run
```
snippy-core --ref ref.fa snippyoutput1/ snippyoutput2/
```
ie. put each snippy _folder_ as a parameter.
