### ISSUE TITLE
BGzip included in snippy

### ISSUE THREAD

**Issue by scholzmb** [tseemann/snippy#32]
Note,

binary version of BGZIP included with source code is dependent on glibc, with the static compile that is included compiled against glibc 2.14.  Had to recompile from samtools/htseq from my own install of samtools and replace binary.

**Comment by tseemann** [comment]
@scholzmb Are you able to help me to build a static version of `bgzip` and `tabix` ?
I've had trouble in the past.

**Comment by tseemann** [comment]
I've replaced some of the binaries with those from here:
https://sourceforge.net/projects/biobin/files/
They are mostly static and built on older glibc from Centos 5.

**Comment by tseemann** [comment]
In https://github.com/tseemann/snippy/tree/version_4 I am not producing .bgz files anymore.
