### ISSUE TITLE
BAM header error - failing every time

### ISSUE THREAD

**Issue by nataliering** [tseemann/snippy#322]
Hello @tseemann 

I'm trying to use Snippy with some fastqs downloaded from the SRA, along with a reference gbff also downloaded from NCBI. 

Everything goes smoothly during the intial bwa memming, but something seems to be going wrong immediately after that (possibly during conversion from sam to bam?). After that, the script does run to completion, but always with 0 variants (there definitely should be some!). 

Here's the output just before and after where I'm seeing the error message:

`[samclip] Processed 7200000 records...
[main] Version: 0.7.15-r1140
[main] CMD: bwa mem -Y -M[samclip] Total SAM records 7291398, removed 350755, allowed 134488, passed 6940643
[samclip] Header contained 3 lines
[samclip] Done.
 -R @RG\tID:snippy_test\tSM:snippy_test -t 16 reference/ref.fa /home/ubuntu/FHA/post2000/I429_1.fastq.gz /home/ubuntu/FHA/post2000/I429_2.fastq.gz
[main] Real time: 431.538 sec; CPU: 3105.016 sec
[bam_sort_core] merging from 0 files and 15 in-memory blocks...
[E::bgzf_read] Read block operation failed with error 33 after 0 of 4 bytes
[E::bam_hdr_read] Invalid BAM binary header
[bam_mating_core] ERROR: Couldn't read header
[00:09:49] Running: samtools index snps.bam 2>> snps.log
[00:09:49] Running: fasta_generate_regions.py reference/ref.fa.fai 134011 > reference/ref.txt 2>> snps.log
[00:09:49] Running: freebayes-parallel reference/ref.txt 16 -p 2 -P 0 -C 10 --min -repeat-entropy 1.5 --strict-vcf -q 13 -m 60 --min-coverage 10 -F 0.05  -f reference/ref.fa snps.bam > snps.raw.vcf 2>> snps.log`

And the command I'm using to run Snippy is:
`snippy --cpus 16 --outdir snippy_test --ref BP_Tohama1_genomic.gbff --R1 I429_1.fastq.gz --R2 I429_2.fastq.gz
`

I've tried various different reference files from NCBI, made sure all my tools were up-to-date (including Snippy itself), and Googled  the error messages to see if I could fix it myself, but I'm coming up blank. 

Any ideas what's going wrong, and how I can fix it please?

Thanks for your help,
Nat

**Comment by andersgs** [comment]
Hi @nataliering how did you install all the tools? Can you confirm that samtools is working? Can you run it independently of snippy? That error suggests compression isn’t working properly. I would be particularly interested in knowing that you can correctly covert a SAM to BAM and sort it. 

Cheers.  A.

**Comment by tseemann** [comment]
@nataliering can you tell me what these commands print: 
```
snippy --check
which samtools
ldd $(which samtools)
```

**Comment by tseemann** [comment]
1. Try `snippy --ram 32` 

2. samtools is tricky - you need to build it against the right htslib version.

3. Given the mix of years old installation, I would recommend using Conda (with envs) to make your life simpler: https://bioconda.github.io/user/install.html

**Comment by tomrconnor** [comment]
In response to 4 - are you running a GVL or custom instance?

**Comment by nataliering** [comment]
Hi both 

It's a custom instance, but it's taken so much abuse from me over the course of my PhD (installing things over the top of other things, etc.) that it's probably beyond hope! However, I created a Snippy conda environment and that seems to be working fine, so I'll just stick with that.

Thanks for all your help! :)
Nat

**Comment by tseemann** [comment]
@nataliering good news!  conda envs are the simplest strategy these days.
