### ISSUE TITLE
Snippy pipe error at freebayes-parallel

### ISSUE THREAD

**Issue by feardley** [tseemann/snippy#323]
Hi Torsten,
I am running snippy to target sites on an S. Venezuelae reference with an interleaved sequencing file, however the pipeline is failing at the freebayes-parallel step. 
"### freebayes-parallel reference/ref.txt 4 -p 2 -P 0 -C 10 --min-repeat-entropy 1.5 --strict-vcf -q 13 -m 60 --min-coverage 10 -F 0.05  -f reference/ref.fa snps.bam > snps.raw.vcf
dyld: Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13find_first_ofEPKcmm"

My command is:
"snippy --cpus 4 --outdir mysnps --ref SVEN.gbk --peil combined.fastq"

The reference was obtained from NCBI:
"https://www.ncbi.nlm.nih.gov/nuccore/NZ_CP018074.1?report=gbwithparts&log$=seqview"

[snps.log](https://github.com/tseemann/snippy/files/3734614/snps.log)

Cheers

**Comment by tseemann** [comment]
Looks like you are running on MacOS ?
How did you install snippy?
Hopefully with `brew`?
Have you done `brew update ; brew upgrade snippy` ?

**Comment by feardley** [comment]
Thanks for the reply,
Yes Mac OS
Installed snippy with Brew 
Have done Brew Update and Upgrade 
Brew won’t pull the updates past 4.5.0 - says this is the latest version

**Comment by tseemann** [comment]
I assume you mean snippy 4.4.0?

Try `brew reinstall snippy freebayes`

**Comment by feardley** [comment]
Sorry yes I did mean 4.4.0

I can now pull the latest patch from Brew

However snippy can't find java despite java being installed (see log file below).

Has any of the code for locating java been changed in the latest patch? Java was found before I updated.

Thanks for your help

[Java Error.log](https://github.com/tseemann/snippy/files/3738411/Java.Error.log)

**Comment by tseemann** [comment]
```
brew unlink  jdk
brew install jdk@8
brew link jdk@8
```

**Comment by tseemann** [comment]
Ok, you are on MacOS:
```
java -version\
java version "13" 2019-09-17\
Java(TM) SE Runtime Environment (build 13+33)\
Java HotSpot(TM) 64-Bit Server VM (build 13+33, mixed mode, sharing)\
C02Z412WL40Y:102 fne21$ \
}
```
That looks different to my Mac:
```
java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

**Comment by TDT53** [comment]
Hello Torsten,

I am not sure if this issue has been resolved in 4.6.0 but I seem to encounter the same problem. If there is any current workaround or fixing, please let me know.

Thank you!

**Comment by tseemann** [comment]
Can you run these commands on your reference `ref.gbk` 
```
head ref.gbk | od -a
```
and
```
tail ref.gbk
```

**Comment by rileyo** [comment]
Hi Torsten,

Sorry to jump in in the middle of this thread but I am experiencing the same problem. My .log file includes the following after attempting to run freebayes.

`freebayes-parallel reference/ref.txt 16 -p 2 -P 0 -C 2 -F 0.05 --min-coverage 10 --min-repeat-entropy 1.0 -q 13 -m 60 --strict-vcf   -f reference/ref.fa snps.bam > snps.raw.vcf`

dyld: Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13find_first_ofEPKcmm
  Referenced from: /usr/local/bin/vcfstreamsort
  Expected in: /usr/lib/libstdc++.6.dylib
 in /usr/local/bin/vcfstreamsort
dyld: Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13find_first_ofEPKcmm
  Referenced from: /usr/local/bin/vcfuniq
  Expected in: /usr/lib/libstdc++.6.dylib
 in /usr/local/bin/vcfuniq
Traceback (most recent call last):
  File "/usr/local/bin/vcffirstheader", line 16, in <module>
    print(line.strip())
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
/usr/local/bin/freebayes-parallel: line 40: 77307 Exit 141                ( cat "$regionsfile" | parallel -k -j "$ncpus" "${command[@]}" --region {} )
     77308 Exit 120                | vcffirstheader
     77309 Abort trap: 6           | vcfstreamsort -w 1000
     77311 Abort trap: 6           | vcfuniq

I've attempted to reinstall snippy, freebayes, vcflib, and root using brew. However, nothing has solved the problem. Any guidance would be incredibly helpful. Thanks!

`brew config`
HOMEBREW_VERSION: 2.2.11-42-gee1f05e
ORIGIN: https://github.com/Homebrew/brew
HEAD: ee1f05e029a2308465ba6ca64d715c694cde2f9c
Last commit: 4 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fd3c66a099d64526a3d7e3604184e88e4b3aa69a
Core tap last commit: 6 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1103
Git: 2.26.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 1.8.0_121
macOS: 10.15.4-x86_64
CLT: 1103.0.32.29
Xcode: 11.4
XQuartz: 2.7.11 => /opt/X11

`brew doctor` returns "ready to brew"

**Comment by tseemann** [comment]
Your freebayes installation looks broken.
Try reinstalling a brand new snippy from a fresh conda install.
