### ISSUE TITLE
core snp annotation different with prokka

### ISSUE THREAD

**Issue by wanyingsun** [tseemann/snippy#329]
Hi, Dr. tseemann, I used snppy-core to get the tab file with annotation at the last few lines. I also use prokka to note snps in reference sequence. Why the snp annotation are different from the two methods ?  Can I just use the snppiy-core file as my result ? Thanks.

**Comment by tseemann** [comment]
How did you use `prokka` to find SNPs ?

**Comment by wanyingsun** [comment]
I used prokka to note reference, and find snp position in reference then find genes.

**Comment by tseemann** [comment]
I don't know what the purpose of your analysis is, so I can not answer your original question. It is unclear.

**Comment by wanyingsun** [comment]
I want to annotate snps and want to know wether it is synonymous , can I just use the last few lines of snppy-core result ?

**Comment by tseemann** [comment]
My software `snippy` is often used to generate input for CLonalFrameML or Gubbins:
https://github.com/tseemann/snippy#core-snp-phylogeny

**Comment by tseemann** [comment]
`snippy-core` is only the core snps amongst a set of isolates.  Some of the SNPs will be different, so you can't annotate whether it is synonymous or not.
eg. Ref=A, Sample1=A Sample2=T, Sample3=C

You can use each _individual_ snippy results, but not snippy-core.
