### ISSUE TITLE
Is it possible to have *.aligned.fa with variants?

### ISSUE THREAD

**Issue by andersgs** [tseemann/snippy#33]
Hi Torst.

Would it be possible for .aligned.fa to also include variants (SNPs)? .consensus.fa includes all variants (including indels --- meaning it has a different length from the reference) making it hard to cut using coordinates from the reference.

My idea would be to produce a snps.vcf.gz with SNPs only, and then apply vcf-concensus. Would that work?

Anders.

**Comment by andersgs** [comment]
Ideally, it would do the following:

>	#filter snps.vcf.gz to only include SNPs
>	vcffilter -f "TYPE = snp" snps.vcf.gz > junk.vcf; 
>	bgzip -c junk.vcf > junk.vcf.gz; 
>	tabix -p vcf junk.vcf.gz; 
> 	# then apply vcf-consensus to introduce the snps to the reference
>	vcf-consensus junk.vcf.gz < ref.fa > junk.aligned.var.fa; 
>	# then apply mask as in consensus.fa to add - or N as appropriate

Anders.

**Comment by tseemann** [comment]
1. `snps.aligned.fa` isn't allowed to include SNPs because it needs to remain that way for snippy-core to work.

2. I have added `snps.consensus.subs.fa` which applied snp and mnp (but **not** equal length complex types) to the snps.consensus.fa (so it has -, N, and [sn]mps).

**Comment by tseemann** [comment]
@embatty I'll fix in issue #133
