### ISSUE TITLE
snpEFF ANN gene names with Genbank reference 

### ISSUE THREAD

**Issue by pvanheus** [tseemann/snippy#332]
When using a Genbank reference ([this one](https://zenodo.org/record/3531703/files/Mycobacterium_tuberculosis_ancestral_reference.gbk?download=1)), the ANN fields provided by snpEff have details from the ID field in the GFF3 that snpEff creates.

I.e. while `snpEff` can handle a Genbank reference directly `snippy` [creates](https://github.com/tseemann/snippy/blob/master/bin/snippy#L197) a GFF3 reference with the ID as the locus tag. If `snpEff` is called with the Genbank file it generates a database with gene names not locus tags.

This is rambling, but since the gene names are what I want is there a way to get then by either doing something with the GFF3 or using the Genbank file directly?

**Comment by tseemann** [comment]
What is the exact `snpEff` command line you used to go from GENBANK + VCF to the annotated VCF?

I have had no end of pain with `snpEff` and am half way to migrating to `bcftools csq`

**Comment by pvanheus** [comment]
Yes they are not unique. Uniqueness is not required in the ANN field.

```
mkdir ref
gzip -c Mycobacterium_tuberculosis_ancestral_reference.gb > ref/genes.gbk.gz
snpEff build -c snpeff.config -dataDir . -genbank ref
snpEff ann -noLog -noStats -no-downstream -no-upstream -no-utr -c snpeff.config -dataDir . ref test.vcf
```
[test.vcf](https://gist.github.com/pvanheus/73317f04cb713b78191fefd89e76ec12)
[test-annotated.vcf](https://gist.github.com/pvanheus/259d78a730052479d6b8fc7f65123852)

**Comment by cocathail** [comment]
Also having this issue where snpEff craps out after running below command when using GebBank Reference. Can't seem to figure why. This also happens to be a mycobacterial reference genome. It runs completely fine when using the fasta of the same reference genome.

snpEff ann -noLog -noStats -no-downstream -no-upstream -no-utr -t -c reference/snpeff.config -dataDir . ref snps.filt.vcf > snps.vcf 2>> snps.log

**Comment by cocathail** [comment]
Nevermind. Just ran it on E. coli with K12 GFF and snpEff still crapped out

**Comment by biobrad** [comment]
I also have snpEff caking its' trousers when using a genbank file.

**Comment by tseemann** [comment]
@biobrad @cocathail what version of snpeff are you using? and what java version?

```
 $ snpEff -version
SnpEff  4.3t    2017-11-24

 $ java -version
openjdk version "1.8.0_212-ojdkbuild"
```

**Comment by cocathail** [comment]
snpEff is the same version

java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

**Comment by tseemann** [comment]
I've had issues with Java.  Never worked on versions > 1.8 for me.
Then they changed the numbering system.

**Comment by cocathail** [comment]
managed to force back to java 1.8. This has indeed fixed the issues!
