### ISSUE TITLE
Symbolic link  then hard link issues

### ISSUE THREAD

**Issue by Tahausix** [tseemann/snippy#334]
Hi,

I had an issue with symbolic links giving a operation no permitted termination, i followed the advice on a previous issue relating to this, and now i get a failed to create hard link './ref.fa' => 'reference/ref.fa': operation not permitted message for this operation.

Any hints on how i could work around this?

Cheers,

**Comment by tseemann** [comment]
You can change `ln -s` or `ln -f` to `cp -f` 
This will **copy** the file instead of trying to link it.
