### ISSUE TITLE
snippy-multi has error: Bad ID?

### ISSUE THREAD

**Issue by Chongli-90** [tseemann/snippy#336]
I am new to snippy and am trying to run snippy-multi with the following command:

snippy-multi input_1.tab --ref 452_H1N1_HA.fa --cpus 16 > runme.sh

However, I got the error:
Reading: input_1.tab
ERROR: Bad ID: 

I checked the input_1.tab file (see attached) but have no idea where it going wrong. Any help will be appreciated!
[input_1.tab.txt](https://github.com/tseemann/snippy/files/3878129/input_1.tab.txt)

**Comment by moshtaqtsr** [comment]
I got the same error. with quite a similar input file!

**Comment by tseemann** [comment]
The second line of your file is blank. A blank ID is a bad ID :-)

```
#ID	#R1	#R2

MT472	/home/torremor/lixx5577/MT1803_1/snippy/472_S3_001.fastq.gz_trim_R1_paired.fastq.gz	/home/torremor/lixx5577/MT1803_1/snippy/472_S3_001.fastq.gz_trim_R2_paired.fastq.gz

MT474	/home/torremor/lixx5577/MT1803_1/snippy/474_S4_001.fastq.gz_trim_R1_paired.fastq.gz	/home/torremor/lixx5577/MT1803_1/snippy/474_S4_001.fastq.gz_trim_R2_paired.fastq.gz
```

**Comment by Chongli-90** [comment]
Thank you for the help! Now I can run this script but I can't find my output files! The system showed like this:

Reading: input_1.tab
Generating output commands for 3 isolates
Done.

However, I can't find the output files in my directory. Is there anything wrong?

**Comment by tseemann** [comment]
You didn't follow the instructions.
That script only generates the script you need to run.
Read https://github.com/tseemann/snippy#using-snippy-multi
