### ISSUE TITLE
How does Snippy create 'core.full.aln' from a draft assembly reference?

### ISSUE THREAD

**Issue by cizydorczyk** [tseemann/snippy#338]
How does Snippy create its pseudo-whole genome alignment (core.full.aln) when the reference provided consists of contigs (i.e. is a draft assembly)?

Are contigs stitched together, separated by 'N's or something along those lines? I have tried searching in the code but am either looking in the wrong place or misunderstanding something (Perl is not my strong suit). I also have not been able to find any previous questions that may have answered this (but I may have just missed it!).

Any help in understanding is greatly appreciated!

Thank you,
Conrad

**Comment by tseemann** [comment]
it just concatenates the contigs.
i think they are in the order you provided them in the `--ref` file.
a gff file would be useful to maintain connection back, but you could derive it from ref.fa if needed.
it is designed to pass to tree building software.

**Comment by cizydorczyk** [comment]
Great, thank you for the clarification. I realized I had never thought about it (as I usually run Snippy with a complete reference) and thought I would ask!
