### ISSUE TITLE
snippy-core issue

### ISSUE THREAD

**Issue by peflanag** [tseemann/snippy#339]
Hi,

I'm just wondering if this has actually worked? It says theres a warring and an error at the end but it seems to have made an .aln file that when I run through snp-dists gives me my snps. Could anyone tell me if it is correct or not? I have also attached the snp-dists output

Cheers

This is snippy-core 4.4.5
Obtained from http://github.com/tseemann/snippy
Enabling bundled tools.
Found any2fasta - /Users/peterflanagan/miniconda3/envs/snippy/binaries/noarch/any2fasta
Found samtools - /Users/peterflanagan/miniconda3/envs/snippy/bin/samtools
Found minimap2 - /Users/peterflanagan/miniconda3/envs/snippy/bin/minimap2
Found bedtools - /Users/peterflanagan/miniconda3/envs/snippy/bin/bedtools
Found snp-sites - /Users/peterflanagan/miniconda3/envs/snippy/bin/snp-sites
Saving reference FASTA: Core_IMRL_All_Runs.ref.fa
This is any2fasta 0.4.2
Opening '/Users/peterflanagan/IMRL_Sequencing/Illumina/Clusters_Snippy/H37rv_Ref3.fasta'
Detected FASTA format
Read 63024 lines from '/Users/peterflanagan/IMRL_Sequencing/Illumina/Clusters_Snippy/H37rv_Ref3.fasta'
Wrote 1 sequences from FASTA file.
Processed 1 files.
Done.
Loaded 1 sequences totalling 4411532 bp.
Loading mask bed file: /Users/peterflanagan/IMRL_Sequencing/Illumina/Clusters_Snippy/Mtb_NC_000962.3_mask.bed
Will mask 731 regions totalling 341952 bp ~ 7.75%
0	IMRL28	snp=558	del=188	ins=134	het=382	unaligned=90162
1	IMRL29	snp=535	del=87	ins=63	het=110	unaligned=91731
2	IMRL30	snp=566	del=111	ins=94	het=271	unaligned=88527
3	IMRL137	snp=984	del=315	ins=235	het=1459	unaligned=78547
4	IMRL138	snp=980	del=312	ins=192	het=1747	unaligned=78892
5	IMRL139	snp=320	del=65	ins=41	het=959	unaligned=74117
6	IMRL140	snp=2407	del=466	ins=443	het=1257	unaligned=105106
7	IMRL141	snp=2400	del=439	ins=444	het=1841	unaligned=140664
8	IMRL142	snp=945	del=130	ins=149	het=631	unaligned=83485
9	IMRL143	snp=969	del=188	ins=216	het=2367	unaligned=89927
10	IMRL144	snp=1477	del=308	ins=302	het=1357	unaligned=103326
11	IMRL145	snp=1454	del=262	ins=266	het=1182	unaligned=104055
12	IMRL146	snp=1478	del=362	ins=322	het=2125	unaligned=102433
13	IMRL147	snp=1461	del=299	ins=226	het=1444	unaligned=104031
14	IMRL148	snp=1466	del=343	ins=309	het=691	unaligned=103705
15	IMRL149	snp=1481	del=362	ins=312	het=1508	unaligned=102803
16	IMRL150	snp=980	del=313	ins=193	het=1140	unaligned=79709
17	IMRL151	snp=944	del=310	ins=173	het=575	unaligned=84734
18	IMRL152	snp=967	del=306	ins=191	het=803	unaligned=84369
19	IMRL153	snp=809	del=275	ins=188	het=784	unaligned=101382
20	IMRL154	snp=798	del=284	ins=179	het=893	unaligned=101154
21	IMRL156	snp=804	del=282	ins=170	het=496	unaligned=102359
22	IMRL157	snp=805	del=284	ins=164	het=380	unaligned=102387
23	IMRL158	snp=801	del=282	ins=173	het=329	unaligned=102308
24	IMRL159	snp=818	del=305	ins=197	het=408	unaligned=101030
25	IMRL160	snp=804	del=296	ins=170	het=356	unaligned=101736
26	IMRL161	snp=801	del=273	ins=178	het=429	unaligned=103195
27	IMRL162	snp=806	del=296	ins=187	het=509	unaligned=102527
28	IMRL163	snp=802	del=246	ins=164	het=470	unaligned=102574
29	IMRL164	snp=796	del=282	ins=161	het=471	unaligned=104545
30	IMRL165	snp=794	del=297	ins=145	het=410	unaligned=102582
31	IMRL167	snp=902	del=298	ins=127	het=153	unaligned=86322
32	IMRL168	snp=939	del=300	ins=134	het=198	unaligned=81512
33	IMRL169	snp=949	del=255	ins=176	het=164	unaligned=81489
34	IMRL170	snp=949	del=307	ins=129	het=367	unaligned=81907
35	IMRL171	snp=965	del=311	ins=184	het=477	unaligned=79697
36	IMRL172	snp=963	del=310	ins=161	het=735	unaligned=81216
37	IMRL173	snp=973	del=324	ins=131	het=395	unaligned=79398
38	IMRL174	snp=955	del=311	ins=197	het=731	unaligned=79851
39	IMRL175	snp=883	del=211	ins=102	het=85	unaligned=85493
40	IMRL176	snp=949	del=302	ins=129	het=551	unaligned=81190
41	IMRL177	snp=978	del=319	ins=188	het=844	unaligned=80187
42	IMRL178	snp=974	del=327	ins=164	het=372	unaligned=80674
43	IMRL179	snp=973	del=310	ins=213	het=970	unaligned=79183
44	IMRL180	snp=965	del=302	ins=165	het=467	unaligned=80636
45	IMRL181	snp=964	del=296	ins=124	het=652	unaligned=80965
46	IMRL182	snp=986	del=326	ins=190	het=1832	unaligned=78463
47	IMRL183	snp=919	del=256	ins=123	het=285	unaligned=88878
48	IMRL184	snp=922	del=262	ins=107	het=209	unaligned=89807
49	IMRL185	snp=945	del=257	ins=134	het=358	unaligned=84465
50	IMRL186	snp=942	del=256	ins=166	het=341	unaligned=85016
51	IMRL187	snp=1398	del=238	ins=189	het=184	unaligned=109577
52	IMRL188	snp=821	del=122	ins=129	het=73	unaligned=103098
53	IMRL189	snp=863	del=153	ins=125	het=162	unaligned=90089
54	IMRL190	snp=875	del=154	ins=185	het=328	unaligned=87254
55	IMRL191	snp=818	del=153	ins=143	het=95	unaligned=105083
56	IMRL192	snp=861	del=192	ins=112	het=208	unaligned=88924
57	IMRL193	snp=802	del=105	ins=132	het=40	unaligned=107206
58	IMRL194	snp=855	del=178	ins=127	het=195	unaligned=88497
59	IMRL195	snp=871	del=163	ins=160	het=191	unaligned=87786
60	IMRL196	snp=903	del=190	ins=188	het=566	unaligned=85372
61	IMRL197	snp=887	del=204	ins=179	het=605	unaligned=85836
62	IMRL198	snp=843	del=182	ins=140	het=108	unaligned=94407
63	IMRL199	snp=935	del=134	ins=140	het=351	unaligned=91786
64	IMRL200	snp=925	del=136	ins=101	het=282	unaligned=94114
65	IMRL201	snp=904	del=131	ins=113	het=145	unaligned=106814
66	IMRL202	snp=944	del=196	ins=138	het=340	unaligned=84271
67	IMRL203	snp=772	del=110	ins=123	het=399	unaligned=91393
68	IMRL204	snp=948	del=122	ins=121	het=342	unaligned=88470
69	IMRL205	snp=891	del=136	ins=106	het=115	unaligned=102085
70	IMRL206	snp=993	del=292	ins=184	het=1015	unaligned=78843
71	IMRL207	snp=986	del=206	ins=174	het=505	unaligned=79616
72	IMRL208	snp=996	del=310	ins=128	het=677	unaligned=78786
73	IMRL209	snp=994	del=283	ins=180	het=554	unaligned=78412
74	IMRL210	snp=985	del=251	ins=162	het=425	unaligned=78897
75	IMRL211	snp=1002	del=269	ins=155	het=627	unaligned=78641
76	IMRL212	snp=996	del=251	ins=197	het=647	unaligned=78262
77	IMRL213	snp=517	del=23	ins=30	het=26	unaligned=130127
78	IMRL214	snp=0	del=0	ins=0	het=0	unaligned=4406927
79	IMRL215	snp=867	del=191	ins=181	het=255	unaligned=87835
80	IMRL216	snp=874	del=163	ins=126	het=258	unaligned=86813
81	IMRL217	snp=874	del=181	ins=167	het=305	unaligned=86637
82	IMRL219	snp=730	del=35	ins=52	het=20	unaligned=113618
83	IMRL220	snp=862	del=145	ins=115	het=226	unaligned=88071
84	IMRL221	snp=875	del=168	ins=138	het=184	unaligned=87288
85	IMRL222	snp=881	del=172	ins=142	het=348	unaligned=86336
86	IMRL223	snp=871	del=154	ins=121	het=263	unaligned=87801
87	IMRL225	snp=872	del=187	ins=168	het=436	unaligned=87495
88	IMRL226	snp=874	del=168	ins=138	het=353	unaligned=90618
89	IMRL228	snp=873	del=163	ins=174	het=62522	unaligned=87295
90	IMRL232	snp=889	del=240	ins=206	het=440	unaligned=85426
91	IMRL233	snp=825	del=39	ins=82	het=230	unaligned=89004
92	IMRL234	snp=890	del=276	ins=172	het=294	unaligned=85332
93	IMRL235	snp=897	del=238	ins=197	het=304	unaligned=85912
94	IMRL236	snp=602	del=22	ins=40	het=200	unaligned=98437
95	IMRL237	snp=905	del=309	ins=204	het=729	unaligned=85474
96	IMRL238	snp=890	del=220	ins=188	het=278	unaligned=86027
97	IMRL239	snp=899	del=177	ins=203	het=405	unaligned=85534
98	IMRL241	snp=898	del=238	ins=225	het=287	unaligned=85669
99	IMRL243	snp=0	del=0	ins=0	het=0	unaligned=4405795
100	IMRL244	snp=755	del=45	ins=68	het=219	unaligned=129805
101	IMRL251	snp=576	del=201	ins=121	het=471	unaligned=89593
102	IMRL252	snp=571	del=171	ins=132	het=477	unaligned=89817
103	IMRL253	snp=561	del=175	ins=122	het=460	unaligned=88240
104	IMRL254	snp=559	del=96	ins=131	het=281	unaligned=88298
Opening: Core_IMRL_All_Runs.tab
Opening: Core_IMRL_All_Runs.vcf
Processing contig: NC_000962.3
Masking alignment at 731 regions
Generating Core_IMRL_All_Runs.full.aln
Creating TSV file: Core_IMRL_All_Runs.txt
Running: snp-sites -c -o Core_IMRL_All_Runs.aln Core_IMRL_All_Runs.full.aln
Warning: No SNPs were detected so there is nothing to output.
ERROR: Could not run: snp-sites -c -o Core_IMRL_All_Runs.aln Core_IMRL_All_Runs.full.aln
(snippy) peterflanagan@med176028 Clusters_Snippy % 

[Core.xlsx](https://github.com/tseemann/snippy/files/3891802/Core.xlsx)

**Comment by tseemann** [comment]
```
Warning: No SNPs were detected so there is nothing to output.
```

It turns out you have no core SNPs. Zero. Zilch.  
This means you have an outlier sample which is ruining it for the rest.

I can see a few outliers:
```
78 IMRL214 snp=0 del=0 ins=0 het=0 unaligned=4406927
99 IMRL243 snp=0 del=0 ins=0 het=0 unaligned=4405795
```
Basically both those samples had no reads aligning to them.
Remove them from the core analysis and you should get a proper result.
