### ISSUE TITLE
annotations in core files

### ISSUE THREAD

**Issue by marieleoz** [tseemann/snippy#340]
Hi, I have used snippy-multi with several multi-fasta inputfiles and a .gbk file as a ref using the commands:

$snippy-multi CAS-NAD_input.tab --ref CAS-NAD-13-1.gbk --cpus 16 > runme.sh
$sh ./runme.sh

I found that each inputfile got annotations in its own snp output files, but there was no annotations in the core output files. I checked the runme.sh file and found that the command for snippy-core used a fasta file as a reference:

$snippy-core --ref 'CAS-NAD-13-2/ref.fa' CAS-NAD-13-2 CAS-NAD-13-3 CAS-NAD-13-4 CAS-NAD-13-5 CAS-NAD-21-1 CAS-NAD-21-2 CAS-NAD-21-3 CAS-NAD-21-4 CAS-NAD-21-5 CAS-NAD-53-1 CAS-NAD-53-2 CAS-NAD-53-3 CAS-NAD-53-4 CAS-NAD-53-5

Thus I reran snippy-core specifying that the same .gbk ref file was to be used as the one for snippy-multi:

$snippy-core --ref 'CAS-NAD-13-1.gbk' CAS-NAD-13-2 CAS-NAD-13-3 CAS-NAD-13-4 CAS-NAD-13-5 CAS-NAD-21-1 CAS-NAD-21-2 CAS-NAD-21-3 CAS-NAD-21-4 CAS-NAD-21-5 CAS-NAD-53-1 CAS-NAD-53-2 CAS-NAD-53-3 CAS-NAD-53-4 CAS-NAD-53-5

However, I still have no annotations in the core files. 
How can I fix this please?

Thanks a lot!

**Comment by marieleoz** [comment]
Just adding: version is 4.4.0 and details for the snippy-core run seems to show that a fasta reference is produced from the .gbk file:

This is snippy-core 4.4.0
Obtained from http://github.com/tseemann/snippy
Enabling bundled tools.
Found any2fasta - /home/adm-loc/miniconda3/envs/snippyenv/binaries/noarch/any2fasta
Found samtools - /home/adm-loc/miniconda3/envs/snippyenv/bin/samtools
Found minimap2 - /home/adm-loc/miniconda3/envs/snippyenv/bin/minimap2
Found bedtools - /home/adm-loc/miniconda3/envs/snippyenv/bin/bedtools
Found snp-sites - /home/adm-loc/miniconda3/envs/snippyenv/bin/snp-sites
Saving reference FASTA: core.ref.fa
This is any2fasta 0.4.2
Opening 'CAS-NAD-13-1.gbk'
Detected GENBANK format
Read 245860 lines from 'CAS-NAD-13-1.gbk'
Wrote 1 sequences from GENBANK file.
Processed 1 files.
Done.
Loaded 1 sequences totalling 7087087 bp.
Will mask 0 regions totalling 0 bp ~ 0.00%
0	CAS-NAD-13-2	snp=3	del=3	ins=1	het=693	unaligned=84561
1	CAS-NAD-13-3	snp=3	del=3	ins=1	het=338	unaligned=84804
2	CAS-NAD-13-4	snp=3	del=3	ins=1	het=481	unaligned=84634
3	CAS-NAD-13-5	snp=4	del=3	ins=1	het=299	unaligned=85296
4	CAS-NAD-21-1	snp=3	del=3	ins=1	het=104	unaligned=85800
5	CAS-NAD-21-2	snp=4	del=23	ins=1	het=1106	unaligned=84303
6	CAS-NAD-21-3	snp=3	del=3	ins=1	het=1945	unaligned=83739
7	CAS-NAD-21-4	snp=4	del=3	ins=1	het=484	unaligned=84638
8	CAS-NAD-21-5	snp=3	del=3	ins=1	het=1197	unaligned=85239
9	CAS-NAD-53-1	snp=3	del=3	ins=1	het=887	unaligned=84430
10	CAS-NAD-53-2	snp=3	del=3	ins=1	het=1168	unaligned=84053
11	CAS-NAD-53-3	snp=3	del=3	ins=0	het=687	unaligned=444109
12	CAS-NAD-53-4	snp=4	del=3	ins=1	het=744	unaligned=84813
13	CAS-NAD-53-5	snp=5	del=3	ins=0	het=1068	unaligned=444458
Opening: core.tab
Opening: core.vcf
Processing contig: ctg.s1.000000F.arrow
Generating core.full.aln
Creating TSV file: core.txt
Running: snp-sites -c -o core.aln core.full.aln
Run 'snp-sites -b -c -o phylo.aln core.full.aln' for IQTree, BEAST, RaxML
Done.

**Comment by tseemann** [comment]
`snippy-core` 4.x does not put any annotations in the `core.*` files.

The main issue is what the annotation should be.
There could be 4 different bases at any core site - one 'reference' and 3 alternatives.
A `snpEff` annotation for the whole site does not make sense.

If you only want the gene labelled, you can use a GFF version of your reference, and use `bedtools intersect` to combine that somehow.

**Comment by marieleoz** [comment]
Hi Torsten,

Thanks for your answer; all I need is to label genes indeed. I will try to find a way to do this, I don't know what 'bedtools intersect' is but thanks for the suggestion. You may want to update the "Output Files" table in the "Core SNP phylogeny section of https://github.com/tseemann/snippy, which specifies that the .tab file comes with annotations. 

Best,
Marie

Le Dimanche 1 Décembre 2019 09:10 CET, Torsten Seemann <notifications@github.com> a écrit:

**Comment by tseemann** [comment]
@marieleoz thank you for letting me know about my error in documentation. i have fixed it now!

**Comment by mabouelk** [comment]
Hi All, 

I have the same issue, I need to annotate the core file. Is there anyone can help me?
