### ISSUE TITLE
View bam file on Tablet

### ISSUE THREAD

**Issue by maingoclanmaingoclan** [tseemann/snippy#342]
Hello Torsten,
I have used reference genome with the file type .gbff to get SNP with the gene information in snippy results. However, when I want to view the snps.bam file in Tablet, it does not work. 
If I use the reference genome with the file type .fna, I can not get the SNP with the gene name in .csv file but I could view the SNPs on Tablet.
So If I want to get the gene information and to view the SNP on graph, I have to run snippy twice. 
Is there any way that I just need to run once and get both?
Thank you.

**Comment by tseemann** [comment]
If you use `.gbff` reference, Snippy will create the `ref.fa` version of it in FASTA format.  Use `ref.fa` and `snps.bam` with Tablet.

**Comment by maingoclanmaingoclan** [comment]
Yep. It works. Thank you very much.
