### ISSUE TITLE
--minfrac 0?

### ISSUE THREAD

**Issue by cizydorczyk** [tseemann/snippy#343]
Hi Torsten,

Just out of curiosity, what does `--minfrac 0` do? That is, what does setting --minfrac to AUTO do? I tested it vs. `--minfrac 0.9` and got slightly different results, so I'm assuming it's not just setting this value to 0.9? (Snippy v4.4.3)

Any response is greatly appreciated!

Thank you,
Conrad

**Comment by tseemann** [comment]
The only place `--minfrac` is used is here:
```
FMT/GT="1/1" && QUAL>=$minqual && FMT/DP>=$mincov && (FMT/AO)/(FMT/DP)>=$minfrac
```
ie. just ensures that the alternate allele is called more than `--minfrac` proportion of the time. 

if it set to 0, it will allow any variant through that satisfies the other conditions - namely `GT` (genotype),. `--minqual` and `--mincov`.  The `--minqual` default will not allow low alternate allele counts, so you would get sumilar results to 0.9 say.  The QUAL comes from the statistical model from inside Freebayes. And for GT=1/1 to be called, you'd need at least >70% alternate allelle say.

So `AUTO` really means "let freebayes do whatever it wants" ... but it is still filtered on quality and coverage. There are also some other hidden freebayes defaults that _also_ ensure only real looking things are called.

This was a very good question, and I will try and augment the documentation explaining some of this.

**Comment by alswajiab** [comment]
Hi Torsten,
To follow on this topic
I am wondering if the GT value should be set to either 1/1 or 0/1. Otherwise if you select an `--minfrac` < 0.9 you would expect the GT value to be rather 0/1 and therefore you are not going to see any difference between `--minfrac` 0.8, 0.75 or 0.7 as all variants in this case are going to be called as "n" (based on my experience).

Please correct me if I am wrong.
Thank you.

**Comment by tseemann** [comment]
The reported genotype is always GT=0 or GT=1.   I call in diploid mode to identify mixed sites that may otherwise be classified GT=1 under a haploid model (incorrectly).  

You are right that having `--minfrac` < 0.8 or so is unlikely to produce GT=1
