### ISSUE TITLE
Using --bam

### ISSUE THREAD

**Issue by peflanag** [tseemann/snippy#345]
Hi,

We have .bam files that collaborators sent to us that we want to analysis. Due to the way they generated their bam files we cannot convert back to fastq in the R1 and R2 format as one sample contains two .bam files mixed with the R1 and R2 reads. We have merged these into one .bam file and ran snippy. However we have gotten this error and I was wondering if you could tell me what it means? Do I need to edit the .py file?

Thanks

### samtools view -h -O SAM \/Users\/peterflanagan\/IMRL_Sequencing\/Illumina\/Test_fastq\/Fastq\/IMRLH83\.bam | samclip --max 10 --ref reference/ref.fa.fai | samtools sort -n -l 0 -T /private/var/folders/yw/9tmv96yx73ld2r712hclgjv00000gn/T --threads 15 -m 266M | samtools fixmate -m - - | samtools sort -l 0 -T /private/var/folders/yw/9tmv96yx73ld2r712hclgjv00000gn/T --threads 15 -m 266M | samtools markdup -T /private/var/folders/yw/9tmv96yx73ld2r712hclgjv00000gn/T -r -s - - > snps.bam

READ 2277016 WRITTEN 1059809 
EXCLUDED 12194 EXAMINED 2264822
PAIRED 2260500 SINGLE 4322
DULPICATE PAIR 1214644 DUPLICATE SINGLE 2563
DUPLICATE TOTAL 1217207

### fasta_generate_regions.py reference/ref.fa.fai 144681 > reference/ref.txt

  File "/usr/local/bin/fasta_generate_regions.py", line 7
    print "usage: ", sys.argv[0], " <fasta file or index file> <region size>"
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("usage: ", sys.argv[0], " <fasta file or index file> <region size>")?

**Comment by tseemann** [comment]
The final error is a wrong python version. Looks like your conda environment (?) is broken. it's got nothing to do with the BAM files.

You can convert BAM back to FASTQ uses `samtools fastq`. The help even gives an example:

```
Examples:
 To get just the paired reads in separate files, use:
   samtools fastq -1 paired1.fq -2 paired2.fq -0 /dev/null -s /dev/null -n in.bam
```

**Comment by peflanag** [comment]
Cheers i'll look at my python. I cant change to fastq because the guys that made the bam have two files for one sample that doesn't correspond to R1 and R2. It looks like each is a mixture of both separated by the channels/lanes on the flowcell. It's really weird, I've never seen it before.

**Comment by peflanag** [comment]
@tseemann re-made the conda environment and its fine! Thanks for your help, I appreciate it!
