### ISSUE TITLE
snippy-core issue from snippy using .bam as input

### ISSUE THREAD

**Issue by peflanag** [tseemann/snippy#346]
Hi,

I have a selection of .bam files that I ran snippy on. After it ran, I tried to run snippy-core but it failed with the following error:

ERROR: Could not find .aligned.fa/.vcf in /path/to/folder

Does snippy-core not work with the output of .bam inputs? I also have converted the .bam into fastq but its a single fastq file that cannot be split into R1 and R2. Can i use the single fastq file to run snippy and snippy-core?

**Comment by tseemann** [comment]
You can use `samtools fastq` to get R1 and R2 from a BAM if you need to.

Do you have files called `snps.aligned.fa` and `snps.vcf` in all the folders you are providing to `snippy-core`?

You are probably the first person to ever use the `--bam` options so it is not really tested. Is your sequencing provider not giving you R1 and R2 files?

**Comment by peflanag** [comment]
These are old files that a provider sequenced for us but they convert everything to bam. However we can’t convert back to fastq cause if they way they made the bam. They split them into two bam files we had to merge and then generate a single fastq. The name Int system seems to lack the info for us to generate R1 and R2. I don’t quite understand it. But needless to say samtools won’t work! That’s why I was hoping the bam files would work. 

But the —bam option doesn’t seem to have generated the .fa or vcf files from what I remember. Unfortunately I can’t log into the machine in question to check at the moment

**Comment by peflanag** [comment]
Hey @tseemann happy new year! I've only just got access onto my machine again and to answer your question I only have the snps.aligned.fa files. Just the ones in the screenshot below. 

<img width="617" alt="Screenshot 2020-01-03 at 08 43 09" src="https://user-images.githubusercontent.com/32863969/71714322-4d9bed00-2e05-11ea-954f-a4ad46f1edb3.png">

**Comment by tseemann** [comment]
I am unsure why the `--bam` option does not generate an output.
BAM files come in two flavours - aligned, and unaligned. 
If yours are unaligned, then it will probably not work.
You will need to use `samtools fastq` to extract out the reads.

**Comment by ktmeaton** [comment]
I just wanted to say you have at least one other user that uses the --bam input flag! I've never come across any errors so far in using them for snippy and snippy-core. If it helps, @peflanag I can provide some additional info about my usage of bam inputs to help troubleshoot?

**Comment by peflanag** [comment]
Hey @ktmeaton cheers for the message! I managed to get them all working in the end. It was only a handful of files that where sent to my by a collaborator. I managed to convert back to a single fastq file and used it as a SE read for the input.

**Comment by tseemann** [comment]
@ktmeaton i appreciate the feedback regarding `--bam`!  I was never sure if it was ok or not.
