### ISSUE TITLE
RNA-seq through snippy

### ISSUE THREAD

**Issue by biobenkj** [tseemann/snippy#347]
Hi @tseemann! I'm updating some old code from graduate school for pipelining RNA-seq processing and wanted to add a variant calling layer. Do you think there would be some significant "gotchas" for feeding snippy bacterial RNA-seq fastq or BAM files to call variants?

Thanks so much for your time!

**Comment by tseemann** [comment]
We have called SNPs from RNA seq data before, where no WGS was available.
It mostly works.
The only caveat is depth - if a transcript has depth < 10 then it won't be called due to --mincov 10.
