### ISSUE TITLE
Old snippy vs new snippy

### ISSUE THREAD

**Issue by labrat9** [tseemann/snippy#349]
I have two versions of snippy, both were installed together with nullarbor, one was via brew (nullarbor v1) and the other via conda (nullarbor v2).

When I analysed the same set of data using both, I got two different results. It seems that snippy in nullarbor v2 is more stringent than the one implemented in nullarbor v1 (higher support for indels in nullarbor v1). May I please find out what modifications that make nullarbor v2 more stringent?

Thank you.

**Comment by tseemann** [comment]
Snippy does not come with nullarbor.
Nullarbor 1 and 2 both work with Snippy 3 or 4.
Please use Snippy >= 4.4 because older versions had some serious bugs.
