### ISSUE TITLE
Discrepancy in #SNPs reported among different variant callers

### ISSUE THREAD

**Issue by drish91** [tseemann/snippy#350]
Hi Torsten, 
This is on the same lines as issue #160 , maybe I'm missing this in the documentation, but is there a way to use previously mapped-sam files from another pipeline (like samtools/bbmap) as input and then use snippy for variant filtering, consensus and downstream alignment?

The reason I ask is because I used bbmap for calling variants and bcftools for downstream filtering, but the results are much more comprehensive than when I re-did the analysis using snippy for the same purpose. There are a lot of vcfs reported in the bbmap results that don't show up in the snippy results, and I was wondering if that was because of the stringency of parameters. So, I thought it would be great if I could use the SNPs previously detected and do the downstream parsing and core phylogenetic analysis with snippy?

Thanks,
Drishti

**Comment by tseemann** [comment]
The help says you can provide a BAM file:
```
SYNOPSIS
  snippy 4.4.6 - fast bacterial variant calling from NGS reads
USAGE
  snippy [options] --outdir <dir> --ref <ref> --R1 <R1.fq.gz> --R2 <R2.fq.gz>
  snippy [options] --outdir <dir> --ref <ref> --ctgs <contigs.fa>
  snippy [options] --outdir <dir> --ref <ref> --bam <reads.bam>

  --bam F          Use this BAM file instead of aligning reads (default '')

```
