### ISSUE TITLE
SNIPPY using using genbank with --ref

### ISSUE THREAD

**Issue by Munnj90** [tseemann/snippy#351]
Hi Torsten,

I'm currently attempting to run SNIPPY using a genbank file for --ref.  Using all the same data and the equivalent FASTA file for --ref works nicely.  I used the genbank (full) for S. coelicolor downloaded from NCBI:

https://www.ncbi.nlm.nih.gov/nuccore/NC_003888.3

The snps.log file has this warning in it:

WARNING: All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate.

It fails to generate the usual complement of files giving only:

drwxrwxr-x 4 ubuntu ubuntu       204 Jan 17 12:36 reference
lrwxrwxrwx 1 ubuntu ubuntu        16 Jan 17 12:30 ref.fa -> reference/ref.fa
lrwxrwxrwx 1 ubuntu ubuntu        20 Jan 17 12:30 ref.fa.fai -> reference/ref.fa.fai
-rw-rw-r-- 1 ubuntu ubuntu 687553403 Jan 17 12:36 snps.bam
-rw-rw-r-- 1 ubuntu ubuntu     30624 Jan 17 12:36 snps.bam.bai
-rw-rw-r-- 1 ubuntu ubuntu     17840 Jan 17 12:38 snps.filt.vcf
-rw-rw-r-- 1 ubuntu ubuntu      2731 Jan 17 12:38 snps.log
-rw-rw-r-- 1 ubuntu ubuntu     92317 Jan 17 12:38 snps.raw.vcf
-rw-rw-r-- 1 ubuntu ubuntu         0 Jan 17 12:38 snps.vcf

Any help would be appreciated.
John.

**Comment by cizydorczyk** [comment]
I get a similar warning in my snps.log files when using a .gbk file (full) downloaded from NCBI, but I get the full set of files and SNPs in the final .vcf are annotated. Weird...

**Comment by tseemann** [comment]
That warning is from a bug in your version of `snpEff`.
It does not seem to affect the results.
I agree it is annoying.
it comes from the `PHASE` column in the GFF file i create from the GBK file.
Different snpEff seem to interpret it differently.
