### ISSUE TITLE
Snippy-Core --ref

### ISSUE THREAD

**Issue by peflanag** [tseemann/snippy#352]
Hi @tseemann how are you? I'm just wondering, do you have to specify --ref when running snippy-core? I use to because I got this error when I'd leave it out;

<img width="631" alt="Screenshot 2020-01-21 at 09 46 24" src="https://user-images.githubusercontent.com/32863969/72793857-e8ccf900-3c32-11ea-937b-0b32825184e1.png">

But now I am comparing my Snippy.aln file with the output from MTBseq and when I look at the tress using RAxML they are different which I assume is down to the fact of the --ref option?

<img width="796" alt="Screenshot 2020-01-21 at 09 48 02" src="https://user-images.githubusercontent.com/32863969/72794023-334e7580-3c33-11ea-8750-179d3c2a676c.png">
<img width="963" alt="Screenshot 2020-01-21 at 09 48 19" src="https://user-images.githubusercontent.com/32863969/72794025-334e7580-3c33-11ea-8695-56b86c6410e5.png">

I suppose my question is can I remove the reference somehow in snippy?

Cheers.

**Comment by tseemann** [comment]
Snippy-core requires the reference because reasons (it needs to consolidate all the VCF files and they are relative to the reference).

You are free to remove it from `snps.full.aln` afterwards, and re-run `snp-sites` etc yourself.

**Comment by peflanag** [comment]
Thanks @tseemann i appreciate it!
