### ISSUE TITLE
snippy-v4.4.5 compatibility with Samtools-v1.10

### ISSUE THREAD

**Issue by wshropshire** [tseemann/snippy#357]
Hello, 

I just noted that there is a new release of Samtools from December. I note that the parse_version function checks for samtools >= 1.7 and notes 1.10 as too low. 

Before I try to manually fix the code locally, just wanted to know if you are aware of any issues with compatibility with this new version of samtools? Similarly, would this be a problem with bcftools-v1.10.2. If so, I'll just use the older versions. 

Best, 

Will

**Comment by wshropshire** [comment]
Sorry, I see this issue has already been raised. I'll close

**Comment by tseemann** [comment]
It's fixed now.

**Comment by wshropshire** [comment]
Awesome, thanks for letting me know!
