### ISSUE TITLE
Question: Multiple Snippy Outputs for Snippy-core

### ISSUE THREAD

**Issue by peflanag** [tseemann/snippy#361]
Hi,

I have a number of folders where I have grouped samples according to clusters and ran snippy followed by snippy-core and generated a newick file in RaxML and then made an MLT. This has resulted in 20 different MLTs. 

However, now I want to make one big tree with all the clusters merged. I assumed I could just take the outputs of snippy and run them all together in snippy-core to get one core.aln file to use in RAxML online to make a newick file and then my MLT in GrapeTree. 

This doesn't seem to have worked in the sense that the output snippy-core file just seems to be identical and doesn't show the different clusters all on one tree. 

Can anyone tell me what I am doing wrong? Hopefully I have made clear what I am trying to do! I basically want a way that if I want to compare different clusters quickly on an MLT I can.

Cheers,

Peter

**Comment by tseemann** [comment]
Did you use the SAME reference for each of the snippy cluster-specific analyses?

**Comment by peflanag** [comment]
I do use the same ref. Each cluster has a folder and in it there’s a fastq input folder the reference file and a masked bed file as well as the core output. 

I then copied the output of each —snippy run into one new combined folder to run snippy core collectively for one massive output.

**Comment by tseemann** [comment]
There should not be any need to copy data.
`snippy-core` just takes a list of folders.
You can run it as many times as you want on different subsets of all those folders.
They don't need to be within the same folder.
Just make sure you use a different `--prefix` so the output files don't overwrite.

Imagine you ran 26 snippys:
```
% ls
A B C D ........ Z  ref.fa

$ snippy-core --ref ref.a  --prefix set1  A C E L U X

$ snippy-core --ref ref.a  --prefix set2  I K N O W

$ snippy-core --ref ref.a  --prefix set3  B D F G H L M P Q R S T
```

**Comment by peflanag** [comment]
So I think the error was that I actually had 4 M. bovis samples in my 325 dataset! I removed them and now I can see the differences between the samples!

**Comment by peflanag** [comment]
So I think the issue was because I had 4 M. bovis samples in my 325 data set! All the samples where coming back as identical until i removed them!

**Comment by tseemann** [comment]
Yes, that's always the issue - some bad/outlier samples. Always use `make preview` first.
