### ISSUE TITLE
huge number of variants

### ISSUE THREAD

**Issue by marsurro** [tseemann/snippy#363]
Hi,

I'm kinda new on using **snippy**. I have some WGS bacterial samples that I try to do variant analysis onto.
I use the following dependencies:
**samtools --version is >= 1.7 - ok, have 1.9
bcftools --version is >= 1.7 - ok, have 1.9
freebayes --version is >= 1.1 - ok, have 1.3
java -version is >= 1.8 - ok, have 1.8
snpEff -version is >= 4.3 - ok, have 4.3
bwa is >= 7.12 - ok, have 7.17**

When running snippy on one _Acinetobacter baumannii_ sample I use the following command:
**snippy --cpus 16 --report --outdir sample1_snippy --ref Ab.gbff --contigs sample1/contigs.fa &**

This is a part of the output that I'm getting:
_options:     input VCF file                                  -
         [o] output VCF file                                 -
         [w] sorting window size                             10000
         [m] no fail on masked reference inconsistency       false
         [n] no fail on reference inconsistency              false
         [q] quiet                                           false
         [d] debug                                           false
         [r] reference FASTA file                            reference/ref.fa

stats: biallelic
          no. left trimmed                      : 85
          no. right trimmed                     : 486
          no. left and right trimmed            : 69
          no. right trimmed and left aligned    : 0
          no. left aligned                      : 0

       total no. biallelic normalized           : 640

       multiallelic
          no. left trimmed                      : 0
          no. right trimmed                     : 0
          no. left and right trimmed            : 0
          no. right trimmed and left aligned    : 0
          no. left aligned                      : 0

       total no. multiallelic normalized        : 0

       total no. variants normalized            : 640
       total no. variants observed              : 46626
       total no. reference observed             : 0_

Therefore, I have some questions I haven't found an answer yet:
1. Why do I get this huge number of variants? 
2. What is the difference between normalized and observed variants? Should I take into account only the normalized ones?
3. How do I select only the normalized ones?

P.S. I use the contigs file as the output from shovill assembly. On the other hand, when using the PE raw reads, I get the same huge number of variants.

Hope you could help me clear these problems.

Thank you so much!

Regards,
Marius

**Comment by tseemann** [comment]
1.  60k variants is not unusual in A.baumannii between a random reference and a random isolate. You probably just have a distant reference. 60k SNPs in a 6Mbp genome is only 1% divergence. What makes you think the answer is wrong? 

2. the 'vt' command just cleans up the (insertion and deletion and MNP) REF/ALT columns in the VCF to make them consistent. You had 60,000 variants, but only 600 of them needed cleaning up.

3. you don't want to do that. you would probably only get (some) of your indels, and SNPs would disappear

4. never use assembled contigs in Snippy if you have the original FASTQ reads available. You will lose sensitivity and introduce false SNPs from assembly artifacts.

**Comment by marsurro** [comment]
Thank you so much for the clarifying! 
Best regards!
