### ISSUE TITLE
Update taxa name in .consensus.fa and .consensus.subs.fa based on base name of mapped reads

### ISSUE THREAD

**Issue by EpiDemos82** [tseemann/snippy#366]
I noticed that the .consensus.subs.fa and .consensus.fa use the reference name as taxon name in the fasta file preventing a simple *.fasta > msa.fasta operation.  This is relatively easy to address in post analysis, but if it is of general agreement that the base name of the mapped reads file is appropriate, than perhaps this could be included with future updates.  Again... super small, not even an issue, just cleans up the workflow.  Thanks again!

**Comment by tseemann** [comment]
Yes, it uses the contig names present in the reference.
I assume you only have 1 contig (maybe a single chromosomal reference) ?
What would happen if you had the plasmids too?

**Comment by EpiDemos82** [comment]
So having just read snippy-multi and snippy-core info in more detail, snippy-core outputs a core SNP alignment, correct?  My usual workflow for recombinogenic bacteria is ref-based alignment -> MSA -> Gubbins -> SNP alignment with recombined sites masked. For this I would almost always be using a reference with a single contig without the plasmid in gbk format (great feature by the way!).  However, considering you also made Snippy handy for assembly polishing, I could see why you wouldn't necessarily want to update the contig names in the file.  A solution would be to have a separate --ID flag to rename the contig. Again, this is pretty simple to do post-hoc.  So if doing this compromises other use cases, then it is not worth undertaking.

**Comment by tseemann** [comment]
I always include the plasmids in my reference genome, but mask them in snippy-core. This is to ensure plasmid reads get assigned properly to the plasmid, and not accidently mapped to the chromosome. A simple `--mask` file for snippy-core with the plasmid entries ensures they don't participitate in the core. 

We also work reguarly with other organisms with more than one chromosome. eg. Leptospira, Burkholderia etc.  and fungi.

Best for you to just have that feature in your pipeline I think.
