### ISSUE TITLE
Core genome snp number and phylogenetic tree

### ISSUE THREAD

**Issue by Galib009** [tseemann/snippy#368]
Hi,
I have run snippy and snippy-core on 30 isolates and generated .aln , .tab, .txt, .vcf files. now, I am interested to know the core genome snp numbers and  generate Phylogenetic tree.
I am sorry if it is naive question as i am new to this.
Thanks in advance!

**Comment by tseemann** [comment]
the number of letters in each entry of the core.aln file is the number of core SNPs.
