### ISSUE TITLE
how to know the Number of core genome SNPs

### ISSUE THREAD

**Issue by Galib009** [tseemann/snippy#369]
Hi! 
i used snippy and snippy-core on 30 isolates and generated .aln , .tab , .vcf files.  i just want to know the number of core genome snps.
Thanks in advance.

**Comment by tseemann** [comment]
Two ways:

1. look at the sequence length of each sequence in `core.aln`
```
seqkit stats core.aln 
file      format  type  num_seqs  sum_len  min_len  avg_len  max_len
core.aln  FASTA   DNA          8      120       15       15       15
```
8 samples, each with 15 core snps.

2. Run `wc -l core.tab` and subtract 1 (for the header line)
```
wc -l core.tab 
16 core.tab
```
