### ISSUE TITLE
Using snippy on yeast data?

### ISSUE THREAD

**Issue by sn0001** [tseemann/snippy#374]

**Comment by sn0001** [comment]
@tseemann, would you recommend using snippy on sequencing data from (diploid) yeasts? What tweaks would be necessary to obtain valid results?

**Comment by tseemann** [comment]
If you know it is definitely diploid, then do not use Snippy.
It will only report homozygous SNPs in the final results.
You _could_ use `snps.raw.vcf` but you would need to do your own filtering.
