### ISSUE TITLE
run snpEFF on core_genome.vcf from fasta by giving genbank

### ISSUE THREAD

**Issue by mattbawn** [tseemann/snippy#375]
Hi Torsten,

I was just wondering if there was a way to run snpEFF on core_genome.vcf that was generated from a fasta reference and is therfore unannotated, by giving a genbank reference?

Thanks,

Matt

**Comment by tseemann** [comment]
Not easily.... snpEff is a pain to get working.

If you run a single snippy run on one sample with the GBK file, that will generate the required files in the `reference/` folder in the `--outdir`

Then, look at `snps.log` for the commands for running snpEff.

Then use that as a template to run snpEff on all the samples you already ran.

That's my best suggestion (besides running them all from scratch).
