### ISSUE TITLE
How to input snippy result to PHYLOviz to view the tree?

### ISSUE THREAD

**Issue by mingjuhao** [tseemann/snippy#378]
I followed every step to the last. However, i can't get a beautiful tree as published in the paper. PHYLOviz is a good viewer and it has the functin to do the snp tree. But the format is different from snippy result. So i am wondering if I can get a tree in PHYLOviz from snippy report? If not, then what software is suitable for snippy? Thanks!

**Comment by tseemann** [comment]
You can produce a Newick tree file from the `snippy-core` output using many tools:
```
iqtree -s core.aln -pre iqtree -m GTR+G4   # use "iqtree.treefile"
FastTree -gtr -nt core.aln > tree.nwk  # use "tree.nwk"
```

The author of Phyloviz suggests these links:
* https://github.com/nickloman/misc-genomics-tools/blob/master/scripts/vcf2phyloviz.py
* http://userweb.eng.gla.ac.uk/cosmika.goswami/snp_calling/SNPCalling.html
