### ISSUE TITLE
Combination of gubbins + snps-sites + FastTree for tree calculation

### ISSUE THREAD

**Issue by Lneffe** [tseemann/snippy#384]
Hi everyone!
My question relates to the suggested workflow after using snippy-core:
for the detection of recombination in the full length alignment the tool gubbins is suggested. 
this step produces a Max Likelihood phylogenetic tree (by default a with raxML) in the last step which does not contain recombinant regions.
What is the advandage of using snp-sites and FastTree additionally over the "gubbins tree"?

**Comment by conmeehan** [comment]
Hi there,
I think the ML tree from RAxML or IQ-TREE after recombination is removed will be sufficient and perhaps more accurate than the FastTree approach. However, it is just about whether RAxML or FastTree is a 'better' program which is a constant debate. Thus, I think going with the ML tree from Gubbins could suffice.

**Comment by tseemann** [comment]
One prominent phylogeneticist told me they reject any paper that uses FastTree. YMMV.
