### ISSUE TITLE
How many core SNPs I obtained?

### ISSUE THREAD

**Issue by Asylulan** [tseemann/snippy#386]
How many core SNPs I obtained?

Hello, can you to suggest to me, how I can check how many core SNPs I obtained through analysis, for used in phylogenetic tree...
I think, that I can to count nucleotides in core.aln or core.tab files. Is it right?

**Comment by tseemann** [comment]
It's a fair question and you are right about counting the size/length of the alignment in core.aln.
There are various ways you could do that, but it depends on what other tools you have installed.

```
fa -f core.aln | head -n 1 | cut -f 3

esl-alistat core.aln | grep 'Alignment length:'

echo $(( $(seqtk seq core.aln | sed -n '2p;' | wc -c) - 1 ))
