### ISSUE TITLE
Snippy core VCF / alignment

### ISSUE THREAD

**Issue by esteinig** [tseemann/snippy#388]
Hey all, are the number of sites in the `VCF` output from `snippy-core` always the same as the number of sites in the output alignment, (`core.aln`) or can there be a difference? I process some things downstream and just want to make sure that it works from the `VCF` directly.

Thanks so much, always a pleasure to use `Snippy` :)

**Comment by tseemann** [comment]
The VCF file contains indels, snps and 'complex' variants.
The number of columns in core.aln will NOT match the number of entries in the VCF.

For example, a complex variant `TAC => GAG` will cause 2 sites in core.aln.

**Comment by esteinig** [comment]
Ah that's good to know thanks Torsten. Makes sense.

**Comment by esteinig** [comment]
Hey Torsten - apologies to bug you on this again.

Can I ask if `COMPLEX` variants like this are considered at all or are they excluded as insertion / deletion?

```
AAAAG   TTCC    2464.56  .   AB=0;AO=91;DP=91;QA=3109;QR=0;RO=0;TYPE=complex
```

Does this block have anything to do with this?

```bash
if ($r ne $gap_char) {
  $var{$chr}{$pos+$i}{$id} = $a;  # ALT is [ATGC-]
  $a eq '-' ? $ndel++ : $nsnp++;
}
```

Thanks heaps!

**Comment by tseemann** [comment]
I believe yes they are considered.
It will be treated as 4 SNPs and 1 deletion.
Is this the right thing biologically and to treat it as such? Who knows.

````
REF AAAAG
ALT TTCC-
```
If you have evidence it is not doing that. let me know.
There has been another report  recently of deletions not being propogated.

**Comment by esteinig** [comment]
Legend! I was trying to recreate the function in Python and was wondering why there were too few SNPs, but had excluded reference and alternative alleles that did not match in length.

Will do! Thanks for the great work and taking the time to respond.
