### ISSUE TITLE
how to parse all of the variants for specific gene/product in over than 2000 viral genomes sequences

### ISSUE THREAD

**Issue by mabouelk** [tseemann/snippy#390]
Hi, 

I got the output for each viral genome with the annotation but I am interested in one gene and I need to know all of the Variant for this specific gene/product among all of the samples.

**Comment by tseemann** [comment]
:warning: was your genome FASTQ derived from a multiplex PCR amplicon system? If so, did you trim all primer sequences? If not, then all your results are probably invalid.

**Comment by mabouelk** [comment]
No, they are fasta files.

**Comment by tseemann** [comment]
You should probably align the FASTA files directly with `mafft` or `clustalo` and then find the variants in some other way.  Snippy is the the correct tool for this job. Even I did not use it for my own COVID-19 work with 1500 samples.

**Comment by mabouelk** [comment]
are there any alternative tools that can do all of that? 

I can do clustal or mafft alignment but I am excited to use one of your great tools regarding that

**Comment by tseemann** [comment]
My great tools don't work for this grant problem unfortunately.

**Comment by mabouelk** [comment]
Sorry for asking about an unrelated topic, do you know a good tool(s) for virus detection/ screening in RNAseq?

**Comment by tseemann** [comment]
`kraken2` might work.
