### ISSUE TITLE
Error running command

### ISSUE THREAD

**Issue by mingjuhao** [tseemann/snippy#391]
Hi, tseemann, thanks for your great snippy!
It all worked well several days ago. However, it stopped here today. Even i ran the same sequences as before. It also happened.
[13:25:00] Running: snpEff ann -noLog -noStats -no-downstream -no-upstream -no-utr -t -c reference/snpeff.config -dataDir . ref snps.filt.vcf > snps.vcf 2>> snps.log
[13:25:02] Error running command, check yujiaosnp/snps.log
the snps.log said this:
### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.07 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 2.11 seconds elapse.
[bwa_index] Update BWT... 0.05 sec
[bwa_index] Pack forward-only FASTA... 0.04 sec
[bwa_index] Construct SA from BWT and Occ... 0.82 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index reference/ref.fa
[main] Real time: 3.499 sec; CPU: 3.088 sec

### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

WARNING: All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate.

### bwa mem  -Y -M -R '@RG\tID:yujiaosnp\tSM:yujiaosnp' -t 16 reference/ref.fa /home/hao/hao/Sequencingdata/cleanfq/yujiao/CRPA-011_1.fq.gz /home/hao/hao/Sequencingdata/cleanfq/yujiao/CRPA-011_2.fq.gz | samclip --max 10 --ref reference/ref.fa.fai | samtools sort -n -l 0 -T /tmp/s
nippy.9632. --threads 16 -m 500M | samtools fixmate -m - - | samtools sort -l 0 -T /tmp/snippy.9632. --threads 16 -m 500M | samtools markdup -T /tmp/snippy.9632. -r -s - - > snps.bam

READ 6562203 WRITTEN 6185685 
EXCLUDED 874360 EXAMINED 5687843
PAIRED 5620138 SINGLE 67705
DULPICATE PAIR 346866 DUPLICATE SINGLE 29652
DUPLICATE TOTAL 376518

### snpEff ann -noLog -noStats -no-downstream -no-upstream -no-utr -t -c reference/snpeff.config -dataDir . ref snps.filt.vcf > snps.vcf

Thanks for your response!

**Comment by tseemann** [comment]
Probably a Java issue, and snpEff is sensitive to Java. I think some people need to use an older 1.8 (or 8) version.

**Comment by mingjuhao** [comment]
Thanks for your prompt response. I changed the reference from gbk to fasta. It works again. I will change the java version and have a try.

**Comment by tseemann** [comment]
```
conda update --all 
```
sometimes helps

```
conda install java=1.8  # maybe?
```

**Comment by mingjuhao** [comment]
conda update --all  didn't work for my computer.
I create a new conda enviroment and install java version 1.8. It works perferctly!
