### ISSUE TITLE
Error: Failed to set region: ; ERROR(freebayes): Could not SetRegion

### ISSUE THREAD

**Issue by SShaminur** [tseemann/snippy#393]
Here are the details of my error. My command was "snippy --outdir mysnps --ref test.gbk --ctgs sequence.fna"

### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.07 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.01 sec
[bwa_index] Construct SA from BWT and Occ... 0.05 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index reference/ref.fa
[main] Real time: 0.466 sec; CPU: 0.140 sec

### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

WARNING: All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate.

### bwa mem  -Y -M -R '@RG\tID:mysnps\tSM:mysnps' -t 8 reference/ref.fa fake_reads.fq | samclip --max 10 --ref reference/ref.fa.fai | samtools sort -n -l 0 -T /tmp/snippy.15123. --threads 8 -m 1000M | samtools fixmate -m - - | samtools sort -l 0 -T /tmp/snippy.15123. --threads 8 -m 1000M | samtools markdup -T /tmp/snippy.15123. -r -s - - > snps.bam

READ 0 WRITTEN 0 
EXCLUDED 0 EXAMINED 0
PAIRED 0 SINGLE 0
DULPICATE PAIR 0 DUPLICATE SINGLE 0
DUPLICATE TOTAL 0

### freebayes-parallel reference/ref.txt 8 -p 2 -P 0 -C 10 --min-repeat-entropy 1.5 --strict-vcf -q 13 -m 60 --min-coverage 10 -F 0.05  -f reference/ref.fa snps.bam > snps.raw.vcf

Error: Failed to set region: -1:0-11,878(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:0..11878
Error: Failed to set region: -1:11,878-23,756(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:11878..23756
Error: Failed to set region: -1:23,756-35,634(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:23756..35634
Error: Failed to set region: -1:35,634-47,512(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:35634..47512
Error: Failed to set region: -1:47,512-59,390(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:47512..59390
Error: Failed to set region: -1:59,390-71,268(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:59390..71268
Error: Failed to set region: -1:71,268-83,146(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:71268..83146
Error: Failed to set region: -1:83,146-95,024(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:83146..95024
Error: Failed to set region: -1:95,024-106,902(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:95024..106902
Error: Failed to set region: -1:106,902-118,780(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:106902..118780
Error: Failed to set region: -1:118,780-130,658(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:118780..130658
Error: Failed to set region: -1:130,658-142,536(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:130658..142536
Error: Failed to set region: -1:142,536-154,414(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:142536..154414
Error: Failed to set region: -1:154,414-166,292(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:154414..166292
Error: Failed to set region: -1:166,292-175,210(*)
ERROR(freebayes): Could not SetRegion to LBB_contig000001:166292..175210

### snpEff ann -noLog -noStats -no-downstream -no-upstream -no-utr -t -c reference/snpeff.config -dataDir . ref snps.filt.vcf > snps.vcf

Error: Multi-threaded opton not supported in this version!

SnpEff version SnpEff 4.5covid19 (build 2020-04-15 22:26), by Pablo Cingolani
Usage: snpEff [command] [options] [files]

Run 'java -jar snpEff.jar command' for help on each specific command

Available commands: 
	[eff|ann]                    : Annotate variants / calculate effects (you can use either 'ann' or 'eff', they mean the same). Default: ann (no command or 'ann').
	build                        : Build a SnpEff database.
	buildNextProt                : Build a SnpEff for NextProt (using NextProt's XML files).
	cds                          : Compare CDS sequences calculated form a SnpEff database to the one in a FASTA file. Used for checking databases correctness.
	closest                      : Annotate the closest genomic region.
	count                        : Count how many intervals (from a BAM, BED or VCF file) overlap with each genomic interval.
	databases                    : Show currently available databases (from local config file).
	download                     : Download a SnpEff database.
	dump                         : Dump to STDOUT a SnpEff database (mostly used for debugging).
	genes2bed                    : Create a bed file from a genes list.
	len                          : Calculate total genomic length for each marker type.
	pdb                          : Build interaction database (based on PDB data).
	protein                      : Compare protein sequences calculated form a SnpEff database to the one in a FASTA file. Used for checking databases correctness.
	seq                          : Show sequence (from command line) translation.
	show                         : Show a text representation of genes or transcripts coordiantes, DNA sequence and protein sequence.
	translocReport               : Create a translocations report (from VCF file).

Generic options:
	-c , -config                 : Specify config file
	-configOption name=value     : Override a config file option
	-d , -debug                  : Debug mode (very verbose).
	-dataDir <path>              : Override data_dir parameter from config file.
	-download                    : Download a SnpEff database, if not available locally. Default: true
	-nodownload                  : Do not download a SnpEff database, if not available locally.
	-h , -help                   : Show this help and exit
	-noLog                       : Do not report usage statistics to server
	-q , -quiet                  : Quiet mode (do not show any messages or errors)
	-v , -verbose                : Verbose mode
	-version                     : Show version number and exit

Database options:
	-canon                       : Only use canonical transcripts.
	-canonList <file>            : Only use canonical transcripts, replace some transcripts using the 'gene_id 	 transcript_id' entries in <file>.
	-interaction                 : Annotate using inteactions (requires interaciton database). Default: true
	-interval <file>             : Use a custom intervals in TXT/BED/BigBed/VCF/GFF file (you may use this option many times)
	-maxTSL <TSL_number>         : Only use transcripts having Transcript Support Level lower than <TSL_number>.
	-motif                       : Annotate using motifs (requires Motif database). Default: true
	-nextProt                    : Annotate using NextProt (requires NextProt database).
	-noGenome                    : Do not load any genomic database (e.g. annotate using custom files).
	-noExpandIUB                 : Disable IUB code expansion in input variants
	-noInteraction               : Disable inteaction annotations
	-noMotif                     : Disable motif annotations.
	-noNextProt                  : Disable NextProt annotations.
	-onlyReg                     : Only use regulation tracks.
	-onlyProtein                 : Only use protein coding transcripts. Default: false
	-onlyTr <file.txt>           : Only use the transcripts in this file. Format: One transcript ID per line.
	-reg <name>                  : Regulation track to use (this option can be used add several times).
	-ss , -spliceSiteSize <int>  : Set size for splice sites (donor and acceptor) in bases. Default: 2
	-spliceRegionExonSize <int>  : Set size for splice site region within exons. Default: 3 bases
	-spliceRegionIntronMin <int> : Set minimum number of bases for splice site region within intron. Default: 3 bases
	-spliceRegionIntronMax <int> : Set maximum number of bases for splice site region within intron. Default: 8 bases
	-strict                      : Only use 'validated' transcripts (i.e. sequence has been checked). Default: false
	-ud , -upDownStreamLen <int> : Set upstream downstream interval length (in bases)

**Comment by tseemann** [comment]
```
READ 0 WRITTEN 0
EXCLUDED 0 EXAMINED 0
PAIRED 0 SINGLE 0
DULPICATE PAIR 0 DUPLICATE SINGLE 0
DUPLICATE TOTAL 0
```

No reads aligned to your reference genome.

**Comment by SShaminur** [comment]
Thank You Sir for your response.
I am going to clear all the input and command:

My input files are from [https://github.com/tseemann/snippy/tree/master/test] and they are example.gbk as reference and example.fna as the target. My command is according to your instruction (`snippy --maxsoft 150 --outdir mysnps --ref example.gbk --ctgs example.fna )`. 

I am getting the same type of error.

My question is, 
1. is it work with gbk and fasta file?
When I gave both reference and ctgs as fasta file it executed but results were empty.

Apology  for wasting your time.
