### ISSUE TITLE
snippy --check 

### ISSUE THREAD

**Issue by ytao0210** [tseemann/snippy#395]
$snippy --check

Found freebayes - /hwfssz5/ST_MCHRI/BIGDATA/USER/taoye1/snippy_HP/snippy-master/binaries/linux/freebayes

FATAL: kernel too old
Could not read output of 'freebayes --version'

Installed low version of freebayes
file freebayes
freebayes: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, not stripped

The kernel version of linux meets the requirements.

Why is there the same problem as above?

**Comment by tseemann** [comment]
Where does it say what kernel Snippy needs?

Please compile freebayes for your own system.
Do not depend on the one I include.

Or. use conda or brew to install snippy.
