### ISSUE TITLE
Strain(s)-specific SNPs from snippy output files

### ISSUE THREAD

**Issue by MostafaYA** [tseemann/snippy#396]
Hi Torsten, 
I was wondering how it is possible to parse snippy output files to identify strain(s)-specific SNPs?
I am looking for SNPs which are unique in one strain (or a group of strains) and different in all other strains.   
Thanks and regards,

**Comment by tseemann** [comment]
Yes it is possible. All the information is there. But Snippy has no tool to do that for you.

You could use `bcftools isec` to do "set operations" on the VCF files perhaps.

There may be other tools but I don't know that field very well, sorry.
