### ISSUE TITLE
Error: Multi-threaded opton not supported in this version!

### ISSUE THREAD

**Issue by ireneortega** [tseemann/snippy#399]
Snippy failed with this error message: [Sample_snippy_log.log](https://github.com/tseemann/snippy/files/4741987/Sample_snippy_log.log). Something happened with this snpEff version: `SnpEff version SnpEff 4.3t (build 2017-11-24 10:18), by Pablo Cingolani`

This is my java version: 
```
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (Zulu 8.33.0.1-linux64) (build 1.8.0_192-b01)
OpenJDK 64-Bit Server VM (Zulu 8.33.0.1-linux64) (build 25.192-b01, mixed mode)
```

I followed previous issues and couldn't solve it. What should I do? Thanks for your response!

**Comment by tseemann** [comment]
You are using a VERY new experimental version of snpEff that doesn't seem to support threading.
```
SnpEff version SnpEff 4.5covid19 (build 2020-04-15 22:26), by Pablo Cingolani
Error: Multi-threaded opton not supported in this version!
```

However, I do not use the "-t" option in snpEff in current version of Snippy.

You must be using an old Snippy version?
Please use >= 4.6.0
