### ISSUE TITLE
ERROR: Could not run: snp-sites -c -o core.aln core.full.aln

### ISSUE THREAD

**Issue by letQOD** [tseemann/snippy#400]
Hello,

I ran a snippy job with the 4.4.0 version and got the following messages at the end:
Opening: core.tab
Opening: core.vcf
Processing contig: CP028357.1
Generating core.full.aln
Creating TSV file: core.txt
Running: snp-sites -c -o core.aln core.full.aln
Warning: No SNPs were detected so there is nothing to output.
ERROR: Could not run: snp-sites -c -o core.aln core.full.aln

I know there should be some SNPs as I ran the 4.1.0 version few months ago on the same dataset minus 5 genomes. 

tried to relaunch the snp-sites -c -o core.aln core.full.aln alone but got the same error. 

Is there a trick to avoid launching the entire analysis on the dataset (125 genomes) or do I have to redo the whole thing ?

options used:
snippy-multi ../listesnippy_120620.txt --ref ../ref201001922.fasta --mapqual 60 --basequal 13 --mincov 4 --minfrac 0.75 --cpus=12 > multi.sh

Thanx for your help !

**Comment by tseemann** [comment]
```
Warning: No SNPs were detected so there is nothing to output.
```
There were no core SNPs.
Older versions of Snippy had more false positives.
Also, your extra 5 genomes could be a problem.

You don't need to do it again. Just use `snippy-core` manually,using the snippy output folders you want to include.    Use the `core.txt` file to figure out which one are the "bad" outliers and don't include them.

**Comment by pgcudahy** [comment]
Hello Torsten, I'm having the same issue when running on 972 different isolates using the mask file you provide. Is it really possible that no SNPs were detected? log at https://gist.github.com/pgcudahy/2257b9260901a136df9fdeffe39edbb5
