### ISSUE TITLE
Exception: Unable to read reference sequence base past end of current cached sequence.

### ISSUE THREAD

**Issue by Perugolate** [tseemann/snippy#41]
In one of my projects with 100's of samples, the total size of the snippy output directories was > 20X larger than expected. I realised that the log files are each filled with ~25000-160000 instances of:

> Exception: Unable to read reference sequence base past end of current cached sequence.

e.g.

> Exception: Unable to read reference sequence base past end of current cached sequence.
> jla513_unpol:36
> 35-336
> alignment: AATTTCATAACATCAACTAGGGTTTGGTCCGAAGCATACGTGTTTACAATGTTCGAACAACTTATACAGTTCTTATACATACTTTATAAATTATTTCCCAAACTGTTTTGATACACTCACTAACAGATACTCTATAGAAGGAAAAGTTATCCACTTATGCACATTTATAGTTTTCAGAATTGTGGATAATTAGAAATTACACACAAAGTTATACTATTTTTAGCAACATATTCACAGGTATTTGACATATAGAGAACTGAAAAAGTATAATTGTGTGGATAAGTCGTCCAACTCATGATTT
> currentSequence: CGATTAAAGATAGAAATACACGATGCGAGCAATCAAATTTCATAACATCACCATGAGTTTGGTCCGAAGCATGAGTGTTTACAATGTTCGAACACCTTATACAGTTCTTATACATACTTTATAAATTATTTCCCAAACTGTTTTGATACACTCACTAACAGATACTCTATAGAAGGAAAAGTTATCCACTTATGCACATTTATAGTTTTCAGAATTGTGGATAATTAGAAATTACACACAAAGTTATACTATTTTTAGCAACATATTCACAGGTATTTGACATATAGAGAACTGAAAAAGTATAATTGTGTGGATAAGTCGTCCAACTCATGATT
> currentSequence matching:

This seems to be a known freebayes issue https://github.com/ekg/freebayes/issues/165 and installing v1.0.1 seems to have resolved it for me. The number of SNPs increases with v.1.0.1. Don't know if this is related to the exception or to some other change in freebayes behaviour.

**Comment by tseemann** [comment]
@Perugolate thanks for the warning. I've updated the bundled freebayes to 1.0.1 which I what I am using on our servers. 

I think freebayes has so many complicated options that it is becoming hard to maintain and debug!

**Comment by tseemann** [comment]
Lots of changes in Snippy 4.x and freebayes 1.1
