### ISSUE TITLE
BAM file as input

### ISSUE THREAD

**Issue by shaman-narayanasamy** [tseemann/snippy#42]
Hi!

Any plans on including BAM format as input to snippy..? It would be convenient a convenient option :)

Best,
Shaman

**Comment by tseemann** [comment]
Do you mean a BAM of unaligned reads? 

Or a BAM containing reads that have been aligned already ?

And if aligned already, do you mean to not use the alignments? Or use them instead of BWA MEM?

**Comment by shaman-narayanasamy** [comment]
Sorry for not being clear. 

I meant BAM file containing alignments to a reference.

I would like to use those alignments directly to call the SNPs instead of aligning them using BWA, within snippy.

Also, I need your opinion. My alignments contain both paired-end and single-end reads, i.e. within a single BAM file. Do you think they should be separate?

**Comment by tseemann** [comment]
I have added this to https://github.com/tseemann/snippy/tree/version_4
