### ISSUE TITLE
bam file as snippy input

### ISSUE THREAD

**Issue by Kelzor** [tseemann/snippy#421]
Hello!

I saw in https://github.com/tseemann/snippy/issues/269 that it's possible to run snippy with --bam, but when I do, snippy doesn't report snps. Why is freebayes not running correctly? I could not find any more information in the readme about --bam.

The input bam is analysis-ready, trimmed, filtered, and duplicates removed. I've attached the .log here:
[snps.log](https://github.com/tseemann/snippy/files/5120810/snps.log)

Thanks!
Kelly

**Comment by ktmeaton** [comment]
Hi Kelly,

The last message I see in your log is:

```
No such sample: TLTA102_bam
``` 

In my experience, that occurred because the read group (RG) in your bam file is not identical to the --outdir you've set ```TLTA102_bam```.

In my case, my --outdir was ```SAMN02442721``` (because my input was SAMN02442721.bam). But when I checked the RG flag in the bam, the read group was set to SRR1048905:

```
$ samtools view -h SAMN02442721.bam | grep "@RG"

@RG     ID:SRR1048905
```

For me, this happened because I renamed the bam file after mapping and before snippy. Do you think this is related?

Cheers,
Kat

**Comment by Kelzor** [comment]
Thank you for the suggestion, @ktmeaton !

I changed the @RG ID to match the output directory name, but I encounter the same problem 
[snps.log](https://github.com/tseemann/snippy/files/5336896/snps.log)

The problem seems to occur at variant calling. Snippy successfully preps and creates the snps.bam that it uses as freebayes input:

`samtools view -h -O SAM \/data\/stonelab\/Kelly_TB\/snippy_testing\/TLT001\.A0102\.bam | samclip --max 10 --ref reference/ref.fa.fai | samtools sort -n -l 0 -T /tmp --threads 7 -m 1000M | samtools fixmate -m --threads 7 - - | samtools sort -l 0 -T /tmp --threads 7 -m 1000M | samtools markdup -T /tmp --threads 7 -r -s - - > snps.bam`

The output snps.bam is the expected size. All of the steps produce a non-empty file until the freebayes step:

`freebayes-parallel reference/ref.txt 16 -p 2 -P 0 -C 2 -F 0.05 --min-coverage 5 --min-repeat-entropy 1.0 -q 35 -m 60 --strict-vcf   -f reference/ref.fa snps.bam > snps.raw.vcf`

snps.raw.vcf is empty. 

freebayes runs perfectly, however, if I run it outside of snippy using the snippy-produced .fa and .bam:

`freebayes --min-coverage 5 -f reference/ref.fa snps.bam > snps_freebayes.vcf`

I can't figure out where `bcftools consensus --sample TLT001.A0102` would be getting the sample name from, but I think the first problem is occurring with freebayes and geneating the vcf file.

I would love any more advice that you have for how to fix this! 

Thank you, 
Kelly

**Comment by ktmeaton** [comment]
Hi Kelly,

```bcftools consensus``` looks like it searches for the sample name in the output file snps.vcf.gz. If you run the following to inspect the vcf header, what is your output?

```bash
gunzip -c snps.vcf.gz | grep "#CHROM"
```

Example output from my input file ```SAMN02442718.bam```.

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  SAMN02442718
```

If your output is not:
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  TLT001.A0102
```

That might be a clue to why bcftools is giving errors.

Cheers,
Katherine

**Comment by Kelzor** [comment]
Hi, Katherine!

Thank you so much for your help! You were definitely right about the RGs. I had only changed the ID, not the SM.
Now they're both the same as the .bam name:

`picard AddOrReplaceReadGroups I=515b_trimmed_merged_bwa_mapped_q37_sorted.bam O=515b.bam RGID=515b RGLB=lib1 RGPL=ILLUMINA RGPU=unit1 RGSM=515b`

and the run goes to completion without errors.

However, I was still getting an empty snps.raw.vcf output from freebayes with no errors. I tried the solution presented here: https://github.com/tseemann/snippy/issues/410, but that didn't solve the problem. I didn't think it was a problem with vt though because it happens before the` vt normalize ` step. 

It turns out that the default mapping quality is set to 60, and I wasn't specifying a mapping quality. So none of my snps were passing the mapqual filter...oops.

Everything seems to be working fine now. I really, really appreciate your help getting this to work! 

Best, 
Kelly

**Comment by ktmeaton** [comment]
> It turns out that the default mapping quality is set to 60, and I wasn't specifying a mapping quality. So none of my snps were passing the mapqual filter...oops.

I'm glad to hear everything is working! Also this is a great tip that I didn't think about it. I tend to 'default' to MQ=30 for most work since I've got short ancient molecules that are mostly single-end. Good to know that MQ=60 can explain sudden data losses :)
