### ISSUE TITLE
Snippy output interpretation!

### ISSUE THREAD

**Issue by nbawe** [tseemann/snippy#422]
I have questions regarding snippy output (added at the end of the comment).

**1) REF; ALT and EFFECT**
Could you please explain REF, ALT and EFFECT using the row beginning with _NODE_4..._, i have read README.md explanation but I am a bit confused?

**2) Additional information using Genbank file as reference**
I used Genbank as reference and the last row beginning with _NODE_1..._ does not have this additional information. What could be the problem?

CHROM|POS|TYPE|REF|ALT|EVIDENCE|FTYPE|STRAND|NT_POS|AA_POS|EFFECT|LOCUS_TAG|GENE|PRODUCT
-----|---|----|---|---|--------|-----|------|------|------|------|---------|----|-------
NODE_4_length_425732_cov_48.486853|181980|snp|C|T|T:22 C:0|CDS|-|16/510|6/169|missense_variant c.16G>A p.Val6Ile|||hypothetical protein
NODE_6_length_201546_cov_44.355597|2286|snp|T|A|A:149 T:0|CDS|-|1029/1311|343/436|missense_variant c.1029A>T p.Glu343Asp|||CBS-domain-containing protein
NODE_5_length_217505_cov_37.518516|70702|snp|T|C|C:162 T:0|CDS|+|721/759|241/252|missense_variant c.721T>C p.Ser241Pro|||Indole-3-glycerol phosphate synthase (EC 4.1.1.48)
NODE_3_length_579564_cov_40.280807|264413|snp|C|T|T:145 C:0|CDS|-|757/1476|253/491|missense_variant c.757G>A p.Ala253Thr|||UDP-N-acetylmuramoyl-dipeptide--2,6- diaminopimelate ligase (EC 6.3.2.13)
NODE_1_length_700534_cov_38.930152|694342|del|GA|G|G:77 GA:0||||||||

**Comment by andersgs** [comment]
Hi @nbawe. 

1. The REF is the base observed in the reference genome you used. ALT is the base observed at your sample. EFFECT is the predicted effect of that base change. Only possible when the region has some annotation, typically a CDS. In the top record in your table, it suggests the observed nucleotide difference between your reference and sample genomes at that position would lead to an amino-acid change. 

2. If there is no annotation at the location of the change, then no effect can be inferred. So, in case of NODE_1 there is no annotation in that region. 

Best. A.

**Comment by nbawe** [comment]
Thank you @andersgs One more question. If REF is C and ALT is T howcome the EFFECT is G>A? Could you please clarify?

**Comment by andersgs** [comment]
@nbawe I suspect the CDS must be on the other strand.

**Comment by nbawe** [comment]
@andersgs thank you!
