### ISSUE TITLE
error snippy-core can not work

### ISSUE THREAD

**Issue by senjoro** [tseemann/snippy#424]
the lest code is 
>snippy-core --ref 'ATCC13311.fasta' S-13-10-1r-2-I4512i S-13-10-1r-Derby S-13-100-1r-Derby S-13-103-1r-Derby S-13-106-1r-Wandsworth
and its not work
Derby: command not found
Thompson: command not found
Kintambo: command not found
Llandoff: command not found
Budapest: command not found
Corvallis: command not found
This is snippy-core 4.4.5
Obtained from http://github.com/tseemann/snippy
Enabling bundled tools.
Found any2fasta - /software/snippy/binaries/noarch/any2fasta
Corvallis: command not found
Found samtools - /usr/bin/samtools
Yeerongpilly: command not found
Found minimap2 - /software/minimap2/minimap2
Found bedtools - /usr/bin/bedtools
Found snp-sites - /usr/bin/snp-sites
ERROR: Can't open --ref ATCC13311.fasta
Yeerongpilly: command not found
Washington: command not found

**Comment by schultzm** [comment]
Hi @senjoro,

Are the paths to the reference and the snippy output directories relative paths? Paths need to be relative or absolute.

**Comment by senjoro** [comment]
Thanks for reply:
I used the SH from Snippy-Multi, the file path is relative path, and the puzzling thing is that I ran the whole process again and it worked.
I think maybe something wrong with my computer.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tseemann/snippy"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月4日(星期五) 上午6:29
收件人:&nbsp;"tseemann/snippy"<snippy@noreply.github.com&gt;;
抄送:&nbsp;"赵文轩"<zhao-wx@foxmail.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [tseemann/snippy] error snippy-core can not work (#424)





 
Hi @senjoro,
 
Are the paths to the reference and the snippy output directories relative paths? Paths need to be relative or absolute.

**Comment by andersgs** [comment]
@senjoro if this no longer an issue, can you close it? Thank you.
