### ISSUE TITLE
Error when using GBK file

### ISSUE THREAD

**Issue by nextgenusfs** [tseemann/snippy#43]
Thanks for creating this pipeline - it is very useful.  I'm able to get everything to work if I use just a multi-fasta file for a reference, however, I'm getting an error during the snpEff build step if I use a GBK file.  I've tried both an NCBI GBK and one I created manually - both give me the same error  

Here's the error from the log file:

```
### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref

java.lang.RuntimeException: Error reading file '/Users/ngs/Desktop/Anid_snps/MRB326/reference/./ref/genes.gff'
java.lang.RuntimeException: FATAL ERROR: Offending line (lineNum: 15): 'Chr1	snippy	CDS	1976	1986	.	+	0	ID=AN10814;codon_start=1;locus_tag=AN10814;product=Has domain(s) with predicted oxidoreductase activity and role in metabolic process;protein_id=ncbi:rna_AN10814-1;translation=MRSESSTDVLIVGAGPAGLTTALWLAHTGVQFRIIDKRPNIPRRGQADGLSPRTMEILETFEVAHEVTRLWERATDEMLWCRDAQGNLTRMERFRNQPPQGVRWGHGTLQQGVVEEIMKKKITEVCGVEVEYETTLFELSLDTTKANDPEAFPWSATVRYGTDEPAGQMLSKTMLAKYVVGADGGRSFVRQTMGIEMQGTKGEAVWGVMDIIGTSDFPDDIDGAVDFVRREKDRDAITPESIIVKCEYIIRPYKLYIKEHVWWSAFTVAQRISNSMAVHNRGFLVGDAVHTHSPLCGAGMNTAVQLHRDAYNLGWKLAGVLKHQLNPEILQTYGAERRPVAEALLDADKTILALFHAPLGPEAEALLAKADHIQAYLSGRGIQYRASLLTHGSAEGLRSLAVLPGHCIPDITVQNYMTGRASNLHSWIMADGGWSVIFWASDLSCASRVENIHNCCKQVESIRAKTSSKVGYMLDAFLIHCNEWPSVDLAALPGLFLPPSKYGCLDYGKIFVREETASCKSERMNNLGGIAVVRPDKYVGWVGGLDDMVGLGLYFSKIFL'. File '/Users/ngs/Desktop/Anid_snps/MRB326/reference/./ref/genes.gff' line 15
	'Chr1	snippy	CDS	1976	1986	.	+	0	ID=AN10814;codon_start=1;locus_tag=AN10814;product=Has domain(s) with predicted oxidoreductase activity and role in metabolic process;protein_id=ncbi:rna_AN10814-1;translation=MRSESSTDVLIVGAGPAGLTTALWLAHTGVQFRIIDKRPNIPRRGQADGLSPRTMEILETFEVAHEVTRLWERATDEMLWCRDAQGNLTRMERFRNQPPQGVRWGHGTLQQGVVEEIMKKKITEVCGVEVEYETTLFELSLDTTKANDPEAFPWSATVRYGTDEPAGQMLSKTMLAKYVVGADGGRSFVRQTMGIEMQGTKGEAVWGVMDIIGTSDFPDDIDGAVDFVRREKDRDAITPESIIVKCEYIIRPYKLYIKEHVWWSAFTVAQRISNSMAVHNRGFLVGDAVHTHSPLCGAGMNTAVQLHRDAYNLGWKLAGVLKHQLNPEILQTYGAERRPVAEALLDADKTILALFHAPLGPEAEALLAKADHIQAYLSGRGIQYRASLLTHGSAEGLRSLAVLPGHCIPDITVQNYMTGRASNLHSWIMADGGWSVIFWASDLSCASRVENIHNCCKQVESIRAKTSSKVGYMLDAFLIHCNEWPSVDLAALPGLFLPPSKYGCLDYGKIFVREETASCKSERMNNLGGIAVVRPDKYVGWVGGLDDMVGLGLYFSKIFL'

	at ca.mcgill.mcb.pcingola.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:132)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdBuild.createSnpEffPredictor(SnpEffCmdBuild.java:115)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:304)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:883)
	at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:128)
```

**Comment by tseemann** [comment]
@nextgenusfs I think the version of snpEff is important here. I am using 4.1 series. What are you using? If you send me the .gbk file I can test it out.

**Comment by nextgenusfs** [comment]
I have the following version:  `snpEff version SnpEff 4.1l (build 2015-10-03)`.  Seems like any .GBK file I try fails here, either downloaded from NCBI or one I've created locally.  These are eukaryote genomes (fungi), but I don't see how that would matter for building the snpEff DB.

It has failed with this genome as well as some others: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF_000002655.1_ASM265v1/GCF_000002655.1_ASM265v1_genomic.gbff.gz

**Comment by tseemann** [comment]
@nextgenusfs  I confirm it fails with the file above. I'm not sure why. It works with RefSeq bacterial GBK files and Prokka GBK files. 

The error seems to imply I've fed it an invalid GFF3 line, but I'm not sure what exactly.

You should be made aware that my SnpEff code has hard-coded the bacterial translation tables in it, so it won't give the correct effects for Fungi, and it certainly will fail with exons. The other issue is the CDS in your file seem to be "partial" (they use < and > on their coordinates).

**Comment by nextgenusfs** [comment]
@tseemann thanks for looking into this.  I think partial gene models are allowed in eukaryotic genomes, but not prokaryotes.  So given what you said about hard-coding, i won't attempt to use the gene models for fungal genomes.  But am I correct to assume that I can still use Snippy with just a genome fasta file?  It will still call SNPs and everything correctly, it just won't be able to determine if SNPs were in coding regions and/or result in frameshift/stop/nonsynonomous mutations?

**Comment by tseemann** [comment]
@nextgenusfs Yes you can still use it for SNP calling with a FASTA reference.

Prokaryotic annotations can have partial genes - they often occur at contig ends where the alignment ended to a known protein.

I need to go back and use some GCF_ bacterial genomes and see if i get the same problem. It's probably my fault, I just don't have much time to investigate it at the moment.

**Comment by nextgenusfs** [comment]
@tseemann No worries, it is not an immediate need for me.  Thanks again for looking into it.
