### ISSUE TITLE
samtools faidx reference/ref.fa 2>> snps.log

### ISSUE THREAD

**Issue by angeladelvalle** [tseemann/snippy#438]
Hi, I would have been running snippy, everything looks fine till the point it'is going to star running samtools, so it's when this error comes up:

![image](https://user-images.githubusercontent.com/74251140/98701926-b7fcb280-2371-11eb-9d02-bf4fd4d01c88.png)
 when I open the snps.log folder, this is what I find:
![image](https://user-images.githubusercontent.com/74251140/98702413-4113e980-2372-11eb-8a2d-f267447fa2f4.png)
 Has someone had this problem before? would someone mind helping me?

**Comment by andersgs** [comment]
HI @angeladelvalle can you confirm that your input reference sequence file has sequence data in it? If it is a Genbank file, it is not uncommon for it to be downloaded with just the annotations and not the sequence data.

**Comment by angeladelvalle** [comment]
you were right @andersgs, thank you so much!
