### ISSUE TITLE
snippy-multi provides error

### ISSUE THREAD

**Issue by ShresthaRima** [tseemann/snippy#441]
Hi! 
I ran individual genome to call SNPs with the same reference genome and it does work well. But when I ran more than 150 genomes that need to align with same reference genome using below code:
snippy-multi input.tab --ref refgenome.fa --cpus 16 > runme.sh
it results the error: 
Reading: /Documents/P1aln/NEW/input.tab
ERROR: [a.fasta] missing read/contig data: a.fasta 

I checked the solution you have in the github, which I already adjusted (input.tab as file3.txt), and checked the fasta file and its contigs and sequences are there. Problem is there with running snippy-mutli. 

While running individual genome for a.fasta it does have 
total no. variants normalized            : 366
       total no. variants observed              : 27709
       total no. reference observed             : 0

Time elapsed: 0.25s

**Comment by PaolaLis8** [comment]
I have encountered the same issue, did you solve the problem? 
In my case, I am using assembled contigs.

**Comment by ShresthaRima** [comment]
Solved by checking any gaps in the tab and using path for the commands:

C:/Documents/snippy/bin/snippy-multi C:/Documents/P1aln/NEW/input.tab --ref C:/Documents/P1aln/NEW/refgenome.fa --cpus 16 > runme.sh
