### ISSUE TITLE
Unable to run snippy

### ISSUE THREAD

**Issue by Javaria-Ashraf** [tseemann/snippy#443]
Dear Tseemann,

Im trying to run snippy usibg snippy --check but it gives the following error:

`Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /home/puser/perl5/lib/perl5 /home/puser/anaconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/puser/anaconda3/lib/site_perl/5.26.2 /home/puser/anaconda3/lib/5.26.2/x86_64-linux-thread-multi /home/puser/anaconda3/lib/5.26.2 .) at /home/puser/anaconda3/bin/snippy line 11.
BEGIN failed--compilation aborted at /home/puser/anaconda3/bin/snippy line 11.`

However, BIO::SeqIO is already installed. but when i run the same command using sudo "sudo snippy --check" it gives new error:

`Can't locate strict.pm in @INC (you may need to install the strict module) (@INC contains: /usr/local/lib/site_perl/5.26.2/x86_64-linux-thread-multi /usr/local/lib/site_perl/5.26.2 /usr/local/lib/5.26.2/x86_64-linux-thread-multi /usr/local/lib/5.26.2 .) at /usr/local/bin/snippy line 2.
BEGIN failed--compilation aborted at /usr/local/bin/snippy line 2.`

where as strict module is installed too

Can you please help me with this i have tried to install snippy using git clone as well as anaconda both but it is showing same errors.
looking forward for your response

Thanks

JIA

**Comment by suzlbach** [comment]
I think you need to add your installation to your $PATH, close the terminal and reopen it.

**Comment by rpetit3** [comment]
Hi @Javaria-Ashraf 

I wonder if its worth trying to install Snippy into a new environment (noticed anaconda)

```
conda create -y -n snippy -c conda-forge -c bioconda snippy
conda activate snippy
snippy --version
```

**Comment by andersgs** [comment]
Also, make sure you have version 1.7.2 or above of bioperl. Older versions seem broken in Bioconda.

Please re-open if needed.
