### ISSUE TITLE
snippy-core outputting few snps ???

### ISSUE THREAD

**Issue by robertwhbaldwin** [tseemann/snippy#446]
Hello,

I ran 12 isolates through snippy individually and then called snippy-core with the snippy folders and it seemed to work (no error messages) and I got some output but the number of snps generated was way off. Each of those isolates had 8000 - 14000 snps when aligned to a 5 mbp reference genome. How could I get a dozen snps for the core genome? 

Do I have to run it all again with multi?

Any ideas what's going on? Thank You. - Robert

**Comment by stevenjdunn** [comment]
I'd check out the description of [what snippy core is doing.](https://github.com/tseemann/snippy#core-snp-phylogeny)

If you have read sets that are very different to the reference - and each other - the number of sites in your core genome will be relatively small. Some information on this can be seen in the `snps.txt` output file.

That also sounds like a lot of SNPs. What are you trying to achieve, perhaps there is a neater solution?

**Comment by robertwhbaldwin** [comment]
Thanks, yes, read it. What do I want to achieve? 
I have four Moritella viscosa isolates being sequenced and handed off to me and one of the main things that I need to do is a phylogenetic analysis. 
Before I get the data I'm looking at what's available publicly. There's a high quality reference genome for this species on NCBI (1 chromosome + 2 plasmids) plus 12 genomes on ENA. These 12 genomes all came from the same study. One sample is the same isolate as the reference so I have an assembly plus 11 different isolates. Phylogenetic analysis showed that these 12 isolates form 4 clades. 

My first goal was to generate a core snp set to create a phylogenetic tree and compare the results to the published phylogeny. Ultimately I'm going to add my four samples to the tree and then do some analysis of virulence genes.

In this case, my samples should be close enough to each to make read mapping very feasible. I see no problem with the snps I'm getting. Actually the number of snps I'm seeing is consistent with the phylogeny as the number of snps called between sample of the same clade are far more similiar than they are between samples of different clades. And the sample with the fewest snps is in the same clade as the reference isolate, which is obviously what you'd expect. Also the large majority of the reads are mapping to the reference (~85%). 







 


    


I want a core genome phylogeny. I also have to do some analysis of virulence genes and will require fairly sensitive snp calls

**Comment by fjlicht** [comment]
Hi Robert.

I might suggest trying this: https://github.com/PlantDr430/BuscoOrthoPhylo

I have found it to work well for what you are. trying to do. I have used it on multiple fungal genomes that I assembled and annotated. Publication here: https://doi.org/10.1186/s12864-020-06987-z

Franz

**Comment by Kelzor** [comment]
I have had this issue too. It means that only 12 SNPs are observable in ALL of your samples. This can happen if just one of your samples has splotchy and low coverage. I work with ancient DNA, which is always low coverage, and I have to have Ns in my alignments. What I do to get around this is to use snp-sites to create a SNP alignment from the core.full.aln multiple sequence alignment produced by snippy-core. snp-sites will create a SNP alignment of all sites, including those that are not callable in all genomes. Since it doesn't sound like you have too many samples, I would look through the snp-sites alignment to identify your problem samples (those with lots of Ns) and consider removing them.

snp-sites is part of snippy, so you can just run

`snp-sites -o core_aln_with_ns.aln snippy.core.full.aln`

**Comment by stevenjdunn** [comment]
Sounds cool! I would check to see how large the core genome being called actually is, as @Kelzor says, there might be an awkward sample confusing things. 

If you post your `core.txt` it might help narrow it down, or using @Kelzor’s suggestion above, you could quickly split the multifasta alignment  (I would use a [biopython script](https://github.com/stevenjdunn/TigSPLIT) for this), and then count the number of special characters in each file with something like tr:

`tr -cd 'N' < sample1.fasta | wc -c`

I always find it helpful to assemble the reads and run some quick phylo tools like mashtree, or parsnp if they’re closely related, just to sense check everything. If there was one problem sample it’d quickly jump out at you.

**Comment by andersgs** [comment]
As this discussion has stopped, I will close the issue. Please re-open if necessary.
