### ISSUE TITLE
Any recommendation for a pathogenicity island finder software available in github?

### ISSUE THREAD

**Issue by angeladelvalle** [tseemann/snippy#448]
Hi, I am studying the virulence of some bacteria samples, and I would have heard about a few software for identifying them.
Any recommendation?

**Comment by andersgs** [comment]
Not really. I did a quick google and found this: https://www.pathogenomics.sfu.ca/islandviewer/resources/ --- but not really tested. So, not an endorsement. 

Best of luck.
