### ISSUE TITLE
fails with samtools 1.3

### ISSUE THREAD

**Issue by stephenturner** [tseemann/snippy#45]
Looks like something changed between 1.1 and 1.3 regarding the -T -o options to sort. See the log file below.

```
### samtools faidx reference/ref.fa


### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.02 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.84 seconds elapse.
[bwa_index] Update BWT... 0.02 sec
[bwa_index] Pack forward-only FASTA... 0.03 sec
[bwa_index] Construct SA from BWT and Occ... 0.45 sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa index reference/ref.fa
[main] Real time: 1.653 sec; CPU: 1.369 sec

### mkdir reference/genomes && cp -f reference/ref.fa reference/genomes/ref.fa


### mkdir reference/ref && bgzip -c reference/ref.gff > reference/ref/genes.gff.gz


### (bwa mem  -v 2 -M -R '@RG	ID:snps	SM:snps' -t 16 reference/ref.fa /nv/vol46/uvabx/projects/houpt/samara-mtb/snps/ERR027468_1.fastq.gz /nv/vol46/uvabx/projects/houpt/samara-mtb/snps/ERR027468_2.fastq.gz | samtools view -@ 16 -F 3844 -q 60 -S -b -u -T ref.fa - | samtools sort -@ 16 - snps)

[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
  -@, --threads INT
             Set number of sorting and compression threads [1]
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
[samfaipath] fail to read file ref.fa.
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (314, 741, 1299)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 3269)
[M::mem_pestat] mean and std.dev: (885.94, 718.35)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 4254)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (142, 172, 213)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 355)
[M::mem_pestat] mean and std.dev: (179.11, 54.24)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 426)
[M::mem_pestat] analyzing insert size distribution for orientation RF...
[M::mem_pestat] (25, 50, 75) percentile: (622, 1410, 3220)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 8416)
[M::mem_pestat] mean and std.dev: (2037.37, 1944.74)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 11014)
[M::mem_pestat] analyzing insert size distribution for orientation RR...
[M::mem_pestat] (25, 50, 75) percentile: (386, 721, 1296)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 3116)
[M::mem_pestat] mean and std.dev: (864.82, 652.77)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 4026)
[M::mem_pestat] skip orientation FF
[M::mem_pestat] skip orientation RF
[M::mem_pestat] skip orientation RR
```

**Comment by suryasaha** [comment]
I can confirm the samfaipath error with samtools 1.2

``### samtools faidx reference/ref.fa

### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 4.61 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncCreate] textLength=633296848, availableWord=56560948
[BWTIncConstructFromPacked] 10 iterations done. 89963168 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 169403216 characters processed.
[BWTIncConstructFromPacked] 30 iterations done. 240005728 characters processed.
[BWTIncConstructFromPacked] 40 iterations done. 302753408 characters processed.
[BWTIncConstructFromPacked] 50 iterations done. 358519680 characters processed.
[BWTIncConstructFromPacked] 60 iterations done. 408080880 characters processed.
[BWTIncConstructFromPacked] 70 iterations done. 452126960 characters processed.
[BWTIncConstructFromPacked] 80 iterations done. 491271200 characters processed.
[BWTIncConstructFromPacked] 90 iterations done. 526058688 characters processed.
[BWTIncConstructFromPacked] 100 iterations done. 556973888 characters processed.
[BWTIncConstructFromPacked] 110 iterations done. 584447344 characters processed.
[BWTIncConstructFromPacked] 120 iterations done. 608861792 characters processed.
[BWTIncConstructFromPacked] 130 iterations done. 630557376 characters processed.
[bwa_index] 259.81 seconds elapse.
[bwa_index] Update BWT... 2.56 sec
[bwa_index] Pack forward-only FASTA... 2.60 sec
[bwa_index] Construct SA from BWT and Occ... 76.05 sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa index reference/ref.fa
[main] Real time: 346.877 sec; CPU: 345.636 sec

### mkdir reference/genomes && cp -f reference/ref.fa reference/genomes/ref.fa


### mkdir reference/ref && bgzip -c reference/ref.gff > reference/ref/genes.gff.gz


### (bwa mem  -v 2 -M -R '@RG	ID:pe_paired	SM:pe_paired' -t 30 reference/ref.fa /data/home/surya/work/SL3.0/bacs_err_correction/out.paired.fwd_pe.gz /data/home/surya/work/SL3.0/bacs_err_correction/out.paired.rev_pe.gz | samtools view -@ 30 -F 3844 -q 60 -S -b -u -T ref.fa - | samtools sort -@ 30 - pe_paired)

[samfaipath] fail to read file ref.fa.
[M::mem_pestat] analyzing insert size distribution for orientation FF...
[M::mem_pestat] (25, 50, 75) percentile: (87, 199, 1626)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (1, 4704)
[M::mem_pestat] mean and std.dev: (749.22, 989.22)
[M::mem_pestat] low and high boundaries for proper pairs: (1, 6243)
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (128, 153, 167)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (50, 245)``

**Comment by tseemann** [comment]
Hi @stephenturner  - this was fixed in https://github.com/tseemann/snippy/commit/a8dc9b2b98a3a556c02c55eb628ea1656bc5a34d
I am preparing a new release, which will also support assembled genomes as the "reads" to find SNPs in.
