### ISSUE TITLE
ERROR: Could not find .aligned.fa/.vcf in file_name

### ISSUE THREAD

**Issue by sharbie88** [tseemann/snippy#456]
Hi,  I'm not sure if this is the same error as other issues with the same '.aligned.fa/.vcf' error. 
Snippy has been running for 2 days using the command

`snippy-multi '/media/sharb/SharonsHD4/1to401_fastqgz_list.tab' --ref '/media/sharb/SharonsHD4/fastq_trimmedpaired_1_401/nzak3.gbk' --report --cpus 16 > runme.sh`

all 401 isolate folders are present and most contain 22 items but some only have 5 (reference folder, ref.fa, ref.fa.fai, snps.bam, snps.log)
and only the core.ref.fa has been output.

I've run the command using a subset of my isolates and it's worked perfectly.  Do you know what could have caused the issue please?

**Comment by safrye** [comment]
Hi,
I had a similar problem when running snippy-multi only with contigs generated with Shovill and a GBK file as reference. So in the "runme.sh" file the first lines looked like this example:
`snippy --outdir '2022-03-23-9' --ctgs '/home/sfrye/Data/Pseudomonas/snakemake/shovill/assemblies-shovill-2022-03-23/Pa/2022-03-23-9_S7_L001_run_001-contigs.fa.gz' --ref NC_002516.2.gb --cpus 8`

The generated subfolders, named after the isolate names, only contained after the run a file named "fade_reads.fq" with the size 0. Each subfolder contained another subfolder named "reference" which contained the files "ref.fa" and "ref.gff", nothing more.

The last line in the "runme.sh" file looked like this:
`snippy-core --ref '2022-03-23-10/ref.fa' 2022-03-23-10 2022-03-23-11 2022-03-23-12 2022-03-23-13 2022-03-23-14 2022-03-23-15 2022-03-23-16 2022-03-23-17 2022-03-23-18 2022-03-23-19 2022-03-23-20 2022-03-23-21 2022-03-23-22 2022-03-23-23 2022-03-23-9 A6-17-v1 A6-17-v2`
and thereby referred to a reference file that did not exit, neither as a link as after a successful run!
I got the same "Could not find .aligned.fa/.vcf" error when the script reaches snippy-core. 
(It's the same error I get with the same samples, fastq files, R1 and R2, using Nullarbor.)

I only got a successful snippy-multi run using the fastq (R1 and R2) files as input.

I'm running Snippy version 4.6.0.
