### ISSUE TITLE
Unfixable error in reading files

### ISSUE THREAD

**Issue by mf116** [tseemann/snippy#462]
Does snippy support Ubuntu windows subsystem WSL? because i always have the same error for all trials. @tseemann.
help would me much appreciated.

**Comment by andersgs** [comment]
@mf116 we don't have access to winboxes and have never tested it under Windows.

Can you post what you did exactly, that including commands and how you installed snippy and its dependencies. We would also see an exact output of the error you are getting. 

We make no promises. You are better off trying on a Linux machine or perhaps using Docker (https://docs.docker.com/docker-for-windows/install/). 

I don't really see us supporting WSL or at least, it would be a very low priority for us to implement, test, and maintain WSL support. We don't run any of our tools on Windows. However, if you or someone wants to make a PR request that would provide WSL support, we would be happy to consider to consider it.

**Comment by mf116** [comment]
i installed it using conda running the following commands

conda activate base
conda update --all --yes
conda create -n snippy_env
conda activate snippy_env
conda install -c conda-forge -c bioconda -c defaults snippy

because installing directly did not work

created tabular using normal text editor
running the command goes as follows:
conda activate snippy_env
snippy-multi iso.txt --ref x.gbff --cpus 12 --force > runme.sh

the following error always comes
'RROR: [x] unreadable file '/mnt/c/Users/.../x.fa

**Comment by andersgs** [comment]
Can you read the file from WSL? Can you try `ls <path/to/file>`? And `cat <path/to/file>`?

Given the error, I suspect the path might contain a typo or there is a permissions issue (although, these are not mutually exclusive). 

My understanding is that WSL can access Windows files in the C drive with the `//mnt/c/` prefix. But, perhaps there are underlying privileges that need to be configured. I just don't know enough to help with that aspect.

**Comment by mf116** [comment]
WSL can read the file normally. 
and i used /mnt/c to access windows files. but i think the problem is in permissions as you suspected.
i guess WSL will fix this issue hopefully. but for now i will try to find a way around it if its possible. i will shrink my volume on windows and install dual boot.
thank you for the help.
i will close with this comment

**Comment by andersgs** [comment]
Sorry to hear you weren't able to run it. An alternative to volume shrinking is Docker. But, it is a RAM hog. Best of luck.
