### ISSUE TITLE
snippy-core error

### ISSUE THREAD

**Issue by vscooper** [tseemann/snippy#51]
Hi Torsten, having issues with snippy-core as follows:
`$snippy-core --prefix core mysnps1 mysnps2 mysnps3`
`"any" is not exported by the List::Util module
Can't continue after import errors at /mydir/snippy/bin/snippy-core line 5.
BEGIN failed--compilation aborted at /mydir/snippy/bin/snippy-core line 5.`

Perhaps this is a usage/install error but would appreciate help.

**Comment by tseemann** [comment]
@vscooper - it seems your Perl module List::Util doesn't have the `any` function in it.  That module is part of core Perl, but I suspect maybe you have an old version of Perl before the `any` function became part of the module?

```
% perldoc -m List::Util | grep VERSION
our $VERSION    = "1.41";
```

**Comment by mattbawn** [comment]
@tseemann: after `snippy-core --test core mysnps_1 mysnps_2` I am also getting this error with perl-5.22.0:

```
perldoc -m List::Util | grep VERSION
our $VERSION    = "1.41";
```
Is there a fix?

**Comment by noellenoyes** [comment]
I am also getting this same error when trying to run snippy-core.  Version for Perl module List::Util is 1.41. Thanks for any help you can provide!

**Comment by tseemann** [comment]
@mattbawn @noellenoyes 
can you upgrade List::Util via CPAN?
maybe `sudo cpan List::Util` ?
