### ISSUE TITLE
Cannot install snippy due to bcftools? 

### ISSUE THREAD

**Issue by Xiongqi1114** [tseemann/snippy#583]
(base) C:\Users\dxq>conda install -c conda-forge -c bioconda -c defaults snippy
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides bcftools >=1.8 needed by snippy-4.4.0-0

Could not solve for environment specs
The following packages are incompatible
└─ snippy is not installable because there are no viable options
   ├─ snippy [4.4.0|4.4.1|4.4.3] would require
   │  └─ bcftools >=1.8 , which does not exist (perhaps a missing channel);
   ├─ snippy [4.4.3|4.4.5] would require
   │  └─ bcftools >=1.9 , which does not exist (perhaps a missing channel);
   ├─ snippy 4.4.5 would require
   │  └─ bcftools >=1.9,<1.10 , which does not exist (perhaps a missing channel);
   └─ snippy [4.5.0|4.5.1|4.6.0] would require
      └─ bcftools >=1.10 , which does not exist (perhaps a missing channel).

**Comment by danaauganova** [comment]
Hi Xiongqi1114, 
I got the same issue when tried to install snippy. How did you solve it?

**Comment by Xiongqi1114** [comment]
Hi danaauganova,
I installed a Linux subsystem on my Windows system, and the problem was solved. It's probably because Windows doesn't support bcftools. Hope this helps.



在 2026-02-26 13:26:52，"danaauganova" ***@***.***> 写道：

danaauganova left a comment (tseemann/snippy#583)

Hi Xiongqi1114,
I got the same issue when tried to install snippy. How did you solve it?

**Comment by danaauganova** [comment]
Xiongqi1114, 
Thank you! It helped!
