### ISSUE TITLE
Bundled samtools requires libncurses.so.6

### ISSUE THREAD

**Issue by nickloman** [tseemann/snippy#61]
on my system (Ubuntu 14.04) the bundled samtools won't run due to missing libncursesw.so.6

From what I can see Ubuntu 14.04 still bundles ncurses5

Can work around by downloading ncurses6 from GNU website and building and adding to LD_LIBRARY_PATH

./configure --prefix=`pwd`/install --with-shared --enable-widec
export LD_LIBRARY_PATH=`pwd`/install/lib

Might be good to bundle that library, or drop it from samtools build, or build with v5 instead.

**Comment by tseemann** [comment]
@nickloman Don't depend on my dodgy binaries. I should probably remove them. It will use your artisinally hand compiled versions in preference to my mass produced bundled imitations.
