### ISSUE TITLE
Bundled freebayes needs specific GLIBC version

### ISSUE THREAD

**Issue by nickloman** [tseemann/snippy#62]
Ubuntu 14.04 again

freebayes: relocation error: freebayes: symbol _ZTVNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcE
SaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

I can't be bothered to fix this so I will build freebayes from source

Maybe the bundled bins should use static libraries?

**Comment by jameslz** [comment]
CentOS 7
I have the same error:
 /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./vcfallelicprimitives)

**Comment by tseemann** [comment]
@nickloman @jameslz Don't depend on my 'backup binaries'.  Install via Brew or build the latest freebayes and vcflib for your OS X 👍
