### ISSUE TITLE
No bam file produced with samtools 1.1 or 1.2

### ISSUE THREAD

**Issue by mattbawn** [tseemann/snippy#64]
I recently installed snippy-3.0 on a cluster and found that I had to use samtools 1.3 to get a bam-file to be produced. I had previously tried using samtools 1.1 and 1.2.

**Comment by tseemann** [comment]
Some syntax from samtools 1.1 and 1.2 was deprecated in 1.3 so yes you need 1.3 now. 

I'll try and update the docs.

**Comment by tseemann** [comment]
Fixed in 34fab55da3aecc7845caaa37b21ea5251f978820
