### ISSUE TITLE
SnpEff annotation uses locus_tag rather than gene

### ISSUE THREAD

**Issue by RoyChaudhuri** [tseemann/snippy#65]
When annotating SNPs using a GenBank format reference genome, the CDS "gene" tags are ignored, and the SNPs are annotated using the "locus_tag". This means that the VCF annotations contain only systematic gene IDs rather than human-readable gene names.

**Comment by tseemann** [comment]
Roy, 

It was my understanding that the `gene` is not guaranteed to be unique, hence why I use `locus_tag`.

(and in GFF, the `ID` is unique and `Name` is not).

I'm not sure how best to proceed. What do you feel would be a good solution?

**Comment by RoyChaudhuri** [comment]
Hi Torsten,

Yes, gene is not guaranteed to be unique, but I think it is fine to have both a unique ID containing the locus tag, and a (not necessarily unique) Name containing the gene, which is what my patch does. SnpEff can handle this, with both the Name and the ID tags included in the output, so duplicate Name tags should not be a problem.

This is the output of diff from a Snippy VCF before and after the patch:

63c63
< CP009273      749443  .       G       A       1693.71 .       AB=0;ABP=0;AC=1;AF=1;AN=1;AO=52;CIGAR=1X;DP=52;DPB=52;DPRA=0;EPP=16.5402;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=389.99;PAIRED=0.980769;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=1879;QR=0;RO=0;RPL=27;RPP=3.17734;RPPR=0;RPR=25;RUN=1;SAF=30;SAP=5.68288;SAR=22;SRF=0;SRP=0;SRR=0;TYPE=snp;ANN=A|missense_variant|MODERATE|BW25113_0720|Gene_BW25113_0720|transcript|Transcript_BW25113_0720|Coding|1/1|c.482C>T|p.Ala161Val|482/1284|482/1284|161/427||  GT:DP:RO:QR:AO:QA:GL    1:52:0:0:52:1879:-169.371,0
---
> CP009273      749443  .       G       A       1693.71 .       AB=0;ABP=0;AC=1;AF=1;AN=1;AO=52;CIGAR=1X;DP=52;DPB=52;DPRA=0;EPP=16.5402;EPPR=0;GTI=0;LEN=1;MEANALT=1;MQM=60;MQMR=0;NS=1;NUMALT=1;ODDS=389.99;PAIRED=0.980769;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=1879;QR=0;RO=0;RPL=27;RPP=3.17734;RPPR=0;RPR=25;RUN=1;SAF=30;SAP=5.68288;SAR=22;SRF=0;SRP=0;SRR=0;TYPE=snp;ANN=A|missense_variant|MODERATE|gltA|Gene_BW25113_0720|transcript|Transcript_BW25113_0720|Coding|1/1|c.482C>T|p.Ala161Val|482/1284|482/1284|161/427||  GT:DP:RO:QR:AO:QA:GL    1:52:0:0:52:1879:-169.371,0

 The Gene_ID column stays as "Gene_BW25113_072", but Gene_Name changes from "BW25113_072" to "gltA", which in my opinion is much more useful.

Cheers,
Roy.

**Comment by tseemann** [comment]
I understand what you've done now - sorry I was so slow. I've accepted the change Roy.
