### ISSUE TITLE
vcflib (vcfuniq) on Mac OSX, compilation error??

### ISSUE THREAD

**Issue by nextgenusfs** [tseemann/snippy#67]
Hi Torsten,

So snippy appears to be working correctly, however, by chance I was interested in looking at the options of `vcfuniq` and seeing what it was doing.  I don't know if this is problematic or not, but when I try to run `vcfuniq` from the command line I get the following:
```
ngs@ngs-mac-pro:~$ vcfuniq -h
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string
Abort trap: 6
```
If I run it with any other flag I get the same response, no input and nothing seems to happen (it just runs as perhaps it is expecting something from STDIN?).

So I'm concerned that perhaps it isn't installed correctly and not doing what it is suppose to be doing?  As I said, snippy appears to run to completion and I don't get any error messages.  I'm on Mac 10.10 and have installed snippy using home-brew.

Should I be concerned?

Thanks,
Jon

**Comment by tseemann** [comment]
Most of the `vcflib` tools don't handle empty parameters or help very well and fail like that. I believe @ekg and others are working on improving it. Best to file an Issue at https://github.com/vcflib/vcflib

You should try building the latest version of vcflib yourself (you are on Mac I see), and not rely on the bundled 'backup' binary I provide with Snippy.
