### ISSUE TITLE
Snippy instalation Error :

### ISSUE THREAD

**Issue by hirenbioinfo** [tseemann/snippy#71]
$brew install snippy
Last 15 lines from /home/.cache/Homebrew/Logs/freebayes/02.make:
/usr/include/c++/6/bits/stl_pair.h:425:5: note: candidate: template<class _T1, class _T2> constexpr std::pair<typename std::__decay_and_strip<_Tp>::__type, typename std::__decay_and_strip<_T2>::__type> std::make_pair(_T1&&, _T2&&)
     make_pair(_T1&& __x, _T2&& __y)
     ^~~~~~~~~
/usr/include/c++/6/bits/stl_pair.h:425:5: note:   template argument deduction/substitution failed:
/tmp/freebayes-20160616-14946-1v8a66c/bamtools/src/toolkit/bamtools_resolve.cpp:1051:70: note:   cannot convert â€˜rg.BamTools::SamReadGroup::IDâ€™ (type â€˜const string {aka const std::__cxx11::basic_string<char>}â€™) to type â€˜std::__cxx11::basic_string<char>&&â€™
         m_readGroups.insert( make_pair<string, ReadGroupResolver>(rg.ID, ReadGroupResolver()) );
                                                                   ~~~^~
src/toolkit/CMakeFiles/bamtools_cmd.dir/build.make:257: recipe for target 'src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o' failed
make[2]: *** [src/toolkit/CMakeFiles/bamtools_cmd.dir/bamtools_resolve.cpp.o] Error 1
make[2]: Leaving directory '/tmp/freebayes-20160616-14946-1v8a66c/bamtools/build'
CMakeFiles/Makefile2:523: recipe for target 'src/toolkit/CMakeFiles/bamtools_cmd.dir/all' failed
make[1]: *** [src/toolkit/CMakeFiles/bamtools_cmd.dir/all] Error 2
make[1]: Leaving directory '/tmp/freebayes-20160616-14946-1v8a66c/bamtools/build'
Makefile:130: recipe for target 'all' failed
make: *** [all] Error 2

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/chapmanb/homebrew-cbl/issues

**Comment by tseemann** [comment]
Looks like your brew can't install `freebayes`.   Make sure you `brew update` and try again. It might work better if you `brew install gcc` first.
