### ISSUE TITLE
Snippy-core problem

### ISSUE THREAD

**Issue by FelipeMelis** [tseemann/snippy#73]
Hello,

I am analyzing some bacterial strains. I ran snippy and then ran snippy-core to see the snp-core. 
The problem is when i ran snippy-core with all my data i get 700 core snp but when i ran with a subset of my data i get a less quantity of core snp. When i use others subsets of data i get a higher quantity of 700 core snp.

I would think with a less quantity of data i get a higher quantity of core snp?

Best Regards

**Comment by flashton2003** [comment]
Not necessarily, because if one of the strains that you have in your total collection is low quality, and therefore has lots of positions that were missing in the mapping step, then these positions will be excluded from the core in all strains.

**Comment by tseemann** [comment]
@FelipeMelis the 'core' jumps around when you add/remove samples. it's not always intuitive. check out these slides I have on the topic:

start at slide 22:
https://www.slideshare.net/torstenseemann/snippy-balti-bioinformatics-brum-uk-tue-5-may-2015
