### ISSUE TITLE
Add post-analysis script for SNP density plots, SNP pairwsie distance plots

### ISSUE THREAD

**Issue by flashton2003** [tseemann/snippy#74]
Hey Torst,

How hard would it be to add an extra script that takes a list of snippy output filenames and produces Nullarbor-esque plots, i.e. Pairwise core SNP distances and Core SNP density?

This would definitely save a lot of duplication of effort, as these are common post-SNP call analysis steps.

No worries if it's a hassle.

Ta,

Phil

**Comment by tseemann** [comment]
These plots are done by my Nullarbor pipeline, which uses Snippy as a component.

It would be a nice enhancement, I'll leave this open.

**Comment by tseemann** [comment]
1. If you want the pairwise snps matrix, use `snp-dists` or `disty`.

2. if you want the plots, use Nullarbor or R. 

I won't be adding these features. I think they are best outside this tool.
