### ISSUE TITLE
Use of uninitialized value $header

### ISSUE THREAD

**Issue by jb2cool** [tseemann/snippy#76]
```
[sisadmin@centos-nullarbor` genometrackr]$ nice make -j 1 -C /home/sisadmin/genometrackr/nullarborjb
make: Entering directory `/home/sisadmin/genometrackr/nullarborjb'
mkdir -p SRR1207440
mkdir -p SRR1207460
mkdir -p SRR1207461
mkdir -p SRR1207468
mkdir -p SRR1207483
mkdir -p SRR1207515
snippy-core SRR1207440/SRR1207440 SRR1207460/SRR1207460 SRR1207461/SRR1207461 SRR1207468/SRR1207468 SRR1207483/SRR1207483 SRR1207515/SRR1207515
[15:31:38] Loading Snippy folders
[15:31:38] Using ID 'SRR1207440' for SRR1207440/SRR1207440
Use of uninitialized value $header in pattern match (m//) at /home/sisadmin/.linuxbrew/bin/snippy-core line 215.
Use of uninitialized value $header in concatenation (.) or string at /home/sisadmin/.linuxbrew/bin/snippy-core line 215.
[15:31:38] Unexpected header in SRR1207440/SRR1207440/snps.tab: 
make: *** [core.aln] Error 255
make: Leaving directory `/home/sisadmin/genometrackr/nullarborjb
```

**Comment by jb2cool** [comment]
If i go into ~/.linuxbrew/bin/snippy-core it seems to be this bit it is having a problem with;

my $header = <SNPS>;
$header =~ m/^CHROM/ or err("Unexpected header in $snp_file: $header");

Works fine on Ubuntu/Bio-Linux but for some reason doesn't work on CentOS

**Comment by tseemann** [comment]
This error occurs only if the `snps.tab` file from one of the Snippy runs has no header in it, which could happen if Snippy failed, and it was an empty or blank file.  

What does `ls -l SRR1207440/SRR1207440` say?

**Comment by jb2cool** [comment]
Does indeed seem like a blank file, the snps.tab seems blank for all of these datasets.

[sisadmin@nullarbor-centos genometrackr]$ ls -al nullarbor/SRR1207440/SRR1207440/
total 64
drwxrwxr-x. 3 sisadmin sisadmin 4096 Sep 12 17:17 .
drwxrwxr-x. 3 sisadmin sisadmin 4096 Sep 12 17:17 ..
drwxrwxr-x. 4 sisadmin sisadmin 4096 Sep 12 17:17 reference
-rw-rw-r--. 1 sisadmin sisadmin  273 Sep 12 17:17 snps.bam
-rw-rw-r--. 1 sisadmin sisadmin   24 Sep 12 17:17 snps.bam.bai
-rw-rw-r--. 1 sisadmin sisadmin   28 Sep 12 17:17 snps.depth.gz
-rw-rw-r--. 1 sisadmin sisadmin   70 Sep 12 17:17 snps.depth.gz.tbi
-rw-rw-r--. 1 sisadmin sisadmin 7891 Sep 12 17:17 snps.filt.vcf
-rw-rw-r--. 1 sisadmin sisadmin 2090 Sep 12 17:17 snps.log
-rw-rw-r--. 1 sisadmin sisadmin 7764 Sep 12 17:17 snps.raw.vcf
-rw-rw-r--. 1 sisadmin sisadmin    0 Sep 12 17:17 snps.tab
-rw-rw-r--. 1 sisadmin sisadmin 7891 Sep 12 17:17 snps.vcf
-rw-rw-r--. 1 sisadmin sisadmin 1969 Sep 12 17:17 snps.vcf.gz
-rw-rw-r--. 1 sisadmin sisadmin   72 Sep 12 17:17 snps.vcf.gz.tbi

**Comment by jb2cool** [comment]
This may or may not be important but ~/genometrackr/nullarbor/SRR1207440/SRR1207440/snps.log is telling me that it can't locate Fatal.pm

**Comment by jb2cool** [comment]
Getting closer i think. I have installed Fatal now and I'm getting further but I'm still getting stuck somewhere.

core.tab only lists the headers, it doesn't list any 'data' underneath it. I think because of this core.aln has a zero size and because of this tree.newick has a zero size and because of this tree.svg has a zero size and because of this tree.gif can't be created.

Just trying to re-run this but will then report back with the contents of the folders between a working Bio-Linux PC and a non-working CentOS PC.

**Comment by jb2cool** [comment]
Just finished re-running this and looking at my snps.log it's clearly saying no variants found where as the exact same data on the Bio-Linux machine has a load of variants.

This is what I have in one of my folders;

[sisadmin@nullarbor-centos genometrackr]$ ls -al nullarbor
total 37316
drwxrwxr-x. 8 sisadmin sisadmin     4096 Sep 13 12:05 .
drwxrwxr-x. 3 sisadmin sisadmin     4096 Sep 13 09:00 ..
-rw-rw-r--. 1 sisadmin sisadmin        0 Sep 13 12:05 core.aln
-rw-rw-r--. 1 sisadmin sisadmin 33347705 Sep 13 12:05 core.full.aln
-rw-rw-r--. 1 sisadmin sisadmin      114 Sep 13 12:05 core.nway.tab
-rw-rw-r--. 1 sisadmin sisadmin      114 Sep 13 12:05 core.tab
-rw-rw-r--. 1 sisadmin sisadmin      205 Sep 13 12:05 core.txt
-rw-rw-r--. 1 sisadmin sisadmin      276 Sep 13 12:05 core.vcf
-rw-rw-r--. 1 sisadmin sisadmin      448 Sep 13 12:03 denovo.tab
-rw-rw-r--. 1 sisadmin sisadmin       66 Sep 13 09:00 isolates.txt
-rw-rw-r--. 1 sisadmin sisadmin    24137 Sep 13 09:00 Makefile
-rw-rw-r--. 1 sisadmin sisadmin      552 Sep 13 12:03 mlst2.tab
-rw-rw-r--. 1 sisadmin sisadmin      350 Sep 13 12:03 mlst.tab
-rw-rw-r--. 1 sisadmin sisadmin  4764044 Sep 13 09:00 ref.fa
-rw-rw-r--. 1 sisadmin sisadmin       29 Sep 13 09:00 ref.fa.fai
drwxrwxr-x. 3 sisadmin sisadmin     4096 Sep 13 12:03 SRR1207440
drwxrwxr-x. 3 sisadmin sisadmin     4096 Sep 13 12:04 SRR1207460
drwxrwxr-x. 3 sisadmin sisadmin     4096 Sep 13 12:04 SRR1207461
drwxrwxr-x. 3 sisadmin sisadmin     4096 Sep 13 12:04 SRR1207468
drwxrwxr-x. 3 sisadmin sisadmin     4096 Sep 13 12:04 SRR1207483
drwxrwxr-x. 3 sisadmin sisadmin     4096 Sep 13 12:05 SRR1207515
-rw-rw-r--. 1 sisadmin sisadmin        0 Sep 13 12:05 tree.newick
-rw-rw-r--. 1 sisadmin sisadmin        0 Sep 13 12:05 tree.svg

This may just be a symptom rather than the problem itself, this is my snps.log

### samtools faidx reference/ref.fa

### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.09 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 2.75 seconds elapse.
[bwa_index] Update BWT... 0.04 sec
[bwa_index] Pack forward-only FASTA... 0.05 sec
[bwa_index] Construct SA from BWT and Occ... 0.62 sec
[main] Version: 0.7.15-r1140
[main] CMD: bwa index reference/ref.fa
[main] Real time: 3.836 sec; CPU: 3.560 sec

### mkdir reference/genomes && cp -f reference/ref.fa reference/genomes/ref.fa

### mkdir reference/ref && bgzip -c reference/ref.gff > reference/ref/genes.gff.gz

### (bwa mem  -v 2 -M -R '@RG	ID:snps	SM:snps' -t 4 reference/ref.fa /home/sisadmin/genometrackr/nullarbor/SRR1207440/R1.fq.gz /home/sisadmin/genometrackr/nullarbor/SRR1207440/R2.fq.gz | samtools view -@ 4 -F 3844 -q 60 -S -b -u -T reference/ref.fa - | samtools sort -O bam -o snps.bam -@ 4 -)

### samtools index snps.bam

### samtools depth -q 20 snps.bam | bgzip > snps.depth.gz

### tabix -s 1 -b 2 -e 2 snps.depth.gz

### fasta_generate_regions.py reference/ref.fa.fai 297752 > reference/ref.txt

### freebayes-parallel reference/ref.txt 4 -p 1 -q 20 -m 60 --min-coverage 10 -V -f reference/ref.fa snps.bam > snps.raw.vcf

### /home/sisadmin/.linuxbrew/Cellar/snippy/3.1/bin/snippy-vcf_filter --minqual 10 --mincov 10 --minfrac 0.9  snps.raw.vcf > snps.filt.vcf

Parsing: snps.raw.vcf
No variants found.

### cp snps.filt.vcf snps.vcf

### bgzip -c snps.vcf > snps.vcf.gz

### tabix -p vcf snps.vcf.gz

### /home/sisadmin/.linuxbrew/Cellar/snippy/3.1/bin/snippy-vcf_to_tab --gff reference/ref.gff --ref reference/ref.fa --vcf snps.vcf > snps.tab

Loading reference: reference/ref.fa
Loaded 1 sequences.
Loading features: reference/ref.gff
Parsing variants: snps.vcf
Converted 0 SNPs to TAB format.

### vcf-consensus snps.vcf.gz < reference/ref.fa > snps.consensus.fa

### /home/sisadmin/.linuxbrew/Cellar/snippy/3.1/bin/snippy-vcf_filter --subs snps.filt.vcf > snps.filt.subs.vcf

Parsing: snps.filt.vcf
No variants found.

### bgzip -c snps.filt.subs.vcf > snps.filt.subs.vcf.gz

### tabix -p vcf snps.filt.subs.vcf.gz

### vcf-consensus snps.filt.subs.vcf.gz < reference/ref.fa > snps.consensus.subs.fa

**Comment by tseemann** [comment]
@jb2cool sorry i wasn't able to help you back then. i hope you have got it working now. i agree it is not trivial to install. I think Brew is still the most reliable way to install it.  I've fixed many bugs since you posted last.
