### ISSUE TITLE
Possible for snippy-core to use --minfrac when outputting core snp alignments?

### ISSUE THREAD

**Issue by matbeale** [tseemann/snippy#77]
Having used --minfrac for my snp calling, I would like to generate a core alignment and core vcf that only contains snps/variants above my minimum fraction.  I guess I could combine the .aligned.fa files (or consensus.subs.fa), but it would be nice if snippy-core could do that automatically.  Cheers.

**Comment by flashton2003** [comment]
What is the default behaviour you are seeing here Mat? The .aln file has SNPs in it that were below --minfrac?

**Comment by matbeale** [comment]
Hi Phil,

I'll try to clarify.  

From what I can see, the .aln file from snippy contains the variants filtered according to --minfrac, as does the .filt.vcf, whilst the .consensus.fa uses all good freebayes-detected variants (regardless of --minfrac).  That's fine.

However, it looks to me like the outputs from _snippy-core_ (the .aln .full.aln and .vcf) use the full list of variants (i.e. the one from .consensus.fa), and it doesn't take into account the --minfrac flag (it isn't an option for snippy-core).  I might have that wrong, but that's what it looks like comparing the sequences. 

I have some mixed samples, so need to be able to use --minfrac thresholds to define what variants to include.  What I want is to be able to create a core snp alignment (and .vcf) that only considers snps if they passed --minfrac in each sample.   I could probably try and do it myself, but if snippy-core can do it...  

Cheers,

Mat

**Comment by flashton2003** [comment]
Ah, I see. Good spot.

**Comment by flashton2003** [comment]
I think snippy-core also returns any positions that are variant but that fail --minfrac as reference? I would expect an N in this case? I guess these positions need to be written to the filt.vcf, but highlighted as uncallable?

**Comment by AdmiralenOla** [comment]
I am also wondering about this. I am feeding the output of snippy-core to snp-dists, but this is problematic since positions that fail --minfrac look like they have the reference allele. It would be very nice if there was a way to have these positions as "N" in the core alignment instead.

**Comment by tseemann** [comment]
Yes `snp-dists` was only designed for core alignments where no N or - was present.
I will fix this in 0.3 snp-dists.

https://github.com/tseemann/snippy/tree/version_4  will abandon minfrac/mincov (can still be enabled). it will use stats and GC-coverage correction.
