### ISSUE TITLE
Error reading file 

### ISSUE THREAD

**Issue by YiwenZhou** [tseemann/snippy#78]
Hi, Torsten
Below is the error message in snps.log 
`java.lang.RuntimeException: Error reading file '/home/ubuntu/ResearchProject/Snippy/Wildtype/Wildtype_snps/reference/./ref/genes.gff'
java.lang.StringIndexOutOfBoundsException: String index out of range: -2024846
        at ca.mcgill.mcb.pcingola.snpEffect.factory.SnpEffPredictorFactoryGff.create(SnpEffPredictorFactoryGff.java:132)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdBuild.createSnpEffPredictor(SnpEffCmdBuild.java:115)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:304)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.run(SnpEff.java:883)
        at ca.mcgill.mcb.pcingola.snpEffect.commandLine.SnpEff.main(SnpEff.java:128)` 

I was trying to fix the problem by looking into the scripts but still can't able to solved it.

**Comment by tseemann** [comment]
I have not seen that error before.  But I do know that the latest `snpEff` does NOT work with Snippy anymore. I can not figure out what they have changed.

What versions are you using?

```
% snpEff -version
4.1l

% java -version
java version "1.8.0_102"
```

**Comment by YiwenZhou** [comment]
```%  snpEff -version   
4.2 (build 2015-12-05)```
```% java -version
ava version "1.8.0_101"```

**Comment by tseemann** [comment]
Can you downgrade from to an older `snpEff` like 4.1 ?

I am working on making it always use the bundled `snpEff.jar`  in `snippy/binaries/common`.

**Comment by YiwenZhou** [comment]
i changed to 4.1l version just now, Still same errors, the command i ran ```snippy --cpus 4 --outdir Wildtype_snps --reference sequen
ce.gb --R1 W_S1_L001_1.fastq.gz --R2 W_S1_L001_2.fastq.gz ```
i am wondering that does it have to be .gbk entension ? is this the problem?

**Comment by tseemann** [comment]
@YiwenZhou does the log file say anything about "Detected GBK file" ?

We had some issues with snpEff too, but it seems stable since 4.3 version now.

**Comment by YiwenZhou** [comment]
@tseemann I tried the version 4.3 version, It worked pretty well. Thanks for the help~~:)))
