### ISSUE TITLE
Freebayes Invalid Option

### ISSUE THREAD

**Issue by CNoune** [tseemann/snippy#79]
Hi Torsten,

Not sure what I am doing wrong but I keep getting an invalid option error during the freebayes-parallel step. I've tried using different references (in fasta and gbk format) and cpu count and still getting the error. 

See attached log.
[snps.txt](https://github.com/tseemann/snippy/files/590920/snps.txt)

**Comment by tseemann** [comment]
@CNoune 
`sort: invalid option -- 'O'`
you need to upgrade to samtools 1.3 or higher.
