### ISSUE TITLE
Bioconda Snippy

### ISSUE THREAD

**Issue by esteinig** [tseemann/snippy#80]
Hi Torsten,

thanks for making Snippy available on Bioconda. I ran into a few issues when installing into a virtual-env running Python 3.5:

```bash
conda create -n snippy-test python=3.5
source activate snippy-test
conda install -c=bioconda snippy
```

1. Bioperl could not find SeqIO. Although the folder `Bio` was present in `.../envs/snippy-test/lib/perl5/site_perl/5.22.0/Bio`, the module was not present. Conda installs BioPerl-1.6.924. I replaced the entire folder with the `Bio` directory in [BioPerl-1.007001](http://search.cpan.org/dist/BioPerl/Bio/SeqIO.pm) and this fixed it.

2. When Snippy is installed into the virual-env, the `freebayes-parallel` script is located in `.../envs/snippy-test/bin` but points to `../vcflib/scripts/vcffirstheader` and `../vcflib/bin/vcfstreamsort` which it can't find. I copied `.../envs/snippy-test/binaries/noarch/vcffirstheader` to `.../envs/snippy-test/bin` where `vcfstreamsort` was also located and replaced the references in `freebayes-parallel` with simply `vcfstreamsort` and `vcffirstheader`. This fixed it.

3. `vcffirstheader` starts with `!#/usr/bin/python` which in my case points to Python 3 so replaced it with `!#/usr/bin/python2`

This is all a bit dodgy from my side - are there any better solutions to this or would you be able to make it work right from Bioconda?

Many thanks!

**Comment by tseemann** [comment]
@esteinig 

1. I don't know why Bio::Perl isn't working, I am not the conda packager
2. Open bug in recent freebayes :-(  https://github.com/ekg/freebayes/issues/376
3. That's a vcflib issue. it should be `/usr/bin/env python`. python being 3.x is asking for trouble!

I am told @slugger70 is looking into the conda issue.
