### ISSUE TITLE
Vcf.pm

### ISSUE THREAD

**Issue by plasmid02** [tseemann/snippy#81]
I installed Snippy 3.1 through linuxbrew (thanks for making this option available)!
 One initial problem was that Vcf.pm wasnt avaialble in @INC.  I fixed it by exporting the module:

export PERL5LIB=<PATHTO>/.linuxbrew/Cellar/snippy/3.1/perl5

**Comment by tseemann** [comment]
@plasmid02 `Vcf.pm` is a problem yes, I think the latest Brew formula fixes this problem.
