### ISSUE TITLE
Filter by quality score

### ISSUE THREAD

**Issue by ryjohnson09** [tseemann/snippy#83]
Hi Torsten,

First off, thanks for all the tools you have created...I use them daily! So far Snippy has been great, but I was curious if there was any way to filter the bwa reads by quality score (eg. -q 31) so that only high quality mapped reads are included in the variant call process. Any elaboration on the current quality threshold would be helpful!

Thanks again,
Ryan

**Comment by tseemann** [comment]
There are two qualities to consider:  base quality (often `q`) and read mapping quality (often `Q`).

These are used by `freebayes` and `samtools` at various points in the Snippy pipeline.

Currently, `q` is hard-coded at Phred 20  (1 in 100 error).

`Q` is exposed via the `--mapqual` parameter, and defaults to 60.  In BWA MEM, Q=60 means the read is well aligned, and *uniquely* aligned.   Snippy ignores multimapping reads, and can't call variants in repeat regions (where repeat is defined as longer than the PE read span or fragment size).

**Comment by ryjohnson09** [comment]
Very helpful...thanks for the response!

**Comment by tseemann** [comment]
I've now made `--basequal 20` option. It is used by `samtools` and `freebayes`.
