### ISSUE TITLE
SNP calling more than  --minfrac 0.9

### ISSUE THREAD

**Issue by aphayt** [tseemann/snippy#85]
Hi Torsten 

We have been testing some bacterial isolate stabilities with ngs. I used the starting point isolates as the references from fastq to fasta. After the SNPs were identified, I inspected the short reads aligned to the reference for some of the SNPs with the Tablet. There were 3 positions where the calls were less than 90%. Position A: the reference was a G, short reads 34 Ts and 12 Gs; Position B: the reference was an A, short reads 28 Cs and 12 As; Position C: the reference was a T, short reads 25 Ts and 12 Cs. I have to say this is the first time I have seen this. So my question is whether I can change --minfrac to improve my SNP calling as by default, Snippy should only call a SNP when more than 90% bases differ with the reference?

Many thanks,
Yue

**Comment by tseemann** [comment]
Snippy only uses uniquely mapping reads with mapping quality 60 (this means unique in BWA MEM).
It also only uses bases with Q20 or higher (1 in 100 error).
So your alignment may show more bases than actually took part in the SNP call.

You can change them using these options:

```
  --mapqual [n.n]   Minimum mapping quality to allow (default '60')
  --mincov [N]      Minimum coverage of variant site (default '10')
  --minfrac [n.n]   Minumum proportion for variant evidence (default '0.9')
```
But if you feel you found a real bug in the software, i'm happy to investigate!
