### ISSUE TITLE
Impact of "Warning Got a sequence without letters. Could not guess alphabet"   ; issue #24  ?

### ISSUE THREAD

**Issue by gleveq1** [tseemann/snippy#94]
Hi,

I'm running snippy v3.2 and I also get the above message even though snippy runs to completion.
Is there any impact on snippy's output or is this just a warning that something is off?

Otherwise I'm not sure I understand what your fix was in the response to issue #24.

Thanks in advance,
GL.

**Comment by tseemann** [comment]
@gleveq1 I've seen it a couple of times too.  it's a bioperl warning. I still haven't been able to track it down either.  I planning to finally spend some time on Snippy over the next 2 months so I will drill deeper into this message.

**Comment by gleveq1** [comment]
Ok thanks for the response;  I'll be sure to keep an eye on Snippy's progress going forward!

**Comment by tseemann** [comment]
I've discovered one case where it does appear. It's when we get a consensus sequence with no DNA letters in it, only `N` or `-`.  this can happend when no reads aligned to the reference OR when something went wrong with the BAM creation.

Are these any problems in `snps.log` ?

**Comment by gleveq1** [comment]
No I don't see any of these issues in snps.log.  Also the snps.bam looks fine to me.

Here are the contents of snps.log:

### samtools faidx reference/ref.fa


### bwa index reference/ref.fa

[bwa_index] Pack FASTA... 0.03 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.95 seconds elapse.
[bwa_index] Update BWT... 0.03 sec
[bwa_index] Pack forward-only FASTA... 0.02 sec
[bwa_index] Construct SA from BWT and Occ... 0.36 sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa index reference/ref.fa
[main] Real time: 1.547 sec; CPU: 1.404 sec

### mkdir reference/genomes && cp -f reference/ref.fa reference/genomes/ref.fa


### mkdir reference/ref && bgzip -c reference/ref.gff > reference/ref/genes.gff.gz


### (bwa mem  -v 2 -M -R '@RG	ID:snps	SM:snps' -t 4 reference/ref.fa fake_reads.fq | samtools view -@ 4 -F 3844 -q 60 -S -b -u -T reference/ref.fa - | samtools sort -O bam -o snps.bam -@ 4 -)

[main] Version: 0.7.12-r1039
[main] CMD: bwa mem -v 2 -M -R @RG	ID:snps	SM:snps -t 4 reference/ref.fa fake_reads.fq
[main] Real time: 8.268 sec; CPU: 31.445 sec

### samtools index snps.bam


### samtools depth -q 20 snps.bam | bgzip > snps.depth.gz


### tabix -s 1 -b 2 -e 2 snps.depth.gz


### fasta_generate_regions.py reference/ref.fa.fai 197677 > reference/ref.txt

'import site' failed; use -v for traceback

### freebayes-parallel reference/ref.txt 4 -p 1 -q 20 -m 60 --min-coverage 10 -V -f reference/ref.fa snps.bam > snps.raw.vcf

'import site' failed; use -v for traceback

### /lb/project/mugqic/analyste_dev/software/snippy/bin/snippy-vcf_filter --minqual 10 --mincov 10 --minfrac 0.9  snps.raw.vcf > snps.filt.vcf

Parsing: snps.raw.vcf
Types: snp=2 ins=18 del=17
Passed 37/78 variants (47.44%)

### cp snps.filt.vcf snps.vcf


### bgzip -c snps.vcf > snps.vcf.gz


### tabix -p vcf snps.vcf.gz


### /lb/project/mugqic/analyste_dev/software/snippy/bin/snippy-vcf_to_tab --gff reference/ref.gff --ref reference/ref.fa --vcf snps.vcf > snps.tab

Loading reference: reference/ref.fa
Loaded 5 sequences.
Loading features: reference/ref.gff
Parsing variants: snps.vcf
Converted 37 SNPs to TAB format.

### vcf-consensus snps.vcf.gz < reference/ref.fa > snps.consensus.fa


### /lb/project/mugqic/analyste_dev/software/snippy/bin/snippy-vcf_filter --subs snps.filt.vcf > snps.filt.subs.vcf

Parsing: snps.filt.vcf
Types: snp=2
Passed 2/37 variants (5.41%)

### bgzip -c snps.filt.subs.vcf > snps.filt.subs.vcf.gz


### tabix -p vcf snps.filt.subs.vcf.gz


### vcf-consensus snps.filt.subs.vcf.gz < reference/ref.fa > snps.consensus.subs.fa


### rm -f 'fake_reads.fq'

**Comment by cocathail** [comment]
I too am experiencing this problem. Leads to no variants being called. Any progress? I'm operating on v3.1 I think.

**Comment by sybah2** [comment]
HI tseemann ,
I am following the guideline to download the snippy but I get snippy v3.1. Can you please let me know how to install the latest version 4.0.

Regards,
Saikou

**Comment by swuyts** [comment]
Hi there,

I've got exactly the same problem here. Just installed snippy and tried it on 6 different samples, all generating the same warning message and resulting in no variants.

If some more information needs to be provided, regarding this 'bug'  I'm happy to help!

Kind regards,
Sander

**Comment by swuyts** [comment]
Just a small, hopefully useful, update:

I've got this error when installing Snippy using LinuxBrew on Ubuntu. When I tried to run this again today, the installation was gone, so I decided to use the standard 'git clone' installation.

I've just ran Snippy again, and now it does not trow any errors anymore and result I've also got some SNPs results.

**Comment by tseemann** [comment]
@sybah2 there is no Snippy 4.0 - but I hope to write it one day. Sorry.

**Comment by tseemann** [comment]
@swuyts great to know you got soem results now. it must have something to do with specific versions of software.  but i can't figure out which.  With `brew` you will get up to date versions of most things.

**Comment by amilesj** [comment]
I experienced the same thing as @swuyts: I got this error on all the samples I tried when using Snippy installed via Homebrew on my Mac, but it worked great using the installation from GitHub. Thanks for posting an update, @swuyts! 

I looked in the failed run's log and during alignment bwa mem threw the following error: 

`[E::bwa_set_rg] the read group line contained literal <tab> characters -- replace with escaped tabs: \t`

Looks like you already addressed this in Issue #100, which is probably why it is working fine with the newest release of Snippy from GitHub.

**Comment by cocathail** [comment]
I can also confirm that using a git cloned version of snippy addresses this problem. The brew installed version is the only thing throwing this error for me.

**Comment by indexofire** [comment]
if your abs path contain characters like blank or other language, the warning msg comes out.

**Comment by nenadmacesic** [comment]
@indexofire thank you for posting that - it saved me many hours of pulling my hair out

**Comment by tseemann** [comment]
I finally found the cause of this error. It occurs when writing the `snps_aligned.fa` file which often has lots of `-` and `N` symbols. When Is save it to disk, Bioperl tries to guess it's format, and rejects it. In the Snippy 4 branch i added `-alphabet=>'dna'` to avoid the guesswork.

**Comment by gleveq1** [comment]
Good news!
Thank you for the update.
