### ISSUE TITLE
Extracting loci of SNPs after removal of recombined regions

### ISSUE THREAD

**Issue by kelvin-wcl** [tseemann/snippy#95]
Hi, 
I managed to run Snippy, and generate the csv file of the SNPs (*), then generate the alignment and use the .aln as input to Gubbins.

From Gubbins, I can generate the PDF file of the phylogenetic tree. There is also a csv file which contains a breakdown of the SNPs (in/out recombination region)

My query is: Is there a way of generating a csv file of the SNPS like from Snippy, which lists the SNPs after removal of recombination regions?

Thanks

**Comment by tseemann** [comment]
if you have the gubbins regions in `bed` or `gff` format, and you have the SNPS in `vcf` and `gff` and `bed` then you could use `bedtools to remove the "intersection" of the two.

Or you could use a combination of `grep`, `cut` etc to remove them. But this would require some Unix or programming. I don't have an easy solution for you, sorry.
