### ISSUE TITLE
error: no VCF header

### ISSUE THREAD

**Issue by rbonnet** [tseemann/snippy#97]
Dear Torsten,

I tried to use snippy with own data and the test on linux machine ubuntu 16.04 LTS.
I always obtained the same error 'no VCF header' at the 'freebayes-parallel' step.

Have you an idea ?

thanks per avance

All the best,

Richard
 
### bwa index reference/ref.fa
[bwa_index] Pack FASTA... 0.01 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.11 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.05 sec
[main] Version: 0.7.12-r1039
[main] CMD: bwa index reference/ref.fa
[main] Real time: 0.697 sec; CPU: 0.180 sec
### snpEff build -c reference/snpeff.config -dataDir . -gff3 ref
WARNING: All frames are zero! This seems rather odd, please check that 'frame' information in your 'genes' file is accurate.
### (bwa mem  -v 2 -M -R '@RG	ID:snps	SM:snps' -t 8 reference/ref.fa /usr/local/snippy/test/reads_R1.fastq.gz /usr/local/snippy/test/reads_R2.fastq.gz | samtools view -@ 8 -F 3844 -q 60 -S -b -u -T reference/ref.fa - | samtools sort -O bam -o snps.bam -@ 8 -)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (454, 498, 543)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (276, 721)
[M::mem_pestat] mean and std.dev: (498.46, 65.48)
[M::mem_pestat] low and high boundaries for proper pairs: (187, 810)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[main] Version: 0.7.12-r1039
[main] CMD: bwa mem -v 2 -M -R @RG	ID:snps	SM:snps -t 8 reference/ref.fa /usr/local/snippy/test/reads_R1.fastq.gz /usr/local/snippy/test/reads_R2.fastq.gz
[main] Real time: 2.981 sec; CPU: 14.068 sec
### freebayes-parallel reference/ref.txt 8 -p 1 -q 20 -m 60 --min-coverage 10 -V -f reference/ref.fa snps.bam > snps.raw.vcf

error: no VCF header
Traceback (most recent call last):
  File "/usr/local/snippy/bin/../binaries/noarch/vcffirstheader", line 16, in <module>
    print line.strip()
IOError: [Errno 32] Broken pipe

**Comment by tseemann** [comment]
freebayes-parallel basically runs freebayes in chunks of the genome, then merges them back.

the merging is done like `cat *.vcf | vcffirstheader | vcfstreamsort | vcfuniq > combined.vcf`

Your bwa running time was only 14 seconds which seems very fast. maybe it produced  an empty BAM file.

What does `samtools flagstat snps.bam` say?

**Comment by rbonnet** [comment]
?Thanks Torsten for this clue.
I will check this point when l m black in the lab.
All the best
Richard



Envoyé depuis mon smartphone Samsung Galaxy.


-------- Message d'origine --------
De : Torsten Seemann <notifications@github.com>
Date : 04/08/2017 05:30 (GMT+01:00)
À : tseemann/snippy <snippy@noreply.github.com>
Cc : Bonnet Richard <rbonnet@chu-clermontferrand.fr>, Author <author@noreply.github.com>
Objet : Re: [tseemann/snippy] error: no VCF header (#97)


freebayes-parallel basically runs freebayes in chunks of the genome, then merges them back.

the merging is done like cat *.vcf | vcffirstheader | vcfstreamsort | vcfuniq > combined.vcf

Your bwa running time was only 14 seconds which seems very fast. maybe it produced an empty BAM file.

What does samtools flagstat snps.bam say?

-

**Comment by rbonnet** [comment]
Thanks Torsten for this clue.
I will check this point when l m black in the lab.
All the best
Richard



Envoyé depuis mon smartphone Samsung Galaxy.


-------- Message d'origine --------
De : Torsten Seemann <notifications@github.com>
Date : 04/08/2017 05:30 (GMT+01:00)
À : tseemann/snippy <snippy@noreply.github.com>
Cc : Bonnet Richard <rbonnet@chu-clermontferrand.fr>, Author <author@noreply.github.com>
Objet : Re: [tseemann/snippy] error: no VCF header (#97)


freebayes-parallel basically runs freebayes in chunks of the genome, then merges them back.

the merging is done like cat *.vcf | vcffirstheader | vcfstreamsort | vcfuniq > combined.vcf

Your bwa running time was only 14 seconds which seems very fast. maybe it produced an empty BAM file.

What does samtools flagstat snps.bam say?

-

**Comment by rbonnet** [comment]
Torsten,


That's right ; no mapping occurred, even with the use of the assembly corresponding to the mapped reads as reference.


/usr/local/snippy/binaries/linux/samtools flagstat snps.bam:


2123504 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
2123504 + 0 mapped (100.00% : N/A)
2123504 + 0 paired in sequencing
1064341 + 0 read1
1059163 + 0 read2
2114565 + 0 properly paired (99.58% : N/A)
2120792 + 0 with itself and mate mapped
2712 + 0 singletons (0.13% : N/A)
4821 + 0 with mate mapped to a different chr
4821 + 0 with mate mapped to a different chr (mapQ>=5)


The read files R1 and R2 were generated by the concatenation of two datasets with 'cat'.

That's maybe the reason behind the problem?




All the best,


Richard



________________________________
De : Torsten Seemann <notifications@github.com>
Envoyé : vendredi 4 août 2017 05:30
À : tseemann/snippy
Cc : Bonnet Richard; Author
Objet : Re: [tseemann/snippy] error: no VCF header (#97)


freebayes-parallel basically runs freebayes in chunks of the genome, then merges them back.

the merging is done like cat *.vcf | vcffirstheader | vcfstreamsort | vcfuniq > combined.vcf

Your bwa running time was only 14 seconds which seems very fast. maybe it produced an empty BAM file.

What does samtools flagstat snps.bam say?

-

**Comment by tseemann** [comment]
It looks like they did map ok, which is surprising if you said R1 and R2 were concatendate (rather than interleaved).

I hope you figured it out in the end.
