### ISSUE TITLE
Bio::Perl dependence

### ISSUE THREAD

**Issue by cryptic0** [tseemann/snippy#98]
==> Installing snippy from tseemann/bioinformatics-linux
snippy: Unsatisfied dependency: Bio::Perl
Homebrew does not provide special Perl dependencies; install with:
  `cpan -i Bio::Perl`
Error: An unsatisfied requirement failed this build.

**Comment by tseemann** [comment]
Homebrew is not able to install Perl modules for you.

You need to do that yourself.

Did you try `sudo cpan -i Bio::Perl` ?

**Comment by dougwyu** [comment]
This worked for me on macOS:

snippy requires BioPerl

0) install perl
`brew install perl`

1) install perlbrew
`sudo cpan App::perlbrew`
`~/perl5/perlbrew/bin/perlbrew init`   # run first time to initialise perlbrew

2) use perlbrew to install cpanm (cpan package manager)

`~/perl5/perlbrew/bin/perlbrew install-cpanm` # installs cpanm and also upgrades it
`~/perl5/perlbrew/bin/cpanm --help`

3) use cpanm to install Bio::Perl
`~/perl5/perlbrew/bin/cpanm Bio::Perl` # to install Bioperl

4) install snippy
`brew install snippy`

test files stored at ~/src/snippy/test/  # BTW, where are these available now?

`cd ~/src/snippy/test/`
`snippy --cpus 2 --outdir mysnps --ref example.fna --R1 reads_R1.fastq.gz --R2 reads_R2.fastq.gz`

#### This also worked to install bioperl directly but isn't preferred

`cpan`  # invoke cpan to install bioperl
cpan> `d /bioperl/`  # lists the most recent BioPerl
cpan> `install C/CJ/CJFIELDS/BioPerl-1.007001.tar.gz`

**Comment by tseemann** [comment]
@cryptic0 similar to what @dougwyu suggested, but simpler and avoids Perlbrew.
```
brew install perl
brew install cpanminus
cpanm Bio::Perl
```
